/* Generated by ai2react v0.102.0 - 2021-12-20 21:32 */
/* ai file: CirculoPolitico.ai */

import { makeAi2React } from './src/'
const img0 =
  'https://especiales.latercera.com/boric-presidente-assets/v2/CirculoPolitico-large.jpg'
const img1 =
  'https://especiales.latercera.com/boric-presidente-assets/v2/CirculoPolitico-small.jpg'

const styles = `
  #g-CirculoPolitico-box ,
  #g-CirculoPolitico-box .g-artboard {
    margin:0 auto;
  }
  #g-CirculoPolitico-box p {
    margin:0;
  }
  #g-CirculoPolitico-box .g-aiAbs {
    position:absolute;
  }
  #g-CirculoPolitico-box .g-aiImg {
    position:absolute;
    top:0;
    display:block;
    width:100% !important;
  }
  #g-CirculoPolitico-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-CirculoPolitico-box .g-aiPointText p { white-space: nowrap; }
  #g-CirculoPolitico-large {
    position:relative;
    overflow:hidden;
  }
  #g-CirculoPolitico-large p {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:29px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:24px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-CirculoPolitico-large .g-pstyle0 {
    line-height:38px;
    height:38px;
    font-size:32px;
  }
  #g-CirculoPolitico-large .g-pstyle1 {
    height:29px;
  }
  #g-CirculoPolitico-large .g-pstyle2 {
    height:29px;
    color:rgb(255,255,255);
  }
  #g-CirculoPolitico-large .g-cstyle0 {
    letter-spacing:-0.007em;
  }
  #g-CirculoPolitico-large .g-cstyle1 {
    letter-spacing:-0.018em;
  }
  #g-CirculoPolitico-large .g-cstyle2 {
    letter-spacing:-0.009em;
  }
  #g-CirculoPolitico-large .g-cstyle3 {
    letter-spacing:-0.004em;
  }
  #g-CirculoPolitico-large .g-cstyle4 {
    letter-spacing:-0.02em;
  }
  #g-CirculoPolitico-large .g-cstyle5 {
    letter-spacing:-0.015em;
  }
  #g-CirculoPolitico-large .g-cstyle6 {
    letter-spacing:-0.017em;
  }
  #g-CirculoPolitico-large .g-cstyle7 {
    letter-spacing:-0.019em;
  }
  #g-CirculoPolitico-large .g-cstyle8 {
    letter-spacing:-0.006em;
  }
  #g-CirculoPolitico-large .g-cstyle9 {
    letter-spacing:-0.025em;
  }
  #g-CirculoPolitico-large .g-cstyle10 {
    letter-spacing:-0.005em;
  }
  #g-CirculoPolitico-large .g-cstyle11 {
    letter-spacing:-0.034em;
  }
  #g-CirculoPolitico-large .g-cstyle12 {
    letter-spacing:-0.054em;
  }
  #g-CirculoPolitico-large .g-cstyle13 {
    letter-spacing:-0.013em;
  }
  #g-CirculoPolitico-large .g-cstyle14 {
    letter-spacing:0.032em;
  }
  #g-CirculoPolitico-large .g-cstyle15 {
    letter-spacing:-0.023em;
  }
  #g-CirculoPolitico-large .g-cstyle16 {
    letter-spacing:-0.01em;
  }
  #g-CirculoPolitico-large .g-cstyle17 {
    letter-spacing:-0.011em;
  }
  #g-CirculoPolitico-large .g-cstyle18 {
    letter-spacing:-0.035em;
  }
  #g-CirculoPolitico-large .g-cstyle19 {
    letter-spacing:-0.016em;
  }
  #g-CirculoPolitico-large .g-cstyle20 {
    letter-spacing:-0.036em;
  }
  #g-CirculoPolitico-large .g-cstyle21 {
    letter-spacing:0.005em;
  }
  #g-CirculoPolitico-large .g-cstyle22 {
    letter-spacing:-0.008em;
  }
  #g-CirculoPolitico-large .g-cstyle23 {
    letter-spacing:-0.014em;
  }
  #g-CirculoPolitico-large .g-cstyle24 {
    letter-spacing:0.025em;
  }
  #g-CirculoPolitico-large .g-cstyle25 {
    letter-spacing:-0.024em;
  }
  #g-CirculoPolitico-large .g-cstyle26 {
    letter-spacing:0.006em;
  }
  #g-CirculoPolitico-large .g-cstyle27 {
    letter-spacing:-0.043em;
  }
  #g-CirculoPolitico-large .g-cstyle28 {
    letter-spacing:-0.052em;
  }
  #g-CirculoPolitico-large .g-cstyle29 {
    letter-spacing:-0.059em;
  }
  #g-CirculoPolitico-large .g-cstyle30 {
    letter-spacing:-0.033em;
  }
  #g-CirculoPolitico-large .g-cstyle31 {
    letter-spacing:-0.021em;
  }
  #g-CirculoPolitico-large .g-cstyle32 {
    letter-spacing:-0.055em;
  }
  #g-CirculoPolitico-large .g-cstyle33 {
    letter-spacing:-0.064em;
  }
  #g-CirculoPolitico-small {
    position:relative;
    overflow:hidden;
  }
  #g-CirculoPolitico-small p {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:8px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:7px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-CirculoPolitico-small .g-pstyle0 {
    line-height:11px;
    height:11px;
    font-size:9px;
  }
  #g-CirculoPolitico-small .g-pstyle1 {
    height:8px;
  }
  #g-CirculoPolitico-small .g-pstyle2 {
    height:8px;
    color:rgb(255,255,255);
  }
  #g-CirculoPolitico-small .g-cstyle0 {
    letter-spacing:-0.007em;
  }
  #g-CirculoPolitico-small .g-cstyle1 {
    letter-spacing:-0.018em;
  }
  #g-CirculoPolitico-small .g-cstyle2 {
    letter-spacing:-0.009em;
  }
  #g-CirculoPolitico-small .g-cstyle3 {
    letter-spacing:-0.004em;
  }
  #g-CirculoPolitico-small .g-cstyle4 {
    letter-spacing:-0.02em;
  }
  #g-CirculoPolitico-small .g-cstyle5 {
    letter-spacing:-0.015em;
  }
  #g-CirculoPolitico-small .g-cstyle6 {
    letter-spacing:-0.017em;
  }
  #g-CirculoPolitico-small .g-cstyle7 {
    letter-spacing:-0.019em;
  }
  #g-CirculoPolitico-small .g-cstyle8 {
    letter-spacing:-0.006em;
  }
  #g-CirculoPolitico-small .g-cstyle9 {
    letter-spacing:-0.025em;
  }
  #g-CirculoPolitico-small .g-cstyle10 {
    letter-spacing:-0.005em;
  }
  #g-CirculoPolitico-small .g-cstyle11 {
    letter-spacing:-0.034em;
  }
  #g-CirculoPolitico-small .g-cstyle12 {
    letter-spacing:-0.054em;
  }
  #g-CirculoPolitico-small .g-cstyle13 {
    letter-spacing:-0.013em;
  }
  #g-CirculoPolitico-small .g-cstyle14 {
    letter-spacing:0.032em;
  }
  #g-CirculoPolitico-small .g-cstyle15 {
    letter-spacing:-0.023em;
  }
  #g-CirculoPolitico-small .g-cstyle16 {
    letter-spacing:-0.01em;
  }
  #g-CirculoPolitico-small .g-cstyle17 {
    letter-spacing:-0.011em;
  }
  #g-CirculoPolitico-small .g-cstyle18 {
    letter-spacing:-0.035em;
  }
  #g-CirculoPolitico-small .g-cstyle19 {
    letter-spacing:-0.016em;
  }
  #g-CirculoPolitico-small .g-cstyle20 {
    letter-spacing:-0.036em;
  }
  #g-CirculoPolitico-small .g-cstyle21 {
    letter-spacing:0.005em;
  }
  #g-CirculoPolitico-small .g-cstyle22 {
    letter-spacing:-0.008em;
  }
  #g-CirculoPolitico-small .g-cstyle23 {
    letter-spacing:-0.014em;
  }
  #g-CirculoPolitico-small .g-cstyle24 {
    letter-spacing:0.025em;
  }
  #g-CirculoPolitico-small .g-cstyle25 {
    letter-spacing:-0.024em;
  }
  #g-CirculoPolitico-small .g-cstyle26 {
    letter-spacing:0.006em;
  }
  #g-CirculoPolitico-small .g-cstyle27 {
    letter-spacing:-0.043em;
  }
  #g-CirculoPolitico-small .g-cstyle28 {
    letter-spacing:-0.052em;
  }
  #g-CirculoPolitico-small .g-cstyle29 {
    letter-spacing:-0.059em;
  }
  #g-CirculoPolitico-small .g-cstyle30 {
    letter-spacing:-0.033em;
  }
  #g-CirculoPolitico-small .g-cstyle31 {
    letter-spacing:-0.021em;
  }
  #g-CirculoPolitico-small .g-cstyle32 {
    letter-spacing:-0.055em;
  }
  #g-CirculoPolitico-small .g-cstyle33 {
    letter-spacing:-0.064em;
  }

`

const html = props => `
<div id="g-CirculoPolitico-box" class="ai2html">


  <!-- Artboard: large -->
  <div id="g-CirculoPolitico-large" class="g-artboard" style="width:1280px; height:2901px;" data-aspect-ratio="0.441" data-min-width="1280">
<div style=""></div>
    <img id="g-CirculoPolitico-large-img" class="g-aiImg" alt="" src="${img0}"/>
    <div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:2.2396%;margin-top:-22px;left:2.2483%;width:421px;">
      <p class="g-pstyle0">CÍ<span class="g-cstyle0">R</span>CU<span class="g-cstyle1">L</span>O POLÍTICO CE<span class="g-cstyle2">R</span><span class="g-cstyle3">C</span>ANO</p>
    </div>
    <div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:4.2463%;margin-top:-16.2px;left:82.5574%;width:219px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>atricio <span class="g-cstyle4">F</span>ernández,</p>
    </div>
    <div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:5.1425%;margin-top:-16.2px;left:84.8505%;width:160px;">
      <p class="g-pstyle1">constitu<span class="g-cstyle5">y</span>en<span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:5.177%;margin-top:-16.2px;left:51.7136%;width:125px;">
      <p class="g-pstyle1">Sebastián</p>
    </div>
    <div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:6.0732%;margin-top:-16.2px;left:51.4211%;width:128px;">
      <p class="g-pstyle1">Kralj<span class="g-cstyle1">e</span>vich,</p>
    </div>
    <div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:6.9695%;margin-top:-16.2px;left:52.218%;width:119px;">
      <p class="g-pstyle1">sociólogo</p>
    </div>
    <div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:7.1074%;margin-top:-16.2px;left:1.7749%;width:189px;">
      <p class="g-pstyle1">Giorgio Jackson,</p>
    </div>
    <div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:7.2452%;margin-top:-16.2px;left:24.4943%;width:158px;">
      <p class="g-pstyle1">Nicolás Grau,</p>
    </div>
    <div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.0036%;margin-top:-16.2px;left:1.7749%;width:251px;">
      <p class="g-pstyle1">diputado salien<span class="g-cstyle7">t</span>e (RD)</p>
    </div>
    <div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.1415%;margin-top:-16.2px;left:71.6112%;width:160px;">
      <p class="g-pstyle1"><span class="g-cstyle8">K</span>a<span class="g-cstyle1">r</span>ol Cariola,</p>
    </div>
    <div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.1415%;margin-top:-16.2px;left:25.1786%;width:143px;">
      <p class="g-pstyle1">economista</p>
    </div>
    <div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.0377%;margin-top:-16.2px;left:71.6112%;width:113px;">
      <p class="g-pstyle1">diputada</p>
    </div>
    <div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.934%;margin-top:-16.2px;left:71.6112%;width:154px;">
      <p class="g-pstyle1">reelecta (PC)</p>
    </div>
    <div id="g-ai0-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.9684%;margin-top:-16.2px;left:37.8105%;width:181px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>atricia Muñoz,</p>
    </div>
    <div id="g-ai0-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:10.8647%;margin-top:-16.2px;left:39.1474%;width:162px;">
      <p class="g-pstyle1">de<span class="g-cstyle9">f</span>ensora de </p>
    </div>
    <div id="g-ai0-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:11.7609%;margin-top:-16.2px;left:43.6773%;width:104px;">
      <p class="g-pstyle1">la Niñez</p>
    </div>
    <div id="g-ai0-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:11.7954%;margin-top:-16.2px;left:17.0693%;width:84px;">
      <p class="g-pstyle1"><span class="g-cstyle4">F</span>elipe</p>
    </div>
    <div id="g-ai0-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:12.1401%;margin-top:-16.2px;left:83.7759%;width:163px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>aul<span class="g-cstyle10">e</span>t<span class="g-cstyle6">t</span>e Jara,</p>
    </div>
    <div id="g-ai0-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:12.6916%;margin-top:-16.2px;left:14.9167%;width:139px;">
      <p class="g-pstyle1"><span class="g-cstyle11">V</span>alenzuela,</p>
    </div>
    <div id="g-ai0-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:13.0364%;margin-top:-16.2px;left:83.7759%;width:211px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>xje<span class="g-cstyle2">f</span>a de gabin<span class="g-cstyle10">e</span><span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai0-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:13.5879%;margin-top:-16.2px;left:15.4943%;width:124px;">
      <p class="g-pstyle1">periodista</p>
    </div>
    <div id="g-ai0-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:14.8633%;margin-top:-16.2px;left:29.1818%;width:174px;">
      <p class="g-pstyle1">Camila <span class="g-cstyle11">V</span>allejo,</p>
    </div>
    <div id="g-ai0-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:15.7596%;margin-top:-16.2px;left:29.1818%;width:113px;">
      <p class="g-pstyle1">diputada</p>
    </div>
    <div id="g-ai0-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.6558%;margin-top:-16.2px;left:29.1818%;width:151px;">
      <p class="g-pstyle1">salien<span class="g-cstyle6">t</span>e (PC)</p>
    </div>
    <div id="g-ai0-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:18.8619%;margin-top:-16.2px;left:40.9118%;width:160px;">
      <p class="g-pstyle1">Miguel Crispi,</p>
    </div>
    <div id="g-ai0-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.7582%;margin-top:-16.2px;left:44.568%;width:113px;">
      <p class="g-pstyle1">diputado</p>
    </div>
    <div id="g-ai0-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:20.1718%;margin-top:-16.2px;left:1.4805%;width:183px;">
      <p class="g-pstyle1">Gonzalo Win<span class="g-cstyle6">t</span>e<span class="g-cstyle12">r</span>,</p>
    </div>
    <div id="g-ai0-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:20.6544%;margin-top:-16.2px;left:45.3424%;width:103px;">
      <p class="g-pstyle1">salien<span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai0-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.0681%;margin-top:-16.2px;left:4.1505%;width:113px;">
      <p class="g-pstyle1">diputado</p>
    </div>
    <div id="g-ai0-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.6196%;margin-top:-16.2px;left:91.7487%;width:77px;">
      <p class="g-pstyle1"><span class="g-cstyle13">L</span>ucía</p>
    </div>
    <div id="g-ai0-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.9486%;margin-top:-16.7px;left:54.4763%;width:119px;">
      <p class="g-pstyle2">&iquest;A QUIÉN</p>
    </div>
    <div id="g-ai0-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.9643%;margin-top:-16.2px;left:2.6074%;width:152px;">
      <p class="g-pstyle1">reelec<span class="g-cstyle6">t</span>o (CS)</p>
    </div>
    <div id="g-ai0-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:22.5158%;margin-top:-16.2px;left:89.8717%;width:127px;">
      <p class="g-pstyle1">Damme<span class="g-cstyle14">r</span>t,</p>
    </div>
    <div id="g-ai0-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:22.8261%;margin-top:-16.2px;left:53.9513%;width:133px;">
      <p class="g-pstyle2">ESCUCHA?</p>
    </div>
    <div id="g-ai0-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:23.4121%;margin-top:-16.2px;left:90.1305%;width:119px;">
      <p class="g-pstyle1">socióloga</p>
    </div>
    <div id="g-ai0-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:23.8257%;margin-top:-16.2px;left:30.0011%;width:251px;">
      <p class="g-pstyle1">J<span class="g-cstyle15">a</span>viera &ldquo;<span class="g-cstyle5">P</span>elo&rdquo; Cabello,</p>
    </div>
    <div id="g-ai0-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:24.465%;margin-top:-16.7px;left:19.0568%;width:113px;">
      <p class="g-pstyle2">CÍ<span class="g-cstyle0">R</span>CU<span class="g-cstyle1">L</span>O</p>
    </div>
    <div id="g-ai0-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:24.722%;margin-top:-16.2px;left:29.9096%;width:196px;">
      <p class="g-pstyle1">je<span class="g-cstyle2">f</span>a de ca<span class="g-cstyle16">m</span>paña</p>
    </div>
    <div id="g-ai0-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.3769%;margin-top:-16.2px;left:18.095%;width:137px;">
      <p class="g-pstyle2">DE HIER<span class="g-cstyle16">R</span>O</p>
    </div>
    <div id="g-ai0-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.1353%;margin-top:-16.2px;left:77.9149%;width:291px;">
      <p class="g-pstyle1">Matías Meza-Lopehendía, </p>
    </div>
    <div id="g-ai0-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:27.0315%;margin-top:-16.2px;left:77.9149%;width:256px;">
      <p class="g-pstyle1">académico <span class="g-cstyle17">U</span>. Católica </p>
    </div>
    <div id="g-ai0-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:27.9278%;margin-top:-16.2px;left:77.9149%;width:161px;">
      <p class="g-pstyle1">de <span class="g-cstyle18">V</span>alparaíso</p>
    </div>
    <div id="g-ai0-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.6172%;margin-top:-16.2px;left:1.7749%;width:251px;">
      <p class="g-pstyle1">Constanza Schonhaut,</p>
    </div>
    <div id="g-ai0-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.5134%;margin-top:-16.2px;left:1.7749%;width:211px;">
      <p class="g-pstyle1">constitu<span class="g-cstyle5">y</span>en<span class="g-cstyle6">t</span>e (RD)</p>
    </div>
    <div id="g-ai0-45" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:31.2714%;margin-top:-16.2px;left:67.4411%;width:200px;">
      <p class="g-pstyle1">An<span class="g-cstyle5">t</span>onia Orellana,</p>
    </div>
    <div id="g-ai0-46" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:32.0643%;margin-top:-16.2px;left:52.5818%;width:169px;">
      <p class="g-pstyle1">Diego <span class="g-cstyle10">P</span>a<span class="g-cstyle19">r</span>d<span class="g-cstyle13">o</span><span class="g-cstyle20">w</span>,</p>
    </div>
    <div id="g-ai0-47" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:32.1677%;margin-top:-16.2px;left:67.4411%;width:124px;">
      <p class="g-pstyle1">periodista</p>
    </div>
    <div id="g-ai0-48" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:32.9605%;margin-top:-16.2px;left:54.7511%;width:112px;">
      <p class="g-pstyle1">abogado</p>
    </div>
    <div id="g-ai0-49" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.512%;margin-top:-16.2px;left:83.3936%;width:195px;">
      <p class="g-pstyle1">J<span class="g-cstyle15">a</span>viera Ma<span class="g-cstyle14">r</span>tínez,</p>
    </div>
    <div id="g-ai0-50" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.4083%;margin-top:-16.2px;left:81.5898%;width:220px;">
      <p class="g-pstyle1">ingeniera industrial</p>
    </div>
    <div id="g-ai0-51" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.5462%;margin-top:-16.2px;left:63.661%;width:212px;">
      <p class="g-pstyle1">Claudia Sanhueza,</p>
    </div>
    <div id="g-ai0-52" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.9943%;margin-top:-16.2px;left:41.4311%;width:177px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>ablo <span class="g-cstyle10">P</span>aredes,</p>
    </div>
    <div id="g-ai0-53" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.4424%;margin-top:-16.2px;left:66.4362%;width:143px;">
      <p class="g-pstyle1">economista</p>
    </div>
    <div id="g-ai0-54" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8905%;margin-top:-16.2px;left:40.518%;width:188px;">
      <p class="g-pstyle1">direc<span class="g-cstyle19">t</span>or creati<span class="g-cstyle19">v</span>o</p>
    </div>
    <div id="g-ai0-55" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:41.5438%;margin-top:-16.2px;left:85.3642%;width:160px;">
      <p class="g-pstyle1">Lorena <span class="g-cstyle20">F</span>ries, </p>
    </div>
    <div id="g-ai0-56" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.44%;margin-top:-16.2px;left:85.3642%;width:182px;">
      <p class="g-pstyle1">diputada electa</p>
    </div>
    <div id="g-ai0-57" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:45.1632%;margin-top:-16.2px;left:48.2554%;width:101px;">
      <p class="g-pstyle2">EQUIPO</p>
    </div>
    <div id="g-ai0-58" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.4731%;margin-top:-16.2px;left:70.1993%;width:225px;">
      <p class="g-pstyle1">Mai<span class="g-cstyle19">t</span>e Gamba<span class="g-cstyle19">r</span>della,</p>
    </div>
    <div id="g-ai0-59" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.0591%;margin-top:-16.2px;left:1.7073%;width:188px;">
      <p class="g-pstyle1">Andrea <span class="g-cstyle1">R</span>ep<span class="g-cstyle10">e</span>t<span class="g-cstyle5">t</span>o,</p>
    </div>
    <div id="g-ai0-60" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.3693%;margin-top:-16.2px;left:78.8692%;width:112px;">
      <p class="g-pstyle1">abogada</p>
    </div>
    <div id="g-ai0-61" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.9553%;margin-top:-16.2px;left:5.2137%;width:143px;">
      <p class="g-pstyle1">economista</p>
    </div>
    <div id="g-ai0-62" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:48.6448%;margin-top:-16.2px;left:47.172%;width:173px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>ablo Zamora,</p>
    </div>
    <div id="g-ai0-63" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:48.8516%;margin-top:-16.2px;left:18.2861%;width:178px;">
      <p class="g-pstyle1">Carlos Gaja<span class="g-cstyle6">r</span>do,</p>
    </div>
    <div id="g-ai0-64" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.541%;margin-top:-16.2px;left:49.5851%;width:139px;">
      <p class="g-pstyle1">cofundador</p>
    </div>
    <div id="g-ai0-65" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.7478%;margin-top:-16.2px;left:18.2861%;width:99px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>x<span class="g-cstyle21">f</span>iscal</p>
    </div>
    <div id="g-ai0-66" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:50.4372%;margin-top:-16.2px;left:51.1375%;width:119px;">
      <p class="g-pstyle1">de N<span class="g-cstyle22">o</span>tCO</p>
    </div>
    <div id="g-ai0-67" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:50.8164%;margin-top:-16.2px;left:82.1918%;width:197px;">
      <p class="g-pstyle1">Ma<span class="g-cstyle5">r</span>cela Serrano,</p>
    </div>
    <div id="g-ai0-68" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:51.7127%;margin-top:-16.2px;left:82.1918%;width:111px;">
      <p class="g-pstyle1">escri<span class="g-cstyle5">t</span>ora</p>
    </div>
    <div id="g-ai0-69" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:54.884%;margin-top:-16.2px;left:52.7348%;width:138px;">
      <p class="g-pstyle2">MEN<span class="g-cstyle23">T</span>ORES</p>
    </div>
    <div id="g-ai0-70" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:58.1932%;margin-top:-16.2px;left:86.8117%;width:142px;">
      <p class="g-pstyle1">Carlos <span class="g-cstyle4">R</span>uiz,</p>
    </div>
    <div id="g-ai0-71" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:59.0894%;margin-top:-16.2px;left:87.7306%;width:119px;">
      <p class="g-pstyle1">sociólogo</p>
    </div>
    <div id="g-ai0-72" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:59.4341%;margin-top:-16.2px;left:5.337%;width:120px;">
      <p class="g-pstyle2">FICHAJES</p>
    </div>
    <div id="g-ai0-73" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:59.7099%;margin-top:-16.2px;left:19.443%;width:265px;">
      <p class="g-pstyle1">S<span class="g-cstyle19">t</span>epha<span class="g-cstyle4">n</span>y Gri<span class="g-cstyle24">f</span><span class="g-cstyle21">f</span>ith-Jones,</p>
    </div>
    <div id="g-ai0-74" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:60.6062%;margin-top:-16.2px;left:24.2186%;width:143px;">
      <p class="g-pstyle1">economista</p>
    </div>
    <div id="g-ai0-75" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:61.3645%;margin-top:-16.2px;left:80.9149%;width:185px;">
      <p class="g-pstyle1"><span class="g-cstyle4">F</span>ernando <span class="g-cstyle6">A</span>tria, </p>
    </div>
    <div id="g-ai0-76" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.2608%;margin-top:-16.2px;left:80.9149%;width:160px;">
      <p class="g-pstyle1">constitu<span class="g-cstyle5">y</span>en<span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai0-77" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.3635%;margin-top:-16.2px;left:35.6411%;width:104px;">
      <p class="g-pstyle1">Ma<span class="g-cstyle5">r</span>celo</p>
    </div>
    <div id="g-ai0-78" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.6392%;margin-top:-16.2px;left:54.0892%;width:134px;">
      <p class="g-pstyle1"><span class="g-cstyle13">L</span>uis Maira,</p>
    </div>
    <div id="g-ai0-79" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:65.2597%;margin-top:-16.2px;left:35.6411%;width:89px;">
      <p class="g-pstyle1">Lagos,</p>
    </div>
    <div id="g-ai0-80" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:65.5355%;margin-top:-16.2px;left:53.1367%;width:167px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>xminist<span class="g-cstyle6">r</span>o de </p>
    </div>
    <div id="g-ai0-81" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.156%;margin-top:-16.2px;left:35.6411%;width:113px;">
      <p class="g-pstyle1">geógra<span class="g-cstyle25">f</span>o</p>
    </div>
    <div id="g-ai0-82" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.4317%;margin-top:-16.2px;left:52.773%;width:177px;">
      <p class="g-pstyle1">Plani<span class="g-cstyle26">f</span>icación y </p>
    </div>
    <div id="g-ai0-83" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.328%;margin-top:-16.2px;left:53.4779%;width:150px;">
      <p class="g-pstyle1">Cooperación</p>
    </div>
    <div id="g-ai0-84" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:68.2242%;margin-top:-16.2px;left:68.3223%;width:184px;">
      <p class="g-pstyle1">Manuel An<span class="g-cstyle19">t</span>onio</p>
    </div>
    <div id="g-ai0-85" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.1205%;margin-top:-16.2px;left:70.7918%;width:118px;">
      <p class="g-pstyle1">Garr<span class="g-cstyle10">e</span>tón,</p>
    </div>
    <div id="g-ai0-86" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4996%;margin-top:-16.2px;left:37.9155%;width:175px;">
      <p class="g-pstyle1">Edua<span class="g-cstyle6">r</span>do Engel,</p>
    </div>
    <div id="g-ai0-87" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.0167%;margin-top:-16.2px;left:70.8029%;width:119px;">
      <p class="g-pstyle1">sociólogo</p>
    </div>
    <div id="g-ai0-88" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.3959%;margin-top:-16.2px;left:37.9155%;width:153px;">
      <p class="g-pstyle1">fundador de </p>
    </div>
    <div id="g-ai0-89" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:71.2921%;margin-top:-16.2px;left:37.9155%;width:183px;">
      <p class="g-pstyle1">Espacio Público</p>
    </div>
    <div id="g-ai0-90" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:71.6368%;margin-top:-16.2px;left:9.978%;width:149px;">
      <p class="g-pstyle1">Izkia Siches,</p>
    </div>
    <div id="g-ai0-91" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:72.5331%;margin-top:-16.2px;left:9.978%;width:192px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>xpresidenta del</p>
    </div>
    <div id="g-ai0-92" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:73.4293%;margin-top:-16.2px;left:9.978%;width:179px;">
      <p class="g-pstyle1">Colegio Médico</p>
    </div>
    <div id="g-ai0-93" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:74.9805%;margin-top:-16.2px;left:84.6855%;width:178px;">
      <p class="g-pstyle1">Camila Arenas,</p>
    </div>
    <div id="g-ai0-94" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.8768%;margin-top:-16.2px;left:84.6855%;width:119px;">
      <p class="g-pstyle1">p<span class="g-cstyle6">r</span>o<span class="g-cstyle9">f</span>esora</p>
    </div>
    <div id="g-ai0-95" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:76.0491%;margin-top:-16.2px;left:53.1413%;width:128px;">
      <p class="g-pstyle2"><span class="g-cstyle27">P</span>ARTIDOS</p>
    </div>
    <div id="g-ai0-96" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:78.4621%;margin-top:-16.2px;left:70.7524%;width:103px;">
      <p class="g-pstyle2">FRENTE</p>
    </div>
    <div id="g-ai0-97" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.186%;margin-top:-16.2px;left:23.6937%;width:207px;">
      <p class="g-pstyle1">Guillermo Larraín,</p>
    </div>
    <div id="g-ai0-98" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3238%;margin-top:-16.2px;left:70.7018%;width:104px;">
      <p class="g-pstyle2">AMPLIO</p>
    </div>
    <div id="g-ai0-99" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.0822%;margin-top:-16.2px;left:23.6937%;width:191px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>xpresiden<span class="g-cstyle1">t</span>e del</p>
    </div>
    <div id="g-ai0-100" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.2201%;margin-top:-16.2px;left:2.1949%;width:174px;">
      <p class="g-pstyle1">Ma<span class="g-cstyle5">r</span>celo Mena,</p>
    </div>
    <div id="g-ai0-101" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.9784%;margin-top:-16.2px;left:23.6937%;width:163px;">
      <p class="g-pstyle1">Banco Estado</p>
    </div>
    <div id="g-ai0-102" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.1163%;margin-top:-16.2px;left:2.1949%;width:167px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>xminist<span class="g-cstyle6">r</span>o del</p>
    </div>
    <div id="g-ai0-103" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:82.0126%;margin-top:-16.2px;left:2.1949%;width:191px;">
      <p class="g-pstyle1">Medio Ambien<span class="g-cstyle1">t</span>e</p>
    </div>
    <div id="g-ai0-104" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:83.0122%;margin-top:-16.2px;left:82.9305%;width:209px;">
      <p class="g-pstyle1">Sebastián Depolo,</p>
    </div>
    <div id="g-ai0-105" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:83.1501%;margin-top:-16.2px;left:56.4128%;width:114px;">
      <p class="g-pstyle2"><span class="g-cstyle27">P</span>ARTIDO</p>
    </div>
    <div id="g-ai0-106" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:83.5293%;margin-top:-16.2px;left:37.3692%;width:91px;">
      <p class="g-pstyle2">NUE<span class="g-cstyle20">V</span>A</p>
    </div>
    <div id="g-ai0-107" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:83.9085%;margin-top:-16.2px;left:86.4368%;width:119px;">
      <p class="g-pstyle1">sociólogo</p>
    </div>
    <div id="g-ai0-108" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.0119%;margin-top:-16.2px;left:55.2014%;width:145px;">
      <p class="g-pstyle2">COMUNIS<span class="g-cstyle28">T</span>A</p>
    </div>
    <div id="g-ai0-109" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.3753%;margin-top:-16.7px;left:36.3173%;width:118px;">
      <p class="g-pstyle2">M<span class="g-cstyle29">A</span><span class="g-cstyle30">Y</span>ORÍA</p>
    </div>
    <div id="g-ai0-110" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:86.4248%;margin-top:-16.2px;left:82.1954%;width:198px;">
      <p class="g-pstyle1">Beatriz Sánchez, </p>
    </div>
    <div id="g-ai0-111" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:86.9074%;margin-top:-16.2px;left:1.8874%;width:196px;">
      <p class="g-pstyle1">M<span class="g-cstyle31">a</span><span class="g-cstyle8">y</span>a <span class="g-cstyle4">F</span>ernández,</p>
    </div>
    <div id="g-ai0-112" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.3211%;margin-top:-16.2px;left:82.1954%;width:160px;">
      <p class="g-pstyle1">constitu<span class="g-cstyle5">y</span>en<span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai0-113" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.8037%;margin-top:-16.2px;left:1.6323%;width:200px;">
      <p class="g-pstyle1">diputada salien<span class="g-cstyle1">t</span>e</p>
    </div>
    <div id="g-ai0-114" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:88.6999%;margin-top:-16.2px;left:12.1473%;width:64px;">
      <p class="g-pstyle1">(PS)</p>
    </div>
    <div id="g-ai0-115" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.5603%;margin-top:-16.2px;left:38.154%;width:180px;">
      <p class="g-pstyle1">Carlos Mon<span class="g-cstyle1">t</span>es, </p>
    </div>
    <div id="g-ai0-116" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:94.4566%;margin-top:-16.2px;left:37.4771%;width:198px;">
      <p class="g-pstyle1">senador salien<span class="g-cstyle7">t</span>e </p>
    </div>
    <div id="g-ai0-117" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.3528%;margin-top:-16.2px;left:42.4496%;width:64px;">
      <p class="g-pstyle1">(PS)</p>
    </div>
    <div id="g-ai0-118" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.663%;margin-top:-16.2px;left:54.5134%;width:159px;">
      <p class="g-pstyle1">Irací Hassle<span class="g-cstyle32">r</span>, </p>
    </div>
    <div id="g-ai0-119" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.2835%;margin-top:-16.2px;left:4.3005%;width:176px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>aula Na<span class="g-cstyle24">r</span>váez,</p>
    </div>
    <div id="g-ai0-120" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.5593%;margin-top:-16.2px;left:54.5921%;width:158px;">
      <p class="g-pstyle1">alcaldesa de </p>
    </div>
    <div id="g-ai0-121" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.1108%;margin-top:-16.2px;left:70.8878%;width:231px;">
      <p class="g-pstyle1"><span class="g-cstyle4">F</span>ernando Carmona, </p>
    </div>
    <div id="g-ai0-122" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.1798%;margin-top:-16.2px;left:6.6011%;width:147px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span><span class="g-cstyle5">x</span>candidata</p>
    </div>
    <div id="g-ai0-123" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.2142%;margin-top:-16.2px;left:22.5518%;width:154px;">
      <p class="g-pstyle1">Víc<span class="g-cstyle5">t</span>or <span class="g-cstyle33">T</span>orres,</p>
    </div>
    <div id="g-ai0-124" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.4555%;margin-top:-16.2px;left:56.1183%;width:113px;">
      <p class="g-pstyle1">Santiago</p>
    </div>
    <div id="g-ai0-125" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.0071%;margin-top:-16.2px;left:70.8878%;width:143px;">
      <p class="g-pstyle1">economista</p>
    </div>
    <div id="g-ai0-126" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.076%;margin-top:-16.2px;left:2.8923%;width:195px;">
      <p class="g-pstyle1">presidencial (PS)</p>
    </div>
    <div id="g-ai0-127" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.1105%;margin-top:-16.2px;left:22.5518%;width:250px;">
      <p class="g-pstyle1">diputado salien<span class="g-cstyle7">t</span>e (DC)</p>
    </div>
    <div id="g-ai0-128" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:99.0067%;margin-top:-16.2px;left:22.5518%;width:28px;">
      <p class="g-pstyle1"> </p>
    </div>
  </div>

  <!-- Artboard: small -->
  <div id="g-CirculoPolitico-small" class="g-artboard" style="max-width: 360px;max-height: 815px" data-aspect-ratio="0.442" data-min-width="0" data-max-width="1279">
<div style="padding: 0 0 226.3889% 0;"></div>
    <img id="g-CirculoPolitico-small-img" class="g-aiImg" alt="" src="${img1}"/>
    <div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:2.2493%;margin-top:-6.3px;left:2.3039%;width:134px;">
      <p class="g-pstyle0">CÍ<span class="g-cstyle0">R</span>CU<span class="g-cstyle1">L</span>O POLÍTICO CE<span class="g-cstyle2">R</span><span class="g-cstyle3">C</span>ANO</p>
    </div>
    <div id="g-ai1-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:4.2142%;margin-top:-4.3px;left:82.5488%;width:77px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>atricio <span class="g-cstyle4">F</span>ernández,</p>
    </div>
    <div id="g-ai1-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:5.0731%;margin-top:-4.3px;left:84.8402%;width:61px;">
      <p class="g-pstyle1">constitu<span class="g-cstyle5">y</span>en<span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai1-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:5.1958%;margin-top:-4.3px;left:51.7296%;width:51px;">
      <p class="g-pstyle1">Sebastián</p>
    </div>
    <div id="g-ai1-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:6.0547%;margin-top:-4.3px;left:51.4372%;width:52px;">
      <p class="g-pstyle1">Kralj<span class="g-cstyle1">e</span>vich,</p>
    </div>
    <div id="g-ai1-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:6.9136%;margin-top:-4.3px;left:52.2336%;width:49px;">
      <p class="g-pstyle1">sociólogo</p>
    </div>
    <div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:7.0363%;margin-top:-4.3px;left:1.8305%;width:69px;">
      <p class="g-pstyle1">Giorgio Jackson,</p>
    </div>
    <div id="g-ai1-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:7.159%;margin-top:-4.3px;left:24.5321%;width:60px;">
      <p class="g-pstyle1">Nicolás Grau,</p>
    </div>
    <div id="g-ai1-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.0179%;margin-top:-4.3px;left:1.8305%;width:86px;">
      <p class="g-pstyle1">diputado salien<span class="g-cstyle7">t</span>e (RD)</p>
    </div>
    <div id="g-ai1-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.1406%;margin-top:-4.3px;left:71.6113%;width:61px;">
      <p class="g-pstyle1"><span class="g-cstyle8">K</span>a<span class="g-cstyle1">r</span>ol Cariola,</p>
    </div>
    <div id="g-ai1-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.1406%;margin-top:-4.3px;left:25.2159%;width:56px;">
      <p class="g-pstyle1">economista</p>
    </div>
    <div id="g-ai1-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.9995%;margin-top:-4.3px;left:71.6113%;width:48px;">
      <p class="g-pstyle1">diputada</p>
    </div>
    <div id="g-ai1-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.8584%;margin-top:-4.3px;left:71.6113%;width:59px;">
      <p class="g-pstyle1">reelecta (PC)</p>
    </div>
    <div id="g-ai1-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.9811%;margin-top:-4.3px;left:37.8375%;width:67px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>atricia Muñoz,</p>
    </div>
    <div id="g-ai1-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:10.84%;margin-top:-4.3px;left:39.1734%;width:61px;">
      <p class="g-pstyle1">de<span class="g-cstyle9">f</span>ensora de </p>
    </div>
    <div id="g-ai1-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:11.6989%;margin-top:-4.3px;left:43.6998%;width:45px;">
      <p class="g-pstyle1">la Niñez</p>
    </div>
    <div id="g-ai1-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:11.8216%;margin-top:-4.3px;left:17.1129%;width:39px;">
      <p class="g-pstyle1"><span class="g-cstyle4">F</span>elipe</p>
    </div>
    <div id="g-ai1-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:12.067%;margin-top:-4.3px;left:83.7663%;width:62px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>aul<span class="g-cstyle10">e</span>t<span class="g-cstyle6">t</span>e Jara,</p>
    </div>
    <div id="g-ai1-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:12.6805%;margin-top:-4.3px;left:14.962%;width:55px;">
      <p class="g-pstyle1"><span class="g-cstyle11">V</span>alenzuela,</p>
    </div>
    <div id="g-ai1-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:13.0486%;margin-top:-4.3px;left:83.7663%;width:75px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>xje<span class="g-cstyle2">f</span>a de gabin<span class="g-cstyle10">e</span><span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai1-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:13.5394%;margin-top:-4.3px;left:15.5393%;width:51px;">
      <p class="g-pstyle1">periodista</p>
    </div>
    <div id="g-ai1-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:14.7663%;margin-top:-4.3px;left:29.2158%;width:65px;">
      <p class="g-pstyle1">Camila <span class="g-cstyle11">V</span>allejo,</p>
    </div>
    <div id="g-ai1-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:15.7479%;margin-top:-4.3px;left:29.2158%;width:48px;">
      <p class="g-pstyle1">diputada</p>
    </div>
    <div id="g-ai1-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.6068%;margin-top:-4.3px;left:29.2158%;width:58px;">
      <p class="g-pstyle1">salien<span class="g-cstyle6">t</span>e (PC)</p>
    </div>
    <div id="g-ai1-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:18.8154%;margin-top:-4.3px;left:40.9364%;width:61px;">
      <p class="g-pstyle1">Miguel Crispi,</p>
    </div>
    <div id="g-ai1-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.6743%;margin-top:-4.3px;left:44.5898%;width:48px;">
      <p class="g-pstyle1">diputado</p>
    </div>
    <div id="g-ai1-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:20.1651%;margin-top:-4.3px;left:1.5365%;width:67px;">
      <p class="g-pstyle1">Gonzalo Win<span class="g-cstyle6">t</span>e<span class="g-cstyle12">r</span>,</p>
    </div>
    <div id="g-ai1-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:20.6559%;margin-top:-4.3px;left:45.3635%;width:45px;">
      <p class="g-pstyle1">salien<span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai1-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.024%;margin-top:-4.3px;left:4.2044%;width:48px;">
      <p class="g-pstyle1">diputado</p>
    </div>
    <div id="g-ai1-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.6375%;margin-top:-4.3px;left:91.7329%;width:37px;">
      <p class="g-pstyle1"><span class="g-cstyle13">L</span>ucía</p>
    </div>
    <div id="g-ai1-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.9017%;margin-top:-4.5px;left:54.49%;width:49px;">
      <p class="g-pstyle2">&iquest;A QUIÉN</p>
    </div>
    <div id="g-ai1-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:22.0056%;margin-top:-4.3px;left:2.6628%;width:59px;">
      <p class="g-pstyle1">reelec<span class="g-cstyle6">t</span>o (CS)</p>
    </div>
    <div id="g-ai1-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:22.4964%;margin-top:-4.3px;left:89.8573%;width:52px;">
      <p class="g-pstyle1">Damme<span class="g-cstyle14">r</span>t,</p>
    </div>
    <div id="g-ai1-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:22.8645%;margin-top:-4.3px;left:53.9657%;width:53px;">
      <p class="g-pstyle2">ESCUCHA?</p>
    </div>
    <div id="g-ai1-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:23.3553%;margin-top:-4.3px;left:90.1161%;width:49px;">
      <p class="g-pstyle1">socióloga</p>
    </div>
    <div id="g-ai1-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:23.8461%;margin-top:-4.3px;left:30.0345%;width:86px;">
      <p class="g-pstyle1">J<span class="g-cstyle15">a</span>viera &ldquo;<span class="g-cstyle5">P</span>elo&rdquo; Cabello,</p>
    </div>
    <div id="g-ai1-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:24.4783%;margin-top:-4.5px;left:19.0988%;width:47px;">
      <p class="g-pstyle2">CÍ<span class="g-cstyle0">R</span>CU<span class="g-cstyle1">L</span>O</p>
    </div>
    <div id="g-ai1-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:24.705%;margin-top:-4.3px;left:29.943%;width:71px;">
      <p class="g-pstyle1">je<span class="g-cstyle2">f</span>a de ca<span class="g-cstyle16">m</span>paña</p>
    </div>
    <div id="g-ai1-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.3185%;margin-top:-4.3px;left:18.138%;width:54px;">
      <p class="g-pstyle2">DE HIER<span class="g-cstyle16">R</span>O</p>
    </div>
    <div id="g-ai1-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.1774%;margin-top:-4.3px;left:77.9102%;width:97px;">
      <p class="g-pstyle1">Matías Meza-Lopehendía, </p>
    </div>
    <div id="g-ai1-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:27.0363%;margin-top:-4.3px;left:77.9102%;width:88px;">
      <p class="g-pstyle1">académico <span class="g-cstyle17">U</span>. Católica </p>
    </div>
    <div id="g-ai1-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:27.8952%;margin-top:-4.3px;left:77.9102%;width:61px;">
      <p class="g-pstyle1">de <span class="g-cstyle18">V</span>alparaíso</p>
    </div>
    <div id="g-ai1-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.6314%;margin-top:-4.3px;left:1.8305%;width:86px;">
      <p class="g-pstyle1">Constanza Schonhaut,</p>
    </div>
    <div id="g-ai1-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.4903%;margin-top:-4.3px;left:1.8305%;width:75px;">
      <p class="g-pstyle1">constitu<span class="g-cstyle5">y</span>en<span class="g-cstyle6">t</span>e (RD)</p>
    </div>
    <div id="g-ai1-45" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:31.2081%;margin-top:-4.3px;left:67.4447%;width:72px;">
      <p class="g-pstyle1">An<span class="g-cstyle5">t</span>onia Orellana,</p>
    </div>
    <div id="g-ai1-46" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:32.067%;margin-top:-4.3px;left:52.5971%;width:63px;">
      <p class="g-pstyle1">Diego <span class="g-cstyle10">P</span>a<span class="g-cstyle19">r</span>d<span class="g-cstyle13">o</span><span class="g-cstyle20">w</span>,</p>
    </div>
    <div id="g-ai1-47" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:32.1897%;margin-top:-4.3px;left:67.4447%;width:51px;">
      <p class="g-pstyle1">periodista</p>
    </div>
    <div id="g-ai1-48" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:32.9259%;margin-top:-4.3px;left:54.7645%;width:47px;">
      <p class="g-pstyle1">abogado</p>
    </div>
    <div id="g-ai1-49" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.5394%;margin-top:-4.3px;left:83.3843%;width:71px;">
      <p class="g-pstyle1">J<span class="g-cstyle15">a</span>viera Ma<span class="g-cstyle14">r</span>tínez,</p>
    </div>
    <div id="g-ai1-50" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.3982%;margin-top:-4.3px;left:81.582%;width:78px;">
      <p class="g-pstyle1">ingeniera industrial</p>
    </div>
    <div id="g-ai1-51" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.5209%;margin-top:-4.3px;left:63.6678%;width:76px;">
      <p class="g-pstyle1">Claudia Sanhueza,</p>
    </div>
    <div id="g-ai1-52" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.0117%;margin-top:-4.3px;left:41.4551%;width:65px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>ablo <span class="g-cstyle10">P</span>aredes,</p>
    </div>
    <div id="g-ai1-53" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.3798%;margin-top:-4.3px;left:66.4404%;width:56px;">
      <p class="g-pstyle1">economista</p>
    </div>
    <div id="g-ai1-54" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8706%;margin-top:-4.3px;left:40.5431%;width:69px;">
      <p class="g-pstyle1">direc<span class="g-cstyle19">t</span>or creati<span class="g-cstyle19">v</span>o</p>
    </div>
    <div id="g-ai1-55" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:41.5148%;margin-top:-4.3px;left:85.3535%;width:61px;">
      <p class="g-pstyle1">Lorena <span class="g-cstyle20">F</span>ries, </p>
    </div>
    <div id="g-ai1-56" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.4964%;margin-top:-4.3px;left:85.3535%;width:67px;">
      <p class="g-pstyle1">diputada electa</p>
    </div>
    <div id="g-ai1-57" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:45.1958%;margin-top:-4.3px;left:48.2742%;width:44px;">
      <p class="g-pstyle2">EQUIPO</p>
    </div>
    <div id="g-ai1-58" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.4228%;margin-top:-4.3px;left:70.2007%;width:79px;">
      <p class="g-pstyle1">Mai<span class="g-cstyle19">t</span>e Gamba<span class="g-cstyle19">r</span>della,</p>
    </div>
    <div id="g-ai1-59" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.0363%;margin-top:-4.3px;left:1.7632%;width:69px;">
      <p class="g-pstyle1">Andrea <span class="g-cstyle1">R</span>ep<span class="g-cstyle10">e</span>t<span class="g-cstyle5">t</span>o,</p>
    </div>
    <div id="g-ai1-60" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.4044%;margin-top:-4.3px;left:78.8637%;width:47px;">
      <p class="g-pstyle1">abogada</p>
    </div>
    <div id="g-ai1-61" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.8952%;margin-top:-4.3px;left:5.2669%;width:56px;">
      <p class="g-pstyle1">economista</p>
    </div>
    <div id="g-ai1-62" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:48.6314%;margin-top:-4.3px;left:47.1918%;width:64px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>ablo Zamora,</p>
    </div>
    <div id="g-ai1-63" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:48.8768%;margin-top:-4.3px;left:18.3287%;width:66px;">
      <p class="g-pstyle1">Carlos Gaja<span class="g-cstyle6">r</span>do,</p>
    </div>
    <div id="g-ai1-64" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.4903%;margin-top:-4.3px;left:49.6029%;width:55px;">
      <p class="g-pstyle1">cofundador</p>
    </div>
    <div id="g-ai1-65" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.7357%;margin-top:-4.3px;left:18.3287%;width:44px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>x<span class="g-cstyle21">f</span>iscal</p>
    </div>
    <div id="g-ai1-66" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:50.4719%;margin-top:-4.3px;left:51.1542%;width:49px;">
      <p class="g-pstyle1">de N<span class="g-cstyle22">o</span>tCO</p>
    </div>
    <div id="g-ai1-67" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:50.84%;margin-top:-4.3px;left:82.1837%;width:71px;">
      <p class="g-pstyle1">Ma<span class="g-cstyle5">r</span>cela Serrano,</p>
    </div>
    <div id="g-ai1-68" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:51.6989%;margin-top:-4.3px;left:82.1837%;width:47px;">
      <p class="g-pstyle1">escri<span class="g-cstyle5">t</span>ora</p>
    </div>
    <div id="g-ai1-69" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:54.889%;margin-top:-4.3px;left:52.7501%;width:55px;">
      <p class="g-pstyle2">MEN<span class="g-cstyle23">T</span>ORES</p>
    </div>
    <div id="g-ai1-70" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:58.2019%;margin-top:-4.3px;left:86.8001%;width:56px;">
      <p class="g-pstyle1">Carlos <span class="g-cstyle4">R</span>uiz,</p>
    </div>
    <div id="g-ai1-71" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:59.0608%;margin-top:-4.3px;left:87.7181%;width:49px;">
      <p class="g-pstyle1">sociólogo</p>
    </div>
    <div id="g-ai1-72" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:59.4289%;margin-top:-4.3px;left:5.3901%;width:49px;">
      <p class="g-pstyle2">FICHAJES</p>
    </div>
    <div id="g-ai1-73" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:59.6743%;margin-top:-4.3px;left:19.4846%;width:90px;">
      <p class="g-pstyle1">S<span class="g-cstyle19">t</span>epha<span class="g-cstyle4">n</span>y Gri<span class="g-cstyle24">f</span><span class="g-cstyle21">f</span>ith-Jones,</p>
    </div>
    <div id="g-ai1-74" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:60.5332%;margin-top:-4.3px;left:24.2567%;width:56px;">
      <p class="g-pstyle1">economista</p>
    </div>
    <div id="g-ai1-75" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:61.3921%;margin-top:-4.3px;left:80.9077%;width:68px;">
      <p class="g-pstyle1"><span class="g-cstyle4">F</span>ernando <span class="g-cstyle6">A</span>tria, </p>
    </div>
    <div id="g-ai1-76" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.251%;margin-top:-4.3px;left:80.9077%;width:61px;">
      <p class="g-pstyle1">constitu<span class="g-cstyle5">y</span>en<span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai1-77" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.3369%;margin-top:-4.3px;left:35.67%;width:45px;">
      <p class="g-pstyle1">Ma<span class="g-cstyle5">r</span>celo</p>
    </div>
    <div id="g-ai1-78" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.5823%;margin-top:-4.3px;left:54.1035%;width:54px;">
      <p class="g-pstyle1"><span class="g-cstyle13">L</span>uis Maira,</p>
    </div>
    <div id="g-ai1-79" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:65.3185%;margin-top:-4.3px;left:35.67%;width:41px;">
      <p class="g-pstyle1">Lagos,</p>
    </div>
    <div id="g-ai1-80" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:65.5639%;margin-top:-4.3px;left:53.1516%;width:63px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>xminist<span class="g-cstyle6">r</span>o de </p>
    </div>
    <div id="g-ai1-81" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.1774%;margin-top:-4.3px;left:35.67%;width:48px;">
      <p class="g-pstyle1">geógra<span class="g-cstyle25">f</span>o</p>
    </div>
    <div id="g-ai1-82" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.4228%;margin-top:-4.3px;left:52.7884%;width:66px;">
      <p class="g-pstyle1">Plani<span class="g-cstyle26">f</span>icación y </p>
    </div>
    <div id="g-ai1-83" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.2817%;margin-top:-4.3px;left:53.4926%;width:58px;">
      <p class="g-pstyle1">Cooperación</p>
    </div>
    <div id="g-ai1-84" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:68.2633%;margin-top:-4.3px;left:68.3252%;width:67px;">
      <p class="g-pstyle1">Manuel An<span class="g-cstyle19">t</span>onio</p>
    </div>
    <div id="g-ai1-85" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.1222%;margin-top:-4.3px;left:70.7926%;width:49px;">
      <p class="g-pstyle1">Garr<span class="g-cstyle10">e</span>tón,</p>
    </div>
    <div id="g-ai1-86" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4903%;margin-top:-4.3px;left:37.9427%;width:65px;">
      <p class="g-pstyle1">Edua<span class="g-cstyle6">r</span>do Engel,</p>
    </div>
    <div id="g-ai1-87" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.9811%;margin-top:-4.3px;left:70.8038%;width:49px;">
      <p class="g-pstyle1">sociólogo</p>
    </div>
    <div id="g-ai1-88" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.3492%;margin-top:-4.3px;left:37.9427%;width:59px;">
      <p class="g-pstyle1">fundador de </p>
    </div>
    <div id="g-ai1-89" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:71.3308%;margin-top:-4.3px;left:37.9427%;width:67px;">
      <p class="g-pstyle1">Espacio Público</p>
    </div>
    <div id="g-ai1-90" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:71.5762%;margin-top:-4.3px;left:10.0271%;width:58px;">
      <p class="g-pstyle1">Izkia Siches,</p>
    </div>
    <div id="g-ai1-91" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:72.5578%;margin-top:-4.3px;left:10.0271%;width:70px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>xpresidenta del</p>
    </div>
    <div id="g-ai1-92" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:73.4167%;margin-top:-4.3px;left:10.0271%;width:66px;">
      <p class="g-pstyle1">Colegio Médico</p>
    </div>
    <div id="g-ai1-93" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.0117%;margin-top:-4.3px;left:84.6756%;width:66px;">
      <p class="g-pstyle1">Camila Arenas,</p>
    </div>
    <div id="g-ai1-94" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.8706%;margin-top:-4.3px;left:84.6756%;width:49px;">
      <p class="g-pstyle1">p<span class="g-cstyle6">r</span>o<span class="g-cstyle9">f</span>esora</p>
    </div>
    <div id="g-ai1-95" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.9933%;margin-top:-4.3px;left:53.1565%;width:52px;">
      <p class="g-pstyle2"><span class="g-cstyle27">P</span>ARTIDOS</p>
    </div>
    <div id="g-ai1-96" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:78.4473%;margin-top:-4.3px;left:70.7533%;width:45px;">
      <p class="g-pstyle2">FRENTE</p>
    </div>
    <div id="g-ai1-97" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.1835%;margin-top:-4.3px;left:23.7321%;width:74px;">
      <p class="g-pstyle1">Guillermo Larraín,</p>
    </div>
    <div id="g-ai1-98" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3062%;margin-top:-4.3px;left:70.7026%;width:45px;">
      <p class="g-pstyle2">AMPLIO</p>
    </div>
    <div id="g-ai1-99" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.0424%;margin-top:-4.3px;left:23.7321%;width:69px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>xpresiden<span class="g-cstyle1">t</span>e del</p>
    </div>
    <div id="g-ai1-100" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.1651%;margin-top:-4.3px;left:2.2504%;width:65px;">
      <p class="g-pstyle1">Ma<span class="g-cstyle5">r</span>celo Mena,</p>
    </div>
    <div id="g-ai1-101" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.024%;margin-top:-4.3px;left:23.7321%;width:61px;">
      <p class="g-pstyle1">Banco Estado</p>
    </div>
    <div id="g-ai1-102" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.1467%;margin-top:-4.3px;left:2.2504%;width:63px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span>xminist<span class="g-cstyle6">r</span>o del</p>
    </div>
    <div id="g-ai1-103" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:82.0056%;margin-top:-4.3px;left:2.2504%;width:69px;">
      <p class="g-pstyle1">Medio Ambien<span class="g-cstyle1">t</span>e</p>
    </div>
    <div id="g-ai1-104" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:82.9872%;margin-top:-4.3px;left:82.9218%;width:75px;">
      <p class="g-pstyle1">Sebastián Depolo,</p>
    </div>
    <div id="g-ai1-105" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:83.1099%;margin-top:-4.3px;left:56.4252%;width:48px;">
      <p class="g-pstyle2"><span class="g-cstyle27">P</span>ARTIDO</p>
    </div>
    <div id="g-ai1-106" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:83.6007%;margin-top:-4.3px;left:37.3969%;width:41px;">
      <p class="g-pstyle2">NUE<span class="g-cstyle20">V</span>A</p>
    </div>
    <div id="g-ai1-107" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:83.9688%;margin-top:-4.3px;left:86.4252%;width:49px;">
      <p class="g-pstyle1">sociólogo</p>
    </div>
    <div id="g-ai1-108" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:83.9688%;margin-top:-4.3px;left:55.2148%;width:57px;">
      <p class="g-pstyle2">COMUNIS<span class="g-cstyle28">T</span>A</p>
    </div>
    <div id="g-ai1-109" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.3556%;margin-top:-4.5px;left:36.3458%;width:49px;">
      <p class="g-pstyle2">M<span class="g-cstyle29">A</span><span class="g-cstyle30">Y</span>ORÍA</p>
    </div>
    <div id="g-ai1-110" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:86.4228%;margin-top:-4.3px;left:82.1872%;width:71px;">
      <p class="g-pstyle1">Beatriz Sánchez, </p>
    </div>
    <div id="g-ai1-111" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:86.9136%;margin-top:-4.3px;left:1.9434%;width:71px;">
      <p class="g-pstyle1">M<span class="g-cstyle31">a</span><span class="g-cstyle8">y</span>a <span class="g-cstyle4">F</span>ernández,</p>
    </div>
    <div id="g-ai1-112" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.2817%;margin-top:-4.3px;left:82.1872%;width:61px;">
      <p class="g-pstyle1">constitu<span class="g-cstyle5">y</span>en<span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai1-113" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.7725%;margin-top:-4.3px;left:1.6884%;width:72px;">
      <p class="g-pstyle1">diputada salien<span class="g-cstyle1">t</span>e</p>
    </div>
    <div id="g-ai1-114" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:88.7541%;margin-top:-4.3px;left:12.1948%;width:34px;">
      <p class="g-pstyle1">(PS)</p>
    </div>
    <div id="g-ai1-115" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.5394%;margin-top:-4.3px;left:38.1809%;width:66px;">
      <p class="g-pstyle1">Carlos Mon<span class="g-cstyle1">t</span>es, </p>
    </div>
    <div id="g-ai1-116" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:94.3982%;margin-top:-4.3px;left:37.5043%;width:71px;">
      <p class="g-pstyle1">senador salien<span class="g-cstyle7">t</span>e </p>
    </div>
    <div id="g-ai1-117" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.3798%;margin-top:-4.3px;left:42.4731%;width:34px;">
      <p class="g-pstyle1">(PS)</p>
    </div>
    <div id="g-ai1-118" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.6252%;margin-top:-4.3px;left:54.5275%;width:61px;">
      <p class="g-pstyle1">Irací Hassle<span class="g-cstyle32">r</span>, </p>
    </div>
    <div id="g-ai1-119" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.2387%;margin-top:-4.3px;left:4.3544%;width:65px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>aula Na<span class="g-cstyle24">r</span>váez,</p>
    </div>
    <div id="g-ai1-120" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.6068%;margin-top:-4.3px;left:54.6058%;width:60px;">
      <p class="g-pstyle1">alcaldesa de </p>
    </div>
    <div id="g-ai1-121" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.0976%;margin-top:-4.3px;left:70.8884%;width:81px;">
      <p class="g-pstyle1"><span class="g-cstyle4">F</span>ernando Carmona, </p>
    </div>
    <div id="g-ai1-122" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.2203%;margin-top:-4.3px;left:6.6534%;width:57px;">
      <p class="g-pstyle1"><span class="g-cstyle6">e</span><span class="g-cstyle5">x</span>candidata</p>
    </div>
    <div id="g-ai1-123" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.2203%;margin-top:-4.3px;left:22.5911%;width:59px;">
      <p class="g-pstyle1">Víc<span class="g-cstyle5">t</span>or <span class="g-cstyle33">T</span>orres,</p>
    </div>
    <div id="g-ai1-124" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.4657%;margin-top:-4.3px;left:56.1306%;width:48px;">
      <p class="g-pstyle1">Santiago</p>
    </div>
    <div id="g-ai1-125" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.0792%;margin-top:-4.3px;left:70.8884%;width:56px;">
      <p class="g-pstyle1">economista</p>
    </div>
    <div id="g-ai1-126" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.0792%;margin-top:-4.3px;left:2.9476%;width:71px;">
      <p class="g-pstyle1">presidencial (PS)</p>
    </div>
    <div id="g-ai1-127" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.0792%;margin-top:-4.3px;left:22.5911%;width:86px;">
      <p class="g-pstyle1">diputado salien<span class="g-cstyle7">t</span>e (DC)</p>
    </div>
    <div id="g-ai1-128" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:99.0608%;margin-top:-4.3px;left:22.5911%;width:24px;">
      <p class="g-pstyle1"> </p>
    </div>
  </div>


</div>
`

const containerId = 'g-CirculoPolitico-box'
const namespace = 'g-'
const name = 'CirculoPolitico'

export default makeAi2React({ html, styles, containerId, namespace, name })

/* End ai2react - 2021-12-20 21:32 */
