/* Generated by ai2react v0.102.0 - 2021-12-20 02:38 */
/* ai file: pag-ficha-personal.ai */

import { makeAi2React } from './src'

const styles = `
  #g-pag-ficha-personal-box ,
  #g-pag-ficha-personal-box .g-artboard {
    margin:0 auto;
  }
  #g-pag-ficha-personal-box p {
    margin:0;
  }
  #g-pag-ficha-personal-box .g-aiAbs {
    position:absolute;
  }
  #g-pag-ficha-personal-box .g-aiImg {
    position:absolute;
    top:0;
    display:block;
    width:100% !important;
  }
  #g-pag-ficha-personal-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-pag-ficha-personal-box .g-aiPointText p { white-space: nowrap; }
  #g-pag-ficha-personal-large {
    position:relative;
    overflow:hidden;
  }
  #g-pag-ficha-personal-large p {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:30px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:25px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-pag-ficha-personal-large .g-pstyle0 {
    line-height:38px;
    height:38px;
    font-size:32px;
  }
  #g-pag-ficha-personal-large .g-pstyle1 {
    height:30px;
  }
  #g-pag-ficha-personal-large .g-pstyle2 {
    line-height:29px;
    height:29px;
    font-size:24px;
  }
  #g-pag-ficha-personal-large .g-pstyle3 {
    line-height:32px;
    height:32px;
    font-size:26px;
  }
  #g-pag-ficha-personal-large .g-cstyle0 {
    letter-spacing:-0.001em;
  }
  #g-pag-ficha-personal-large .g-cstyle1 {
    letter-spacing:-0.002em;
  }
  #g-pag-ficha-personal-small {
    position:relative;
    overflow:hidden;
  }
  #g-pag-ficha-personal-small p {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:23px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:19px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-pag-ficha-personal-small .g-pstyle0 {
    height:23px;
  }
  #g-pag-ficha-personal-small .g-pstyle1 {
    line-height:22px;
    height:22px;
    font-size:18px;
  }
  #g-pag-ficha-personal-small .g-pstyle2 {
    line-height:24px;
    height:24px;
    font-size:20px;
  }
  #g-pag-ficha-personal-small .g-cstyle0 {
    letter-spacing:-0.001em;
  }
  #g-pag-ficha-personal-small .g-cstyle1 {
    letter-spacing:-0.002em;
  }

`

const html = props => `
<div id="g-pag-ficha-personal-box" class="ai2html">


  <!-- Artboard: large -->
  <div id="g-pag-ficha-personal-large" class="g-artboard" style="width:1280px; height:1113.82995605469px;" data-aspect-ratio="1.149" data-min-width="1280">
<div style=""></div>
    <img id="g-pag-ficha-personal-large-img" class="g-aiImg" alt="" src="https://especiales.latercera.com/boric-presidente-assets/pag-ficha-personal-large.jpg"/>
    <div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:6.1272%;margin-top:-21.2px;left:29.1846%;width:265px;">
      <p class="g-pstyle0">FICHA PERSONAL</p>
    </div>
    <div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.1384%;margin-top:-16.8px;left:39.0148%;width:217px;">
      <p class="g-pstyle1">NOMBRE CO<span class="g-cstyle0">M</span>PLE</p>
    </div>
    <div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.1384%;margin-top:-16.8px;left:54.2272%;width:34px;">
      <p class="g-pstyle1">T</p>
    </div>
    <div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.1384%;margin-top:-16.8px;left:55.1398%;width:38px;">
      <p class="g-pstyle1">O</p>
    </div>
    <div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.1384%;margin-top:-16.8px;left:74.4944%;width:152px;">
      <p class="g-pstyle1">FECHA DE N</p>
    </div>
    <div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.1384%;margin-top:-16.8px;left:84.669%;width:37px;">
      <p class="g-pstyle1">A</p>
    </div>
    <div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.1384%;margin-top:-16.8px;left:85.801%;width:99px;">
      <p class="g-pstyle1">CIMIEN</p>
    </div>
    <div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.1384%;margin-top:-16.8px;left:91.8551%;width:34px;">
      <p class="g-pstyle1">T</p>
    </div>
    <div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.1384%;margin-top:-16.8px;left:92.7698%;width:38px;">
      <p class="g-pstyle1">O</p>
    </div>
    <div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:39.0148%;width:160px;">
      <p class="g-pstyle2">Gabriel Boric </p>
    </div>
    <div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:49.7867%;width:34px;">
      <p class="g-pstyle2">F</p>
    </div>
    <div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:50.7035%;width:55px;">
      <p class="g-pstyle2">ont</p>
    </div>
    <div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:74.4944%;width:36px;">
      <p class="g-pstyle2">1</p>
    </div>
    <div id="g-ai0-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:75.5594%;width:74px;">
      <p class="g-pstyle2">1 de </p>
    </div>
    <div id="g-ai0-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:79.5888%;width:30px;">
      <p class="g-pstyle2">f</p>
    </div>
    <div id="g-ai0-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:80.1344%;width:68px;">
      <p class="g-pstyle2">ebre</p>
    </div>
    <div id="g-ai0-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:83.7325%;width:30px;">
      <p class="g-pstyle2">r</p>
    </div>
    <div id="g-ai0-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:84.3175%;width:72px;">
      <p class="g-pstyle2">o de </p>
    </div>
    <div id="g-ai0-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:88.24%;width:36px;">
      <p class="g-pstyle2">1</p>
    </div>
    <div id="g-ai0-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.05%;margin-top:-16.2px;left:89.3125%;width:64px;">
      <p class="g-pstyle2">986</p>
    </div>
    <div id="g-ai0-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.0014%;margin-top:-18.6px;left:80.5735%;width:78px;">
      <p class="g-pstyle3">CIÓN</p>
    </div>
    <div id="g-ai0-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.0376%;margin-top:-18px;left:74.4944%;width:70px;">
      <p class="g-pstyle3">OCU</p>
    </div>
    <div id="g-ai0-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.0376%;margin-top:-18px;left:78.2334%;width:38px;">
      <p class="g-pstyle3">P</p>
    </div>
    <div id="g-ai0-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.0376%;margin-top:-18px;left:79.3782%;width:38px;">
      <p class="g-pstyle3">A</p>
    </div>
    <div id="g-ai0-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.0143%;margin-top:-16.8px;left:39.0148%;width:35px;">
      <p class="g-pstyle1">E</p>
    </div>
    <div id="g-ai0-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.0143%;margin-top:-16.8px;left:40.0636%;width:38px;">
      <p class="g-pstyle1">D</p>
    </div>
    <div id="g-ai0-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.0143%;margin-top:-16.8px;left:41.2921%;width:53px;">
      <p class="g-pstyle1">AD</p>
    </div>
    <div id="g-ai0-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.9913%;margin-top:-16.9px;left:74.4944%;width:121px;">
      <p class="g-pstyle1">Diputado</p>
    </div>
    <div id="g-ai0-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.9258%;margin-top:-16.2px;left:39.0148%;width:106px;">
      <p class="g-pstyle2">35 años</p>
    </div>
    <div id="g-ai0-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.723%;margin-top:-16.8px;left:74.4944%;width:149px;">
      <p class="g-pstyle1">HERMANOS</p>
    </div>
    <div id="g-ai0-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.723%;margin-top:-16.8px;left:39.0148%;width:37px;">
      <p class="g-pstyle1">P</p>
    </div>
    <div id="g-ai0-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.723%;margin-top:-16.8px;left:40.1007%;width:97px;">
      <p class="g-pstyle1">ADRES</p>
    </div>
    <div id="g-ai0-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.6345%;margin-top:-16.2px;left:74.4944%;width:152px;">
      <p class="g-pstyle2">Simón Boric </p>
    </div>
    <div id="g-ai0-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.6345%;margin-top:-16.2px;left:84.6851%;width:34px;">
      <p class="g-pstyle2">F</p>
    </div>
    <div id="g-ai0-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.6345%;margin-top:-16.2px;left:85.6038%;width:55px;">
      <p class="g-pstyle2">ont</p>
    </div>
    <div id="g-ai0-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.6345%;margin-top:-16.2px;left:39.0148%;width:34px;">
      <p class="g-pstyle2">L</p>
    </div>
    <div id="g-ai0-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.6345%;margin-top:-16.2px;left:39.926%;width:154px;">
      <p class="g-pstyle2">uis Boric Sca</p>
    </div>
    <div id="g-ai0-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.6345%;margin-top:-16.2px;left:50.2273%;width:30px;">
      <p class="g-pstyle2">r</p>
    </div>
    <div id="g-ai0-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.6345%;margin-top:-16.2px;left:50.8404%;width:54px;">
      <p class="g-pstyle2">pa </p>
    </div>
    <div id="g-ai0-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.5075%;margin-top:-16.2px;left:74.4963%;width:125px;">
      <p class="g-pstyle2">(33 años, </p>
    </div>
    <div id="g-ai0-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.5075%;margin-top:-16.2px;left:82.5062%;width:36px;">
      <p class="g-pstyle2">P</p>
    </div>
    <div id="g-ai0-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.5075%;margin-top:-16.2px;left:83.6031%;width:119px;">
      <p class="g-pstyle2">eriodista)</p>
    </div>
    <div id="g-ai0-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.5075%;margin-top:-16.2px;left:39.0166%;width:200px;">
      <p class="g-pstyle2">(75 años, Ingenie</p>
    </div>
    <div id="g-ai0-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.5075%;margin-top:-16.2px;left:52.9545%;width:30px;">
      <p class="g-pstyle2">r</p>
    </div>
    <div id="g-ai0-45" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.5075%;margin-top:-16.2px;left:53.5442%;width:133px;">
      <p class="g-pstyle2">o Químico)</p>
    </div>
    <div id="g-ai0-46" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.4578%;margin-top:-16.2px;left:39.0148%;width:177px;">
      <p class="g-pstyle2">María Soleda<span class="g-cstyle1">d</span> </p>
    </div>
    <div id="g-ai0-47" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.4578%;margin-top:-16.2px;left:51.0988%;width:34px;">
      <p class="g-pstyle2">F</p>
    </div>
    <div id="g-ai0-48" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.4578%;margin-top:-16.2px;left:52.0122%;width:61px;">
      <p class="g-pstyle2">ont </p>
    </div>
    <div id="g-ai0-49" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.4578%;margin-top:-16.2px;left:55.0929%;width:36px;">
      <p class="g-pstyle2">A</p>
    </div>
    <div id="g-ai0-50" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.4578%;margin-top:-16.2px;left:56.2423%;width:99px;">
      <p class="g-pstyle2">guilera </p>
    </div>
    <div id="g-ai0-51" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.4578%;margin-top:-16.2px;left:74.4954%;width:34px;">
      <p class="g-pstyle2">T</p>
    </div>
    <div id="g-ai0-52" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.4578%;margin-top:-16.2px;left:75.2829%;width:144px;">
      <p class="g-pstyle2">omás Boric </p>
    </div>
    <div id="g-ai0-53" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.4578%;margin-top:-16.2px;left:84.7929%;width:34px;">
      <p class="g-pstyle2">F</p>
    </div>
    <div id="g-ai0-54" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.4578%;margin-top:-16.2px;left:85.7079%;width:55px;">
      <p class="g-pstyle2">ont</p>
    </div>
    <div id="g-ai0-55" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.3308%;margin-top:-16.2px;left:39.0166%;width:29px;">
      <p class="g-pstyle2">(</p>
    </div>
    <div id="g-ai0-56" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.3308%;margin-top:-16.2px;left:39.566%;width:36px;">
      <p class="g-pstyle2">6</p>
    </div>
    <div id="g-ai0-57" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.3308%;margin-top:-16.2px;left:40.5954%;width:99px;">
      <p class="g-pstyle2">1 años)</p>
    </div>
    <div id="g-ai0-58" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.3308%;margin-top:-16.2px;left:74.4954%;width:120px;">
      <p class="g-pstyle2">(29 años)</p>
    </div>
    <div id="g-ai0-59" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.5228%;margin-top:-18px;left:39.0148%;width:38px;">
      <p class="g-pstyle3">P</p>
    </div>
    <div id="g-ai0-60" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.5228%;margin-top:-18px;left:40.1586%;width:69px;">
      <p class="g-pstyle3">ARE</p>
    </div>
    <div id="g-ai0-61" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.5228%;margin-top:-18px;left:43.8267%;width:32px;">
      <p class="g-pstyle3">J</p>
    </div>
    <div id="g-ai0-62" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.5228%;margin-top:-18px;left:44.557%;width:38px;">
      <p class="g-pstyle3">A</p>
    </div>
    <div id="g-ai0-63" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.9717%;margin-top:-18px;left:74.4938%;width:35px;">
      <p class="g-pstyle3">L</p>
    </div>
    <div id="g-ai0-64" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.9717%;margin-top:-18px;left:75.4977%;width:38px;">
      <p class="g-pstyle3">U</p>
    </div>
    <div id="g-ai0-65" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.9717%;margin-top:-18px;left:76.7217%;width:39px;">
      <p class="g-pstyle3">G</p>
    </div>
    <div id="g-ai0-66" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.9717%;margin-top:-18px;left:78.0507%;width:116px;">
      <p class="g-pstyle3">AR DE N</p>
    </div>
    <div id="g-ai0-67" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.9717%;margin-top:-18px;left:85.432%;width:38px;">
      <p class="g-pstyle3">A</p>
    </div>
    <div id="g-ai0-68" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.9717%;margin-top:-18px;left:86.6272%;width:104px;">
      <p class="g-pstyle3">CIMIEN</p>
    </div>
    <div id="g-ai0-69" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.9717%;margin-top:-18px;left:93.0066%;width:35px;">
      <p class="g-pstyle3">T</p>
    </div>
    <div id="g-ai0-70" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.9717%;margin-top:-18px;left:93.9694%;width:39px;">
      <p class="g-pstyle3">O</p>
    </div>
    <div id="g-ai0-71" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.4765%;margin-top:-16.9px;left:39.0148%;width:77px;">
      <p class="g-pstyle1">Irina </p>
    </div>
    <div id="g-ai0-72" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.4765%;margin-top:-16.9px;left:43.3113%;width:38px;">
      <p class="g-pstyle1">K</p>
    </div>
    <div id="g-ai0-73" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.4765%;margin-top:-16.9px;left:44.511%;width:138px;">
      <p class="g-pstyle1">aramanos </p>
    </div>
    <div id="g-ai0-74" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.4765%;margin-top:-16.9px;left:53.5918%;width:37px;">
      <p class="g-pstyle1">A</p>
    </div>
    <div id="g-ai0-75" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.4765%;margin-top:-16.9px;left:54.7649%;width:78px;">
      <p class="g-pstyle1">drian</p>
    </div>
    <div id="g-ai0-76" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.8356%;margin-top:-16.9px;left:74.4944%;width:168px;">
      <p class="g-pstyle1">Punta Arenas</p>
    </div>
    <div id="g-ai0-77" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:58.3495%;margin-top:-16.9px;left:39.0168%;width:160px;">
      <p class="g-pstyle1">32 años, Ant</p>
    </div>
    <div id="g-ai0-78" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:58.3495%;margin-top:-16.9px;left:49.7703%;width:30px;">
      <p class="g-pstyle1">r</p>
    </div>
    <div id="g-ai0-79" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:58.3495%;margin-top:-16.9px;left:50.3904%;width:109px;">
      <p class="g-pstyle1">opóloga</p>
    </div>
    <div id="g-ai0-80" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.2218%;margin-top:-17.3px;left:41.4683%;width:117px;">
      <p class="g-pstyle1">OFESIÓN</p>
    </div>
    <div id="g-ai0-81" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.1709%;margin-top:-16.8px;left:74.4944%;width:262px;">
      <p class="g-pstyle1">COLEGIO DE EGERESO</p>
    </div>
    <div id="g-ai0-82" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.2607%;margin-top:-16.8px;left:39.0581%;width:37px;">
      <p class="g-pstyle1">P</p>
    </div>
    <div id="g-ai0-83" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.2607%;margin-top:-16.8px;left:40.2281%;width:38px;">
      <p class="g-pstyle1">R</p>
    </div>
    <div id="g-ai0-84" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.9927%;margin-top:-16.2px;left:74.4944%;width:244px;">
      <p class="g-pstyle2">The British School de </p>
    </div>
    <div id="g-ai0-85" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.0825%;margin-top:-16.2px;left:39.0581%;width:303px;">
      <p class="g-pstyle2">Egresado de <span class="g-cstyle0">D</span>erecho de la </p>
    </div>
    <div id="g-ai0-86" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.8657%;margin-top:-16.2px;left:74.4944%;width:161px;">
      <p class="g-pstyle2">Punta Arenas</p>
    </div>
    <div id="g-ai0-87" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.9554%;margin-top:-16.2px;left:39.0581%;width:36px;">
      <p class="g-pstyle2">U</p>
    </div>
    <div id="g-ai0-88" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.9554%;margin-top:-16.2px;left:40.1663%;width:41px;">
      <p class="g-pstyle2">ni</p>
    </div>
    <div id="g-ai0-89" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.9554%;margin-top:-16.2px;left:41.6401%;width:33px;">
      <p class="g-pstyle2">v</p>
    </div>
    <div id="g-ai0-90" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.9554%;margin-top:-16.2px;left:42.4463%;width:35px;">
      <p class="g-pstyle2">e</p>
    </div>
    <div id="g-ai0-91" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.9554%;margin-top:-16.2px;left:43.4288%;width:30px;">
      <p class="g-pstyle2">r</p>
    </div>
    <div id="g-ai0-92" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.9554%;margin-top:-16.2px;left:44.0607%;width:166px;">
      <p class="g-pstyle2">sidad de Chile</p>
    </div>
    <div id="g-ai0-93" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.4167%;margin-top:-18px;left:39.1281%;width:38px;">
      <p class="g-pstyle3">P</p>
    </div>
    <div id="g-ai0-94" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.4167%;margin-top:-18px;left:40.2719%;width:38px;">
      <p class="g-pstyle3">A</p>
    </div>
    <div id="g-ai0-95" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.4167%;margin-top:-18px;left:41.4014%;width:138px;">
      <p class="g-pstyle3">TRIMONIO</p>
    </div>
    <div id="g-ai0-96" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:39.1273%;width:37px;">
      <p class="g-pstyle1">U</p>
    </div>
    <div id="g-ai0-97" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:40.2945%;width:42px;">
      <p class="g-pstyle1">n </p>
    </div>
    <div id="g-ai0-98" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:41.8576%;width:30px;">
      <p class="g-pstyle1">t</p>
    </div>
    <div id="g-ai0-99" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:42.4609%;width:158px;">
      <p class="g-pstyle1">erreno en la </p>
    </div>
    <div id="g-ai0-100" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:60.3815%;width:37px;">
      <p class="g-pstyle1">U</p>
    </div>
    <div id="g-ai0-101" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:61.5486%;width:78px;">
      <p class="g-pstyle1">na m</p>
    </div>
    <div id="g-ai0-102" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:65.8984%;width:35px;">
      <p class="g-pstyle1">o</p>
    </div>
    <div id="g-ai0-103" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:66.9283%;width:30px;">
      <p class="g-pstyle1">t</p>
    </div>
    <div id="g-ai0-104" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:67.5346%;width:42px;">
      <p class="g-pstyle1">o </p>
    </div>
    <div id="g-ai0-105" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:69.0472%;width:36px;">
      <p class="g-pstyle1">Y</p>
    </div>
    <div id="g-ai0-106" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:70.027%;width:105px;">
      <p class="g-pstyle1">amaha </p>
    </div>
    <div id="g-ai0-107" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:80.9563%;width:35px;">
      <p class="g-pstyle1">F</p>
    </div>
    <div id="g-ai0-108" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5281%;margin-top:-16.9px;left:81.922%;width:216px;">
      <p class="g-pstyle1">ondos mutuos en </p>
    </div>
    <div id="g-ai0-109" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.4011%;margin-top:-16.9px;left:39.1292%;width:258px;">
      <p class="g-pstyle1">comuna de Dalcahue </p>
    </div>
    <div id="g-ai0-110" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.4011%;margin-top:-16.9px;left:60.3815%;width:101px;">
      <p class="g-pstyle1">con un </p>
    </div>
    <div id="g-ai0-111" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.4011%;margin-top:-16.9px;left:66.5393%;width:36px;">
      <p class="g-pstyle1">a</p>
    </div>
    <div id="g-ai0-112" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.4011%;margin-top:-16.9px;left:67.5623%;width:33px;">
      <p class="g-pstyle1">v</p>
    </div>
    <div id="g-ai0-113" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.4011%;margin-top:-16.9px;left:68.4214%;width:75px;">
      <p class="g-pstyle1">alúo </p>
    </div>
    <div id="g-ai0-114" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.4011%;margin-top:-16.9px;left:72.5767%;width:30px;">
      <p class="g-pstyle1">f</p>
    </div>
    <div id="g-ai0-115" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.4011%;margin-top:-16.9px;left:73.2086%;width:78px;">
      <p class="g-pstyle1">iscal </p>
    </div>
    <div id="g-ai0-116" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.4011%;margin-top:-16.9px;left:80.9563%;width:241px;">
      <p class="g-pstyle1">el Banco Santander </p>
    </div>
    <div id="g-ai0-117" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:39.1292%;width:101px;">
      <p class="g-pstyle1">con un </p>
    </div>
    <div id="g-ai0-118" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:45.2871%;width:36px;">
      <p class="g-pstyle1">a</p>
    </div>
    <div id="g-ai0-119" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:46.3101%;width:33px;">
      <p class="g-pstyle1">v</p>
    </div>
    <div id="g-ai0-120" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:47.1692%;width:75px;">
      <p class="g-pstyle1">alúo </p>
    </div>
    <div id="g-ai0-121" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:51.3254%;width:30px;">
      <p class="g-pstyle1">f</p>
    </div>
    <div id="g-ai0-122" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:51.9564%;width:78px;">
      <p class="g-pstyle1">iscal </p>
    </div>
    <div id="g-ai0-123" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:60.3815%;width:127px;">
      <p class="g-pstyle1">de $ 702.</p>
    </div>
    <div id="g-ai0-124" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:68.5734%;width:37px;">
      <p class="g-pstyle1">4</p>
    </div>
    <div id="g-ai0-125" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:69.7465%;width:52px;">
      <p class="g-pstyle1">49</p>
    </div>
    <div id="g-ai0-126" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:80.9563%;width:101px;">
      <p class="g-pstyle1">con un </p>
    </div>
    <div id="g-ai0-127" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:87.1142%;width:33px;">
      <p class="g-pstyle1">v</p>
    </div>
    <div id="g-ai0-128" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.274%;margin-top:-16.9px;left:87.9732%;width:103px;">
      <p class="g-pstyle1">alor de </p>
    </div>
    <div id="g-ai0-129" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.147%;margin-top:-16.9px;left:39.1292%;width:106px;">
      <p class="g-pstyle1">de $ 12</p>
    </div>
    <div id="g-ai0-130" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.147%;margin-top:-16.9px;left:45.688%;width:28px;">
      <p class="g-pstyle1">.</p>
    </div>
    <div id="g-ai0-131" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.147%;margin-top:-16.9px;left:46.0889%;width:37px;">
      <p class="g-pstyle1">1</p>
    </div>
    <div id="g-ai0-132" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.147%;margin-top:-16.9px;left:47.2107%;width:37px;">
      <p class="g-pstyle1">1</p>
    </div>
    <div id="g-ai0-133" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.147%;margin-top:-16.9px;left:48.3047%;width:87px;">
      <p class="g-pstyle1">0.823</p>
    </div>
    <div id="g-ai0-134" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.147%;margin-top:-16.9px;left:80.9563%;width:43px;">
      <p class="g-pstyle1">$ </p>
    </div>
    <div id="g-ai0-135" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.147%;margin-top:-16.9px;left:82.6073%;width:37px;">
      <p class="g-pstyle1">3</p>
    </div>
    <div id="g-ai0-136" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.147%;margin-top:-16.9px;left:83.6738%;width:37px;">
      <p class="g-pstyle1">1</p>
    </div>
    <div id="g-ai0-137" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.147%;margin-top:-16.9px;left:84.8193%;width:123px;">
      <p class="g-pstyle1">.223.320</p>
    </div>
  </div>

  <!-- Artboard: small -->
  <div id="g-pag-ficha-personal-small" class="g-artboard" style="max-width: 360px;max-height: 2044px" data-aspect-ratio="0.176" data-min-width="0" data-max-width="1279">
<div style="padding: 0 0 567.7201% 0;"></div>
    <img id="g-pag-ficha-personal-small-img" class="g-aiImg" alt="" src="https://especiales.latercera.com/boric-presidente-assets/pag-ficha-personal-small.jpg"/>
    <div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:1.1717%;margin-top:-12.9px;left:3.1657%;width:168px;">
      <p class="g-pstyle0">FICHA PERSONAL</p>
    </div>
    <div id="g-ai1-2" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:4.2491%;margin-top:-12.8px;left:32.1691%;width:170px;">
      <p class="g-pstyle0">NOMBRE CO<span class="g-cstyle0">M</span>PLE</p>
    </div>
    <div id="g-ai1-3" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:4.2491%;margin-top:-12.8px;left:73.313%;width:31px;">
      <p class="g-pstyle0">T</p>
    </div>
    <div id="g-ai1-4" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:4.2491%;margin-top:-12.8px;left:75.7813%;width:34px;">
      <p class="g-pstyle0">O</p>
    </div>
    <div id="g-ai1-5" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:5.4511%;margin-top:-12.4px;left:32.1691%;width:127px;">
      <p class="g-pstyle1">Gabriel Boric </p>
    </div>
    <div id="g-ai1-6" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:5.4511%;margin-top:-12.4px;left:61.3032%;width:31px;">
      <p class="g-pstyle1">F</p>
    </div>
    <div id="g-ai1-7" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:5.4511%;margin-top:-12.4px;left:63.7828%;width:47px;">
      <p class="g-pstyle1">ont</p>
    </div>
    <div id="g-ai1-8" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:7.9677%;margin-top:-12.8px;left:31.9878%;width:121px;">
      <p class="g-pstyle0">FECHA DE N</p>
    </div>
    <div id="g-ai1-9" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:7.9677%;margin-top:-12.8px;left:59.5063%;width:33px;">
      <p class="g-pstyle0">A</p>
    </div>
    <div id="g-ai1-10" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:7.9677%;margin-top:-12.8px;left:62.5681%;width:81px;">
      <p class="g-pstyle0">CIMIEN</p>
    </div>
    <div id="g-ai1-11" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:7.9677%;margin-top:-12.8px;left:78.9421%;width:31px;">
      <p class="g-pstyle0">T</p>
    </div>
    <div id="g-ai1-12" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:7.9677%;margin-top:-12.8px;left:81.416%;width:34px;">
      <p class="g-pstyle0">O</p>
    </div>
    <div id="g-ai1-13" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:9.1697%;margin-top:-12.4px;left:31.9878%;width:33px;">
      <p class="g-pstyle1">1</p>
    </div>
    <div id="g-ai1-14" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:9.1697%;margin-top:-12.4px;left:34.8682%;width:61px;">
      <p class="g-pstyle1">1 de </p>
    </div>
    <div id="g-ai1-15" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:9.1697%;margin-top:-12.4px;left:45.7661%;width:28px;">
      <p class="g-pstyle1">f</p>
    </div>
    <div id="g-ai1-16" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:9.1697%;margin-top:-12.4px;left:47.242%;width:57px;">
      <p class="g-pstyle1">ebre</p>
    </div>
    <div id="g-ai1-17" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:9.1697%;margin-top:-12.4px;left:56.9737%;width:28px;">
      <p class="g-pstyle1">r</p>
    </div>
    <div id="g-ai1-18" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:9.1697%;margin-top:-12.4px;left:58.5558%;width:60px;">
      <p class="g-pstyle1">o de </p>
    </div>
    <div id="g-ai1-19" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:9.1697%;margin-top:-12.4px;left:69.1648%;width:33px;">
      <p class="g-pstyle1">1</p>
    </div>
    <div id="g-ai1-20" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:9.1697%;margin-top:-12.4px;left:72.0654%;width:54px;">
      <p class="g-pstyle1">986</p>
    </div>
    <div id="g-ai1-21" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:11.5395%;margin-top:-12.8px;left:31.9575%;width:32px;">
      <p class="g-pstyle0">E</p>
    </div>
    <div id="g-ai1-22" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:11.5395%;margin-top:-12.8px;left:34.7938%;width:34px;">
      <p class="g-pstyle0">D</p>
    </div>
    <div id="g-ai1-23" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:11.5395%;margin-top:-12.8px;left:38.1166%;width:46px;">
      <p class="g-pstyle0">AD</p>
    </div>
    <div id="g-ai1-24" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:12.7415%;margin-top:-12.4px;left:31.9575%;width:86px;">
      <p class="g-pstyle1">35 años</p>
    </div>
    <div id="g-ai1-25" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:14.7703%;margin-top:-13.9px;left:47.9698%;width:65px;">
      <p class="g-pstyle2">CIÓN</p>
    </div>
    <div id="g-ai1-26" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:14.7971%;margin-top:-13.4px;left:31.528%;width:58px;">
      <p class="g-pstyle2">OCU</p>
    </div>
    <div id="g-ai1-27" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:14.7971%;margin-top:-13.4px;left:41.6409%;width:34px;">
      <p class="g-pstyle2">P</p>
    </div>
    <div id="g-ai1-28" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:14.7971%;margin-top:-13.4px;left:44.7371%;width:34px;">
      <p class="g-pstyle2">A</p>
    </div>
    <div id="g-ai1-29" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:15.9979%;margin-top:-13px;left:31.528%;width:97px;">
      <p class="g-pstyle0">Diputado</p>
    </div>
    <div id="g-ai1-30" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:17.9491%;margin-top:-12.8px;left:32.1905%;width:33px;">
      <p class="g-pstyle0">P</p>
    </div>
    <div id="g-ai1-31" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:17.9491%;margin-top:-12.8px;left:35.1275%;width:79px;">
      <p class="g-pstyle0">ADRES</p>
    </div>
    <div id="g-ai1-32" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:19.1511%;margin-top:-12.4px;left:32.1905%;width:31px;">
      <p class="g-pstyle1">L</p>
    </div>
    <div id="g-ai1-33" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:19.1511%;margin-top:-12.4px;left:34.6549%;width:122px;">
      <p class="g-pstyle1">uis Boric Sca</p>
    </div>
    <div id="g-ai1-34" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:19.1511%;margin-top:-12.4px;left:62.5163%;width:28px;">
      <p class="g-pstyle1">r</p>
    </div>
    <div id="g-ai1-35" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:19.1511%;margin-top:-12.4px;left:64.1743%;width:46px;">
      <p class="g-pstyle1">pa </p>
    </div>
    <div id="g-ai1-36" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:19.9829%;margin-top:-12.4px;left:32.1956%;width:158px;">
      <p class="g-pstyle1">(75 años, Ingenie</p>
    </div>
    <div id="g-ai1-37" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:19.9829%;margin-top:-12.4px;left:69.892%;width:28px;">
      <p class="g-pstyle1">r</p>
    </div>
    <div id="g-ai1-38" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:19.9829%;margin-top:-12.4px;left:71.4871%;width:106px;">
      <p class="g-pstyle1">o Químico)</p>
    </div>
    <div id="g-ai1-39" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:21.6465%;margin-top:-12.4px;left:32.1905%;width:140px;">
      <p class="g-pstyle1">María Soleda<span class="g-cstyle1">d</span> </p>
    </div>
    <div id="g-ai1-40" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:21.6465%;margin-top:-12.4px;left:64.873%;width:31px;">
      <p class="g-pstyle1">F</p>
    </div>
    <div id="g-ai1-41" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:21.6465%;margin-top:-12.4px;left:67.3438%;width:52px;">
      <p class="g-pstyle1">ont </p>
    </div>
    <div id="g-ai1-42" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:21.6465%;margin-top:-12.4px;left:75.676%;width:33px;">
      <p class="g-pstyle1">A</p>
    </div>
    <div id="g-ai1-43" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:21.6465%;margin-top:-12.4px;left:78.7845%;width:80px;">
      <p class="g-pstyle1">guilera </p>
    </div>
    <div id="g-ai1-44" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:22.5272%;margin-top:-12.4px;left:32.1956%;width:27px;">
      <p class="g-pstyle1">(</p>
    </div>
    <div id="g-ai1-45" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:22.5272%;margin-top:-12.4px;left:33.6814%;width:33px;">
      <p class="g-pstyle1">6</p>
    </div>
    <div id="g-ai1-46" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:22.5272%;margin-top:-12.4px;left:36.4654%;width:80px;">
      <p class="g-pstyle1">1 años)</p>
    </div>
    <div id="g-ai1-47" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:23.8695%;margin-top:-12.8px;left:32.2488%;width:119px;">
      <p class="g-pstyle0">HERMANOS</p>
    </div>
    <div id="g-ai1-48" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:25.0715%;margin-top:-12.4px;left:32.2488%;width:121px;">
      <p class="g-pstyle1">Simón Boric </p>
    </div>
    <div id="g-ai1-49" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:25.0715%;margin-top:-12.4px;left:59.8109%;width:31px;">
      <p class="g-pstyle1">F</p>
    </div>
    <div id="g-ai1-50" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:25.0715%;margin-top:-12.4px;left:62.2957%;width:47px;">
      <p class="g-pstyle1">ont</p>
    </div>
    <div id="g-ai1-51" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:26.2458%;margin-top:-12.4px;left:32.254%;width:100px;">
      <p class="g-pstyle1">(33 años, </p>
    </div>
    <div id="g-ai1-52" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:26.2458%;margin-top:-12.4px;left:53.9179%;width:33px;">
      <p class="g-pstyle1">P</p>
    </div>
    <div id="g-ai1-53" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:26.2458%;margin-top:-12.4px;left:56.8848%;width:95px;">
      <p class="g-pstyle1">eriodista)</p>
    </div>
    <div id="g-ai1-54" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:27.9094%;margin-top:-12.4px;left:32.2515%;width:31px;">
      <p class="g-pstyle1">T</p>
    </div>
    <div id="g-ai1-55" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:27.9094%;margin-top:-12.4px;left:34.3815%;width:115px;">
      <p class="g-pstyle1">omás Boric </p>
    </div>
    <div id="g-ai1-56" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:27.9094%;margin-top:-12.4px;left:60.1025%;width:31px;">
      <p class="g-pstyle1">F</p>
    </div>
    <div id="g-ai1-57" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:27.9094%;margin-top:-12.4px;left:62.5773%;width:47px;">
      <p class="g-pstyle1">ont</p>
    </div>
    <div id="g-ai1-58" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:29.0837%;margin-top:-12.4px;left:32.2515%;width:96px;">
      <p class="g-pstyle1">(29 años)</p>
    </div>
    <div id="g-ai1-59" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:30.5032%;margin-top:-13.4px;left:33.4041%;width:34px;">
      <p class="g-pstyle2">P</p>
    </div>
    <div id="g-ai1-60" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:30.5032%;margin-top:-13.4px;left:36.4979%;width:58px;">
      <p class="g-pstyle2">ARE</p>
    </div>
    <div id="g-ai1-61" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:30.5032%;margin-top:-13.4px;left:46.4185%;width:29px;">
      <p class="g-pstyle2">J</p>
    </div>
    <div id="g-ai1-62" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:30.5032%;margin-top:-13.4px;left:48.3936%;width:34px;">
      <p class="g-pstyle2">A</p>
    </div>
    <div id="g-ai1-63" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:31.704%;margin-top:-13px;left:33.4041%;width:64px;">
      <p class="g-pstyle0">Irina </p>
    </div>
    <div id="g-ai1-64" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:31.704%;margin-top:-13px;left:45.0244%;width:34px;">
      <p class="g-pstyle0">K</p>
    </div>
    <div id="g-ai1-65" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:31.704%;margin-top:-13px;left:48.2693%;width:110px;">
      <p class="g-pstyle0">aramanos </p>
    </div>
    <div id="g-ai1-66" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:31.704%;margin-top:-13px;left:72.8293%;width:34px;">
      <p class="g-pstyle0">A</p>
    </div>
    <div id="g-ai1-67" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:31.704%;margin-top:-13px;left:76.0021%;width:64px;">
      <p class="g-pstyle0">drian</p>
    </div>
    <div id="g-ai1-68" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:32.8783%;margin-top:-13px;left:33.4096%;width:127px;">
      <p class="g-pstyle0">32 años, Ant</p>
    </div>
    <div id="g-ai1-69" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:32.8783%;margin-top:-13px;left:62.4938%;width:28px;">
      <p class="g-pstyle0">r</p>
    </div>
    <div id="g-ai1-70" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:32.8783%;margin-top:-13px;left:64.171%;width:88px;">
      <p class="g-pstyle0">opóloga</p>
    </div>
    <div id="g-ai1-71" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:34.2707%;margin-top:-13.4px;left:32.4202%;width:32px;">
      <p class="g-pstyle2">L</p>
    </div>
    <div id="g-ai1-72" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:34.2707%;margin-top:-13.4px;left:35.1351%;width:34px;">
      <p class="g-pstyle2">U</p>
    </div>
    <div id="g-ai1-73" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:34.2707%;margin-top:-13.4px;left:38.4456%;width:35px;">
      <p class="g-pstyle2">G</p>
    </div>
    <div id="g-ai1-74" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:34.2707%;margin-top:-13.4px;left:42.0402%;width:94px;">
      <p class="g-pstyle2">AR DE N</p>
    </div>
    <div id="g-ai1-75" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:34.2707%;margin-top:-13.4px;left:62.0039%;width:34px;">
      <p class="g-pstyle2">A</p>
    </div>
    <div id="g-ai1-76" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:34.2707%;margin-top:-13.4px;left:65.2365%;width:84px;">
      <p class="g-pstyle2">CIMIEN</p>
    </div>
    <div id="g-ai1-77" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:34.2707%;margin-top:-13.4px;left:82.4902%;width:32px;">
      <p class="g-pstyle2">T</p>
    </div>
    <div id="g-ai1-78" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:34.2707%;margin-top:-13.4px;left:85.0944%;width:35px;">
      <p class="g-pstyle2">O</p>
    </div>
    <div id="g-ai1-79" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:35.4715%;margin-top:-13px;left:32.4219%;width:133px;">
      <p class="g-pstyle0">Punta Arenas</p>
    </div>
    <div id="g-ai1-80" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:37.8353%;margin-top:-13.3px;left:39.4434%;width:95px;">
      <p class="g-pstyle0">OFESIÓN</p>
    </div>
    <div id="g-ai1-81" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:37.8631%;margin-top:-12.8px;left:32.9248%;width:33px;">
      <p class="g-pstyle0">P</p>
    </div>
    <div id="g-ai1-82" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:37.8631%;margin-top:-12.8px;left:36.0889%;width:34px;">
      <p class="g-pstyle0">R</p>
    </div>
    <div id="g-ai1-83" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:39.0651%;margin-top:-12.4px;left:32.9248%;width:236px;">
      <p class="g-pstyle1">Egresado de <span class="g-cstyle0">D</span>erecho de la </p>
    </div>
    <div id="g-ai1-84" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:40.2394%;margin-top:-12.4px;left:32.9248%;width:33px;">
      <p class="g-pstyle1">U</p>
    </div>
    <div id="g-ai1-85" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:40.2394%;margin-top:-12.4px;left:35.9218%;width:36px;">
      <p class="g-pstyle1">ni</p>
    </div>
    <div id="g-ai1-86" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:40.2394%;margin-top:-12.4px;left:39.9078%;width:30px;">
      <p class="g-pstyle1">v</p>
    </div>
    <div id="g-ai1-87" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:40.2394%;margin-top:-12.4px;left:42.0882%;width:32px;">
      <p class="g-pstyle1">e</p>
    </div>
    <div id="g-ai1-88" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:40.2394%;margin-top:-12.4px;left:44.7456%;width:28px;">
      <p class="g-pstyle1">r</p>
    </div>
    <div id="g-ai1-89" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:40.2394%;margin-top:-12.4px;left:46.4545%;width:132px;">
      <p class="g-pstyle1">sidad de Chile</p>
    </div>
    <div id="g-ai1-90" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:41.8263%;margin-top:-12.8px;left:33.2189%;width:205px;">
      <p class="g-pstyle0">COLEGIO DE EGERESO</p>
    </div>
    <div id="g-ai1-91" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:43.0283%;margin-top:-12.4px;left:33.2189%;width:191px;">
      <p class="g-pstyle1">The British School de </p>
    </div>
    <div id="g-ai1-92" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:44.2026%;margin-top:-12.4px;left:33.2189%;width:128px;">
      <p class="g-pstyle1">Punta Arenas</p>
    </div>
    <div id="g-ai1-93" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:46.405%;margin-top:-13.4px;left:5.2203%;width:34px;">
      <p class="g-pstyle2">P</p>
    </div>
    <div id="g-ai1-94" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:46.405%;margin-top:-13.4px;left:8.3138%;width:34px;">
      <p class="g-pstyle2">A</p>
    </div>
    <div id="g-ai1-95" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:46.405%;margin-top:-13.4px;left:11.3683%;width:110px;">
      <p class="g-pstyle2">TRIMONIO</p>
    </div>
    <div id="g-ai1-96" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:47.9973%;margin-top:-13px;left:32.5488%;width:33px;">
      <p class="g-pstyle0">U</p>
    </div>
    <div id="g-ai1-97" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:47.9973%;margin-top:-13px;left:35.7058%;width:37px;">
      <p class="g-pstyle0">n </p>
    </div>
    <div id="g-ai1-98" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:47.9973%;margin-top:-13px;left:39.9335%;width:28px;">
      <p class="g-pstyle0">t</p>
    </div>
    <div id="g-ai1-99" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:47.9973%;margin-top:-13px;left:41.5652%;width:126px;">
      <p class="g-pstyle0">erreno en la </p>
    </div>
    <div id="g-ai1-100" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:49.1716%;margin-top:-13px;left:32.5543%;width:202px;">
      <p class="g-pstyle0">comuna de Dalcahue </p>
    </div>
    <div id="g-ai1-101" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:50.3948%;margin-top:-13px;left:32.5543%;width:82px;">
      <p class="g-pstyle0">con un </p>
    </div>
    <div id="g-ai1-102" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:50.3948%;margin-top:-13px;left:49.209%;width:32px;">
      <p class="g-pstyle0">a</p>
    </div>
    <div id="g-ai1-103" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:50.3948%;margin-top:-13px;left:51.9759%;width:31px;">
      <p class="g-pstyle0">v</p>
    </div>
    <div id="g-ai1-104" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:50.3948%;margin-top:-13px;left:54.2993%;width:62px;">
      <p class="g-pstyle0">alúo </p>
    </div>
    <div id="g-ai1-105" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:50.3948%;margin-top:-13px;left:65.5404%;width:28px;">
      <p class="g-pstyle0">f</p>
    </div>
    <div id="g-ai1-106" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:50.3948%;margin-top:-13px;left:67.2472%;width:64px;">
      <p class="g-pstyle0">iscal </p>
    </div>
    <div id="g-ai1-107" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:51.5691%;margin-top:-13px;left:32.5543%;width:86px;">
      <p class="g-pstyle0">de $ 12</p>
    </div>
    <div id="g-ai1-108" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:51.5691%;margin-top:-13px;left:50.2935%;width:27px;">
      <p class="g-pstyle0">.</p>
    </div>
    <div id="g-ai1-109" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:51.5691%;margin-top:-13px;left:51.3775%;width:33px;">
      <p class="g-pstyle0">1</p>
    </div>
    <div id="g-ai1-110" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:51.5691%;margin-top:-13px;left:54.4116%;width:33px;">
      <p class="g-pstyle0">1</p>
    </div>
    <div id="g-ai1-111" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:51.5691%;margin-top:-13px;left:57.3706%;width:72px;">
      <p class="g-pstyle0">0.823</p>
    </div>
    <div id="g-ai1-112" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:53.6241%;margin-top:-13px;left:32.9468%;width:33px;">
      <p class="g-pstyle0">U</p>
    </div>
    <div id="g-ai1-113" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:53.6241%;margin-top:-13px;left:36.1035%;width:64px;">
      <p class="g-pstyle0">na m</p>
    </div>
    <div id="g-ai1-114" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:53.6241%;margin-top:-13px;left:47.8684%;width:32px;">
      <p class="g-pstyle0">o</p>
    </div>
    <div id="g-ai1-115" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:53.6241%;margin-top:-13px;left:50.6538%;width:28px;">
      <p class="g-pstyle0">t</p>
    </div>
    <div id="g-ai1-116" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:53.6241%;margin-top:-13px;left:52.2936%;width:37px;">
      <p class="g-pstyle0">o </p>
    </div>
    <div id="g-ai1-117" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:53.6241%;margin-top:-13px;left:56.3843%;width:33px;">
      <p class="g-pstyle0">Y</p>
    </div>
    <div id="g-ai1-118" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:53.6241%;margin-top:-13px;left:59.0346%;width:85px;">
      <p class="g-pstyle0">amaha </p>
    </div>
    <div id="g-ai1-119" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:54.8473%;margin-top:-13px;left:32.9468%;width:82px;">
      <p class="g-pstyle0">con un </p>
    </div>
    <div id="g-ai1-120" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:54.8473%;margin-top:-13px;left:49.6015%;width:32px;">
      <p class="g-pstyle0">a</p>
    </div>
    <div id="g-ai1-121" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:54.8473%;margin-top:-13px;left:52.3684%;width:31px;">
      <p class="g-pstyle0">v</p>
    </div>
    <div id="g-ai1-122" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:54.8473%;margin-top:-13px;left:54.6918%;width:62px;">
      <p class="g-pstyle0">alúo </p>
    </div>
    <div id="g-ai1-123" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:54.8473%;margin-top:-13px;left:65.9304%;width:28px;">
      <p class="g-pstyle0">f</p>
    </div>
    <div id="g-ai1-124" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:54.8473%;margin-top:-13px;left:67.6397%;width:64px;">
      <p class="g-pstyle0">iscal </p>
    </div>
    <div id="g-ai1-125" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:56.0216%;margin-top:-13px;left:32.9468%;width:102px;">
      <p class="g-pstyle0">de $ 702.</p>
    </div>
    <div id="g-ai1-126" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:56.0216%;margin-top:-13px;left:55.1031%;width:33px;">
      <p class="g-pstyle0">4</p>
    </div>
    <div id="g-ai1-127" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:56.0216%;margin-top:-13px;left:58.2761%;width:45px;">
      <p class="g-pstyle0">49</p>
    </div>
    <div id="g-ai1-128" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:57.8319%;margin-top:-13px;left:33.0474%;width:32px;">
      <p class="g-pstyle0">F</p>
    </div>
    <div id="g-ai1-129" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:57.8319%;margin-top:-13px;left:35.6595%;width:169px;">
      <p class="g-pstyle0">ondos mutuos en </p>
    </div>
    <div id="g-ai1-130" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:59.0062%;margin-top:-13px;left:33.0474%;width:188px;">
      <p class="g-pstyle0">el Banco Santander </p>
    </div>
    <div id="g-ai1-131" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:60.1805%;margin-top:-13px;left:33.0474%;width:82px;">
      <p class="g-pstyle0">con un </p>
    </div>
    <div id="g-ai1-132" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:60.1805%;margin-top:-13px;left:49.7021%;width:31px;">
      <p class="g-pstyle0">v</p>
    </div>
    <div id="g-ai1-133" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:60.1805%;margin-top:-13px;left:52.0258%;width:84px;">
      <p class="g-pstyle0">alor de </p>
    </div>
    <div id="g-ai1-134" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:61.4037%;margin-top:-13px;left:33.0474%;width:38px;">
      <p class="g-pstyle0">$ </p>
    </div>
    <div id="g-ai1-135" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:61.4037%;margin-top:-13px;left:37.513%;width:33px;">
      <p class="g-pstyle0">3</p>
    </div>
    <div id="g-ai1-136" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:61.4037%;margin-top:-13px;left:40.3971%;width:33px;">
      <p class="g-pstyle0">1</p>
    </div>
    <div id="g-ai1-137" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:61.4037%;margin-top:-13px;left:43.4956%;width:99px;">
      <p class="g-pstyle0">.223.320</p>
    </div>
  </div>


</div>
`

const containerId = 'g-pag-ficha-personal-box'
const namespace = 'g-'
const name = 'pag-ficha-personal'

export default makeAi2React({ html, styles, containerId, namespace, name })

/* End ai2react - 2021-12-20 02:38 */
