/* Generated by ai2react v0.102.0 - 2021-12-20 03:12 */
/* ai file: Elecciones 2021 - Presidenciables Boric.ai */

import { makeAi2React } from './src'

const styles = `
  #g-Elecciones-2021---Presidenciables-Boric-box ,
  #g-Elecciones-2021---Presidenciables-Boric-box .g-artboard {
    margin:0 auto;
  }
  #g-Elecciones-2021---Presidenciables-Boric-box p {
    margin:0;
  }
  #g-Elecciones-2021---Presidenciables-Boric-box .g-aiAbs {
    position:absolute;
  }
  #g-Elecciones-2021---Presidenciables-Boric-box .g-aiImg {
    position:absolute;
    top:0;
    display:block;
    width:100% !important;
  }
  #g-Elecciones-2021---Presidenciables-Boric-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-Elecciones-2021---Presidenciables-Boric-box .g-aiPointText p { white-space: nowrap; }
  #g-Elecciones-2021---Presidenciables-Boric-large {
    position:relative;
    overflow:hidden;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large p {
    font-weight:500;
    line-height:24px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:20px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-pstyle0 {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:38px;
    height:38px;
    font-size:32px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-pstyle1 {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:30px;
    height:30px;
    font-size:25px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-pstyle2 {
    line-height:28px;
    height:28px;
    font-size:23px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-pstyle3 {
    line-height:29px;
    height:29px;
    font-size:24px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-pstyle4 {
    height:24px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle0 {
    letter-spacing:-0.014em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle1 {
    letter-spacing:-0.02em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle2 {
    letter-spacing:-0.053em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle3 {
    letter-spacing:-0.038em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle4 {
    letter-spacing:-0.032em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle5 {
    letter-spacing:-0.018em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle6 {
    letter-spacing:-0.037em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle7 {
    letter-spacing:-0.008em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle8 {
    letter-spacing:-0.034em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle9 {
    letter-spacing:-0.069em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle10 {
    letter-spacing:-0.006em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle11 {
    letter-spacing:-0.013em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle12 {
    letter-spacing:-0.009em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle13 {
    letter-spacing:-0.016em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle14 {
    letter-spacing:-0.017em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle15 {
    letter-spacing:-0.022em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle16 {
    letter-spacing:-0.015em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle17 {
    letter-spacing:-0.004em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle18 {
    letter-spacing:-0.007em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle19 {
    letter-spacing:-0.054em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle20 {
    letter-spacing:-0.021em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle21 {
    letter-spacing:0.028em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle22 {
    letter-spacing:0.025em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle23 {
    letter-spacing:-0.04em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle24 {
    letter-spacing:-0.024em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-large .g-cstyle25 {
    letter-spacing:-0.064em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small {
    position:relative;
    overflow:hidden;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small p {
    font-weight:500;
    line-height:14px;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:12px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    height:auto;
    position:static;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-pstyle0 {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:22px;
    height:22px;
    font-size:18px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-pstyle1 {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:17px;
    height:17px;
    font-size:14px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-pstyle2 {
    line-height:16px;
    height:16px;
    font-size:13px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-pstyle3 {
    line-height:16px;
    height:16px;
    font-size:14px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-pstyle4 {
    height:14px;
    font-size:11px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-pstyle5 {
    height:14px;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle0 {
    letter-spacing:-0.014em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle1 {
    letter-spacing:-0.053em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle2 {
    letter-spacing:-0.038em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle3 {
    letter-spacing:-0.032em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle4 {
    letter-spacing:-0.018em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle5 {
    letter-spacing:-0.037em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle6 {
    letter-spacing:-0.008em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle7 {
    letter-spacing:-0.009em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle8 {
    letter-spacing:-0.016em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle9 {
    letter-spacing:-0.02em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle10 {
    letter-spacing:-0.034em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle11 {
    letter-spacing:-0.069em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle12 {
    letter-spacing:-0.006em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle13 {
    letter-spacing:-0.013em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle14 {
    letter-spacing:-0.017em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle15 {
    letter-spacing:-0.022em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle16 {
    letter-spacing:-0.015em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle17 {
    letter-spacing:-0.004em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle18 {
    letter-spacing:-0.007em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle19 {
    letter-spacing:-0.054em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle20 {
    letter-spacing:-0.021em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle21 {
    letter-spacing:0.028em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle22 {
    letter-spacing:0.025em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle23 {
    letter-spacing:-0.04em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle24 {
    letter-spacing:-0.024em;
  }
  #g-Elecciones-2021---Presidenciables-Boric-small .g-cstyle25 {
    letter-spacing:-0.064em;
  }

`

const html = props => `
<div id="g-Elecciones-2021---Presidenciables-Boric-box" class="ai2html">


  <!-- Artboard: large -->
  <div id="g-Elecciones-2021---Presidenciables-Boric-large" class="g-artboard" style="width:1280px; height:651.713989257813px;" data-aspect-ratio="1.964" data-min-width="1280">
<div style=""></div>
    <img id="g-Elecciones-2021---Presidenciables-Boric-large-img" class="g-aiImg" alt="" src="https://especiales.latercera.com/boric-presidente-assets/Elecciones-2021---Presidenciables-Boric-large.jpg"/>
    <div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:10.4296%;margin-top:-22px;left:2.0266%;width:305px;">
      <p class="g-pstyle0">HIS<span class="g-cstyle0">T</span>ORIAL POLÍTICO</p>
    </div>
    <div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:10.8567%;margin-top:-16.8px;left:58.2466%;width:167px;">
      <p class="g-pstyle1">C<span class="g-cstyle1">O</span>ALICIONES</p>
    </div>
    <div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.4232%;margin-top:-16.8px;left:2.0259%;width:146px;">
      <p class="g-pstyle1">MILI<span class="g-cstyle2">T</span>ANCIA</p>
    </div>
    <div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:2.3782%;width:76px;">
      <p class="g-pstyle2">2008</p>
    </div>
    <div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:9.3178%;width:76px;">
      <p class="g-pstyle2">2009</p>
    </div>
    <div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:16.3202%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>0</p>
    </div>
    <div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:23.2471%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle5">1</span>1</p>
    </div>
    <div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:30.1705%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle6">0</span>12</p>
    </div>
    <div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:37.1172%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle7">1</span>3</p>
    </div>
    <div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:44.0783%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>4</p>
    </div>
    <div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:51.0017%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle0">1</span>5</p>
    </div>
    <div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:57.9591%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle8">1</span>6</p>
    </div>
    <div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:64.9293%;width:73px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle9">1</span>7</p>
    </div>
    <div id="g-ai0-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:71.813%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle10">1</span>8</p>
    </div>
    <div id="g-ai0-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:78.758%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle11">1</span>9</p>
    </div>
    <div id="g-ai0-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:85.6508%;width:76px;">
      <p class="g-pstyle2">2020</p>
    </div>
    <div id="g-ai0-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.0414%;margin-top:-15.9px;left:92.6209%;width:75px;">
      <p class="g-pstyle2">20<span class="g-cstyle8">2</span>1</p>
    </div>
    <div id="g-ai0-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.0356%;margin-top:-16.5px;left:3.6918%;width:115px;">
      <p class="g-pstyle3">Iz<span class="g-cstyle12">q</span>uie<span class="g-cstyle13">r</span>da</p>
    </div>
    <div id="g-ai0-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.0356%;margin-top:-16.5px;left:58.9986%;width:140px;">
      <p class="g-pstyle3">M<span class="g-cstyle14">o</span>vimien<span class="g-cstyle0">t</span>o</p>
    </div>
    <div id="g-ai0-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.0356%;margin-top:-16.5px;left:79.9855%;width:158px;">
      <p class="g-pstyle3">Co<span class="g-cstyle15">n</span><span class="g-cstyle16">v</span>ergencia</p>
    </div>
    <div id="g-ai0-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.7182%;margin-top:-16.5px;left:3.6918%;width:125px;">
      <p class="g-pstyle3"><span class="g-cstyle13">A</span>utónoma</p>
    </div>
    <div id="g-ai0-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.7182%;margin-top:-16.5px;left:58.9986%;width:149px;">
      <p class="g-pstyle3"><span class="g-cstyle13">A</span>u<span class="g-cstyle16">t</span>onomista</p>
    </div>
    <div id="g-ai0-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.7182%;margin-top:-16.5px;left:79.9855%;width:83px;">
      <p class="g-pstyle3">Social</p>
    </div>
    <div id="g-ai0-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.8069%;margin-top:-17.3px;left:2.0266%;width:353px;">
      <p class="g-pstyle1"><span class="g-cstyle17">C</span>A<span class="g-cstyle18">R</span>GOS DE REPRESEN<span class="g-cstyle19">T</span><span class="g-cstyle20">A</span>CIÓN</p>
    </div>
    <div id="g-ai0-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:2.3782%;width:76px;">
      <p class="g-pstyle2">2008</p>
    </div>
    <div id="g-ai0-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:9.3178%;width:76px;">
      <p class="g-pstyle2">2009</p>
    </div>
    <div id="g-ai0-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:16.3202%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>0</p>
    </div>
    <div id="g-ai0-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:23.2471%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle5">1</span>1</p>
    </div>
    <div id="g-ai0-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:30.1705%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle6">0</span>12</p>
    </div>
    <div id="g-ai0-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:37.1172%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle7">1</span>3</p>
    </div>
    <div id="g-ai0-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:44.0783%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>4</p>
    </div>
    <div id="g-ai0-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:51.0017%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle0">1</span>5</p>
    </div>
    <div id="g-ai0-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:57.9591%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle8">1</span>6</p>
    </div>
    <div id="g-ai0-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:64.9293%;width:73px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle9">1</span>7</p>
    </div>
    <div id="g-ai0-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:71.813%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle10">1</span>8</p>
    </div>
    <div id="g-ai0-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:78.758%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle11">1</span>9</p>
    </div>
    <div id="g-ai0-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:85.6508%;width:76px;">
      <p class="g-pstyle2">2020</p>
    </div>
    <div id="g-ai0-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4916%;margin-top:-15.9px;left:92.6209%;width:75px;">
      <p class="g-pstyle2">20<span class="g-cstyle8">2</span>1</p>
    </div>
    <div id="g-ai0-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:76.6393%;margin-top:-16.5px;left:24.485%;width:130px;">
      <p class="g-pstyle3">Presiden<span class="g-cstyle5">t</span>e</p>
    </div>
    <div id="g-ai0-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:76.6393%;margin-top:-16.5px;left:45.3069%;width:114px;">
      <p class="g-pstyle3">Diputado</p>
    </div>
    <div id="g-ai0-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:76.6393%;margin-top:-16.5px;left:73.2443%;width:114px;">
      <p class="g-pstyle3">Diputado</p>
    </div>
    <div id="g-ai0-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.3219%;margin-top:-16.5px;left:45.3069%;width:149px;">
      <p class="g-pstyle3">Exdistri<span class="g-cstyle16">t</span>o 60</p>
    </div>
    <div id="g-ai0-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.3219%;margin-top:-16.5px;left:73.2443%;width:143px;">
      <p class="g-pstyle3">Distri<span class="g-cstyle16">t</span>o 28*</p>
    </div>
    <div id="g-ai0-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.0891%;margin-top:-16.5px;left:24.485%;width:132px;">
      <p class="g-pstyle3">de la FECH</p>
    </div>
    <div id="g-ai0-45" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.7823%;margin-top:-13.6px;left:2.0266%;width:834px;">
      <p class="g-pstyle4">*Antiguo distri<span class="g-cstyle13">t</span>o 60, co<span class="g-cstyle12">m</span>pues<span class="g-cstyle13">t</span>o por las comunas de Antá<span class="g-cstyle21">r</span>tica, Cabo de Hornos, Laguna Blanca, </p>
    </div>
    <div id="g-ai0-46" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:94.4648%;margin-top:-13.6px;left:2.0266%;width:824px;">
      <p class="g-pstyle4">Natales, <span class="g-cstyle16">P</span>o<span class="g-cstyle22">r</span><span class="g-cstyle16">v</span>eni<span class="g-cstyle19">r</span>, Prim<span class="g-cstyle15">a</span><span class="g-cstyle16">v</span>era, Punta Arenas, Río <span class="g-cstyle23">V</span>e<span class="g-cstyle13">r</span>de, San Gregorio, Timau<span class="g-cstyle24">k</span>el, <span class="g-cstyle25">T</span>orres del <span class="g-cstyle18">P</span>aine</p>
    </div>
  </div>

  <!-- Artboard: small -->
  <div id="g-Elecciones-2021---Presidenciables-Boric-small" class="g-artboard" style="max-width: 360px;max-height: 655px" data-aspect-ratio="0.549" data-min-width="0" data-max-width="1279">
<div style="padding: 0 0 182.0679% 0;"></div>
    <img id="g-Elecciones-2021---Presidenciables-Boric-small-img" class="g-aiImg" alt="" src="https://especiales.latercera.com/boric-presidente-assets/Elecciones-2021---Presidenciables-Boric-small.jpg"/>
    <div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:4.2362%;margin-top:-12.8px;left:6.0645%;width:182px;">
      <p class="g-pstyle0">HIS<span class="g-cstyle0">T</span>ORIAL POLÍTICO</p>
    </div>
    <div id="g-ai1-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:12.448%;margin-top:-9.6px;left:4.2556%;width:92px;">
      <p class="g-pstyle1">MILI<span class="g-cstyle1">T</span>ANCIA</p>
    </div>
    <div id="g-ai1-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.0344%;margin-top:-9.1px;left:4.9666%;width:53px;">
      <p class="g-pstyle2">2008</p>
    </div>
    <div id="g-ai1-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.0344%;margin-top:-9.1px;left:18.9689%;width:53px;">
      <p class="g-pstyle2">2009</p>
    </div>
    <div id="g-ai1-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.0344%;margin-top:-9.1px;left:33.0981%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle3">1</span>0</p>
    </div>
    <div id="g-ai1-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.0344%;margin-top:-9.1px;left:47.0749%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle4">1</span>1</p>
    </div>
    <div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.0344%;margin-top:-9.1px;left:61.0447%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle5">0</span>12</p>
    </div>
    <div id="g-ai1-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.0344%;margin-top:-9.1px;left:75.0616%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle6">1</span>3</p>
    </div>
    <div id="g-ai1-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.0344%;margin-top:-9.1px;left:89.107%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle3">1</span>4</p>
    </div>
    <div id="g-ai1-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:20.1279%;margin-top:-8.9px;left:7.6169%;width:75px;">
      <p class="g-pstyle3">Iz<span class="g-cstyle7">q</span>uie<span class="g-cstyle8">r</span>da</p>
    </div>
    <div id="g-ai1-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:22.2639%;margin-top:-8.9px;left:7.6169%;width:80px;">
      <p class="g-pstyle3"><span class="g-cstyle8">A</span>utónoma</p>
    </div>
    <div id="g-ai1-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.9253%;margin-top:-9.6px;left:18.8911%;width:105px;">
      <p class="g-pstyle1">C<span class="g-cstyle9">O</span>ALICIONES</p>
    </div>
    <div id="g-ai1-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.039%;margin-top:-9.1px;left:4.2727%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle0">1</span>5</p>
    </div>
    <div id="g-ai1-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.039%;margin-top:-9.1px;left:18.3111%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle10">1</span>6</p>
    </div>
    <div id="g-ai1-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.039%;margin-top:-9.1px;left:32.3749%;width:51px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle11">1</span>7</p>
    </div>
    <div id="g-ai1-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.039%;margin-top:-9.1px;left:46.2649%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle12">1</span>8</p>
    </div>
    <div id="g-ai1-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.039%;margin-top:-9.1px;left:60.278%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle13">1</span>9</p>
    </div>
    <div id="g-ai1-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.039%;margin-top:-9.1px;left:74.1859%;width:53px;">
      <p class="g-pstyle2">2020</p>
    </div>
    <div id="g-ai1-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.039%;margin-top:-9.1px;left:88.2501%;width:52px;">
      <p class="g-pstyle2">20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai1-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.1325%;margin-top:-8.9px;left:20.4088%;width:89px;">
      <p class="g-pstyle3">M<span class="g-cstyle14">o</span>vimien<span class="g-cstyle0">t</span>o</p>
    </div>
    <div id="g-ai1-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.1325%;margin-top:-8.9px;left:62.7547%;width:99px;">
      <p class="g-pstyle3">Co<span class="g-cstyle15">n</span><span class="g-cstyle16">v</span>ergencia</p>
    </div>
    <div id="g-ai1-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.1159%;margin-top:-8.9px;left:20.4088%;width:94px;">
      <p class="g-pstyle3"><span class="g-cstyle8">A</span>u<span class="g-cstyle16">t</span>onomista</p>
    </div>
    <div id="g-ai1-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.1159%;margin-top:-8.9px;left:62.7547%;width:57px;">
      <p class="g-pstyle3">Social</p>
    </div>
    <div id="g-ai1-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.9971%;margin-top:-9.9px;left:3.7207%;width:210px;">
      <p class="g-pstyle1"><span class="g-cstyle17">C</span>A<span class="g-cstyle18">R</span>GOS DE REPRESEN<span class="g-cstyle19">T</span><span class="g-cstyle20">A</span>CIÓN</p>
    </div>
    <div id="g-ai1-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.1448%;margin-top:-9.1px;left:4.4303%;width:53px;">
      <p class="g-pstyle2">2008</p>
    </div>
    <div id="g-ai1-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.1448%;margin-top:-9.1px;left:18.4326%;width:53px;">
      <p class="g-pstyle2">2009</p>
    </div>
    <div id="g-ai1-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.1448%;margin-top:-9.1px;left:32.5618%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle3">1</span>0</p>
    </div>
    <div id="g-ai1-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.1448%;margin-top:-9.1px;left:46.5386%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle4">1</span>1</p>
    </div>
    <div id="g-ai1-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.1448%;margin-top:-9.1px;left:60.5084%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle5">0</span>12</p>
    </div>
    <div id="g-ai1-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.1448%;margin-top:-9.1px;left:74.5253%;width:52px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle6">1</span>3</p>
    </div>
    <div id="g-ai1-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:71.2383%;margin-top:-8.9px;left:49.0362%;width:83px;">
      <p class="g-pstyle3">Presiden<span class="g-cstyle4">t</span>e</p>
    </div>
    <div id="g-ai1-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:73.6793%;margin-top:-8.9px;left:49.0362%;width:85px;">
      <p class="g-pstyle3">de la FECH</p>
    </div>
    <div id="g-ai1-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3551%;margin-top:-8.1px;left:3.7207%;width:48px;">
      <p class="g-pstyle4">2<span class="g-cstyle2">0</span><span class="g-cstyle3">1</span>4</p>
    </div>
    <div id="g-ai1-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3551%;margin-top:-8.1px;left:15.9109%;width:48px;">
      <p class="g-pstyle4">2<span class="g-cstyle2">0</span><span class="g-cstyle0">1</span>5</p>
    </div>
    <div id="g-ai1-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3551%;margin-top:-8.1px;left:28.1605%;width:48px;">
      <p class="g-pstyle4">2<span class="g-cstyle2">0</span><span class="g-cstyle10">1</span>6</p>
    </div>
    <div id="g-ai1-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3551%;margin-top:-8.1px;left:40.4324%;width:47px;">
      <p class="g-pstyle4">2<span class="g-cstyle2">0</span><span class="g-cstyle11">1</span>7</p>
    </div>
    <div id="g-ai1-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3551%;margin-top:-8.1px;left:52.5526%;width:48px;">
      <p class="g-pstyle4">2<span class="g-cstyle2">0</span><span class="g-cstyle12">1</span>8</p>
    </div>
    <div id="g-ai1-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3551%;margin-top:-8.1px;left:64.7803%;width:48px;">
      <p class="g-pstyle4">2<span class="g-cstyle2">0</span><span class="g-cstyle13">1</span>9</p>
    </div>
    <div id="g-ai1-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3551%;margin-top:-8.1px;left:76.9162%;width:49px;">
      <p class="g-pstyle4">2020</p>
    </div>
    <div id="g-ai1-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3551%;margin-top:-8.1px;left:89.1884%;width:48px;">
      <p class="g-pstyle4">20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai1-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:82.8319%;margin-top:-7.9px;left:5.8838%;width:68px;">
      <p class="g-pstyle5">Diputado</p>
    </div>
    <div id="g-ai1-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:82.8319%;margin-top:-7.9px;left:55.0727%;width:68px;">
      <p class="g-pstyle5">Diputado</p>
    </div>
    <div id="g-ai1-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.6627%;margin-top:-7.9px;left:5.8838%;width:85px;">
      <p class="g-pstyle5">Exdistri<span class="g-cstyle16">t</span>o 60</p>
    </div>
    <div id="g-ai1-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.6627%;margin-top:-7.9px;left:55.0727%;width:82px;">
      <p class="g-pstyle5">Distri<span class="g-cstyle16">t</span>o 28*</p>
    </div>
    <div id="g-ai1-45" class="g-Layer_1 g-aiAbs" style="top:88.9473%;left:3.9356%;width:94.7222%;">
      <p>*Antiguo distri<span class="g-cstyle8">t</span>o 60, co<span class="g-cstyle7">m</span>pues<span class="g-cstyle8">t</span>o por las comunas de Antá<span class="g-cstyle21">r</span>tica, Cabo de Hornos, Laguna Blanca, Natales, <span class="g-cstyle16">P</span>o<span class="g-cstyle22">r</span><span class="g-cstyle16">v</span>eni<span class="g-cstyle19">r</span>, Prim<span class="g-cstyle15">a</span><span class="g-cstyle16">v</span>era, Punta Arenas, Río <span class="g-cstyle23">V</span>e<span class="g-cstyle8">r</span>de, San Gregorio, Timau<span class="g-cstyle24">k</span>el, <span class="g-cstyle25">T</span>orres del <span class="g-cstyle18">P</span>aine</p>
    </div>
  </div>


</div>
`

const containerId = 'g-Elecciones-2021---Presidenciables-Boric-box'
const namespace = 'g-'
const name = 'Elecciones_2021_-_Presidenciables_Boric'

export default makeAi2React({ html, styles, containerId, namespace, name })

/* End ai2react - 2021-12-20 03:12 */
