const fichas = [
  {
    nombre: `Sebastián`,
    apellido: `Soto`,
    edad: `46`,
    profesion: `Abogado`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `Independiente`,
    cupo: `Evópoli - Senado`,
    posgrado: `Máster en derecho de la Universidad de Columbia y doctor en derecho de la Universidad de Chile`,
    cargoactual: `Director del Departamento de Derecho Público de la Pontificia Universidad Católica de Chile y consejero del Consejo de Defensa del Estado`,
    cargosanteriores: `Exjefe de la División Jurídico Legislativa de la Segpres`,
    foto: `https://www.latercera.com/resizer/REiAhbE7DGdTxoN3qeDHwJQAKOs=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/SO23B556QFGERNCONBG5N3QYXY.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Bettina`,
    apellido: `Horst`,
    edad: `52`,
    profesion: `Economista`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `Independiente`,
    cupo: `UDI - Senado`,
    posgrado: `Máster en economía con mención en políticas públicas de la Pontificia Universidad Católica de Chile`,
    cargoactual: `Directora ejecutiva de Libertad y Desarrollo y consejera del Consejo de Alta Dirección Pública`,
    cargosanteriores: `Execonomista del Banco Central y exjefa del Área Monetaria del Departamento de Estudios del Banco Central`,
    foto: `https://www.latercera.com/resizer/Jg6fvjdw7V8w6-m9tdLZL1KguYI=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/JMKJR4R4XVA3JHXY5CGXLEZ3DA.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Hernán`,
    apellido: `Larraín`,
    edad: `75`,
    profesion: `Abogado`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `UDI`,
    cupo: `UDI - Senado`,
    posgrado: `Máster en derecho de la London School of Economics`,
    cargoactual: `Académico de la Pontificia Universidad Católica de Chile a partir de marzo de 2023`,
    cargosanteriores: `Exministro de Justicia, exsenador UDI y expresidente de la UDI`,
    foto: `https://www.latercera.com/resizer/Gl_hhHdA4Vue_2muONn_hHObtS4=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/ICZVI7KL2RFGRBBSPGZVBY4FYY.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Teodoro`,
    apellido: `Ribera`,
    edad: `64`,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: `RN`,
    cupo: `RN - Senado`,
    posgrado: `Doctor en derecho de la Universidad Julius Maximilians de Wurzburgo`,
    cargoactual: `Rector de la Universidad Autónoma`,
    cargosanteriores: `Exministro de Justicia, excanciller, exabogado integrante del Tribunal Constitucional y exdiputado`,
    foto: `https://www.latercera.com/resizer/Bf9dh08cN2srgWa3Hv98DAjdpsM=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/SAIAKTGJKRA2ZFX2XWZDGTKQWM.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Katherine`,
    apellido: `Martorell`,
    edad: `41`,
    profesion: `Abogada`,
    universidad: `Universidad Central`,
    filiacion: `RN`,
    cupo: `RN - Senado`,
    posgrado: `Magíster en derecho de la Pontificia Universidad Católica de Chile`,
    cargoactual: `Asesora del gabinete de la alcaldesa de Providencia Evelyn Matthei`,
    cargosanteriores: `Exsubsecretaria de Prevención del Delito`,
    foto: `https://www.latercera.com/resizer/x_ztG7Ek1DaQ8lWmV5k2B5279pI=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/S2YQQ7ZRXRGZJN2KGQUB5SL6CM.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Jaime`,
    apellido: `Arancibia`,
    edad: `47`,
    profesion: `Abogado`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `Independiente`,
    cupo: `RN - Senado`,
    posgrado: `Doctor en derecho de la Universidad de Cambridge`,
    cargoactual: `Director del Departamento de Derecho Público de la Universidad de los Andes`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/QhYV21EkUwD3mm5xjT80OTV5Fyg=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/BVA44TOG3JDLZNC6EH4PKT727E.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Gabriel`,
    apellido: `Osorio`,
    edad: `39`,
    profesion: `Abogado`,
    universidad: `Universidad Central`,
    filiacion: `PS`,
    cupo: `PS - Senado`,
    posgrado: `Magíster en Derecho de la Universidad de Chile`,
    cargoactual: `Profesor de derecho constitucional de la Universidad Andrés Bello y de Derecho Electoral de la Universidad Central y de la Universidad Adolfo Ibáñez y profesor invitado de posgrado de la Universidad de Chile y socio de Osorio, Vargas y Asociados`,
    cargosanteriores: `Exabogado de la División Jurídica de la Segpres y del Ministerio del Interior`,
    foto: `https://www.latercera.com/resizer/mSZFmNQoaxMHgC9kofwZmiga8sU=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/AYF6J5VJSNAYJIEBTWPDK3CTTU.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Catalina`,
    apellido: `Lagos`,
    edad: `39`,
    profesion: `Abogada`,
    universidad: `Universidad Diego Portales`,
    filiacion: `PS`,
    cupo: `PS - Senado`,
    posgrado: `Magíster en derecho de la Universidad de Chile`,
    cargoactual: `Profesora del Departamento de Derecho Público de la Universidad Alberto Hurtado y asesora en el Ministerio del Interior`,
    cargosanteriores: `Exabogada del Programa de Derechos Humanos del Ministerio del Interior, exjefa de Relaciones Internacionales del Ministerio de la Mujer y exasesora del Colectivo Socialista en la Convención Constitucional`,
    foto: `https://www.latercera.com/resizer/qBnqUfW88Gzj46NG0gR7nEzVlcs=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/HWQDVYJTTZGC7KK25F4CXAF6E4.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Leslie`,
    apellido: `Sánchez`,
    edad: `39`,
    profesion: `Abogada`,
    universidad: `Universidad Católica de la Santísima Concepción`,
    filiacion: `PL`,
    cupo: `PPD - Senado`,
    posgrado: `Magíster en Ciencias Jurídicas por la Pontificia Universidad Católica de Chile. Doctora en Derecho por la Pontificia Universidad Católica de Chile. Doctora mención internacional en Estado de Derecho y Gobernanza Global por la Universidad de Salamanca.`,
    cargoactual: `Académica de la Universidad Alberto Hurtado y Universidad de Valparaíso y asesora legislativa del Ministerio del Interior`,
    cargosanteriores: `Exasesora legislativa del senador Ricardo Lagos Weber`,
    foto: `https://www.latercera.com/resizer/p_8_lieCUfXqJObBmWpzRGCvFXs=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/RDDMYPHVMRAOTK2RGYSS7U4JPA.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Alejandra`,
    apellido: `Krauss`,
    edad: `66`,
    profesion: `Abogada`,
    universidad: `Universidad de Chile`,
    filiacion: `DC`,
    cupo: `DC- Senado`,
    posgrado: `-`,
    cargoactual: `Socia de Krauss, Donoso y Cía`,
    cargosanteriores: `Exministra Mideplan, exministra del Trabajo, exconcejal de La Florida y exdirectora de la Corporación de Asistencia Judicial Metropolitana`,
    foto: `https://www.latercera.com/resizer/Jde7yeCkLAeu3IoPpxv4BcGIePE=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/DZOUG3LOW5DEPHZACDGLUQGYFM.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Magaly`,
    apellido: `Fuenzalida`,
    edad: `42`,
    profesion: `Periodista`,
    universidad: `Pontificia Universidad Católica de Valparaíso`,
    filiacion: `Independiente`,
    cupo: `FRVS - Senado`,
    posgrado: `Diplomado en Community Manager del Instituto Arcos y diplomado en Comunicación y Políticas Públicas de la Universidad de Chile`,
    cargoactual: `Encargada de comunicaciones y gestión de prensa del comité de senadores de la FRVS`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/DxE9I-17_h0uQjzDW2g_ML9WBTQ=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/6TFIESWEVNBUNOOBTLFMLCP2SY.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Francisco`,
    apellido: `Soto`,
    edad: `53`,
    profesion: `Abogado`,
    universidad: `Universidad Diego Portales`,
    filiacion: `Independiente`,
    cupo: `PPD - Senado`,
    posgrado: `Magíster en derecho constitucional de la Universidad Diego Portales y doctor en derecho de la Universidad de Barcelona`,
    cargoactual: `Director de investigación de la Universidad de Chile y profesor de derecho constitucional `,
    cargosanteriores: `Exintegrante del Consejo Ciudadano de Observadores y exintegrante de la Secretaría Técnica de Participación de la Convención Constitucional`,
    foto: `https://www.latercera.com/resizer/LVg7JIhiLaOTQp4UnKGR-5RWbpY=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/TJDZYBJKNVHYNAB6W5O4UZM5AY.jpg`,
    origen: `Senado`,
  },
  {
    nombre: `Natalia`,
    apellido: `González`,
    edad: `45`,
    profesion: `Abogada`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `Independiente`,
    cupo: `UDI - Cámara`,
    posgrado: `Máster en derecho de la Universidad de Chicago`,
    cargoactual: `Consejera de Políticas Públicas de Libertad y Desarrollo y consejera del Consejo para la Transparencia`,
    cargosanteriores: ``,
    foto: `https://www.latercera.com/resizer/HfIMjDEsPWEvc2kgp9OnWR4F9iI=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/ZM4VUVRB4BHWVN7GPQQY4RIMAQ.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Máximo`,
    apellido: `Pavez`,
    edad: `39`,
    profesion: `Abogado`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `UDI`,
    cupo: `UDI - Cámara`,
    posgrado: `- `,
    cargoactual: `Académico de la Pontificia Universidad Católica de Chile y vicepresidente de la UDI`,
    cargosanteriores: `Exconcejal de Conchalí, exjefe de Relaciones Políticas de la Segpres y exsubsecretario Segpres`,
    foto: `https://www.latercera.com/resizer/a1zEYtlX5c6pP1gwVu3WQtzwk-A=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/NB5LBZKF2ZAD5MW75DZSALFTJ4.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Catalina`,
    apellido: `Salem`,
    edad: `36`,
    profesion: `Abogada`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `Independiente`,
    cupo: `RN - Cámara`,
    posgrado: `Magíster en derecho de la Pontificia Universidad Católica de Chile`,
    cargoactual: `Acádemica del Centro de Justicia Constitucional de la Universidad del Desarrollo`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/k6wgQeZ4610qS3CqyBYbhVS6c8k=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/ZEHQZI4RKNHPNI5ZTTLKJF6WNY.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Juan José`,
    apellido: `Ossa`,
    edad: `43`,
    profesion: `Abogado`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `RN`,
    cupo: `RN - Cámara`,
    posgrado: `Máster en derecho de la London School of Economics`,
    cargoactual: `Director del Centro de Políticas Públicas de la Universidad San Sebastián`,
    cargosanteriores: `Exsubsecretario de Justicia y exministro Segpres                                                                                         `,
    foto: `https://www.latercera.com/resizer/gfg576rt7DCcwR2U739fV2DZjXs=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/6WSGUVZ5SBAD3DXBH7UE2NJYCY.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Carlos`,
    apellido: `Frontaura`,
    edad: `58`,
    profesion: `Abogado`,
    universidad: ` Pontificia Universidad Católica de Chile`,
    filiacion: `Independiente`,
    cupo: `Repúblicano - Cámara`,
    posgrado: `- `,
    cargoactual: `Académico y director del Departamento de Fundamentos del Derecho de la Pontificia Universidad Católica de Chile`,
    cargosanteriores: `Exconsejero del Instituto Nacional de Derechos Humanos`,
    foto: `https://www.latercera.com/resizer/NC4CFtUaXQWw-DOQWSVF_ABGw_Y=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/CBIAQ54JQRHDJNEEBRQG7SQXIQ.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Marcela`,
    apellido: `Peredo`,
    edad: `43`,
    profesion: `Abogada`,
    universidad: `Universidad de Talca`,
    filiacion: `Independiente`,
    cupo: `RN, ExPDG, Amarillos, PCC e independientes - Cámara`,
    posgrado: `Magíster en derecho de la Pontificia Universidad Católica de Chile, magíster en investigación jurídica de la Universidad de los Andes y doctora en derecho de la Universidad de los Andes`,
    cargoactual: `Académica de la Universidad de los Andes`,
    cargosanteriores: ``,
    foto: `https://www.latercera.com/resizer/FbdP5X74wc9skB5ay6j8UDSJEGg=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/5WRWCGAP3FFLLLB7YQ3TLWDGKY.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Flavio`,
    apellido: `Quezada`,
    edad: `35`,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: `PS`,
    cupo: `PS - Cámara`,
    posgrado: `Magíster en derecho de la Universidad de Chile, magíster en derecho público de la Universidad de Bordeaux y doctorando en derecho de la Universidad de Barcelona`,
    cargoactual: `Académico de la Universidad de Valparaíso`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/W73kvpXpr8QSR-H4iumLQyvxWRs=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/26CNOQQMX5EWNASHRPFS67CHPA.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Verónica`,
    apellido: `Undurraga`,
    edad: `55`,
    profesion: `Abogada`,
    universidad: `Universidad de Chile`,
    filiacion: `Independiente`,
    cupo: `PPD - Cámara`,
    posgrado: `Máster en derecho de la Universidad de Columbia y doctora en derecho de la Universidad de Chile`,
    cargoactual: `Académica de la Universidad Adolfo Ibáñez`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/roCJBGZQt6Db75FMVnf54Sf52Mg=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/CBMPFGXTYBBCJD3KXN7SB2ZCIQ.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Domingo`,
    apellido: `Lovera`,
    edad: `45`,
    profesion: `Abogado`,
    universidad: `Universidad Diego Portales`,
    filiacion: `RD`,
    cupo: `RD - Cámara`,
    posgrado: `Máster en derecho de la Universidad de Columbia y doctor en derecho de la Universidad de York`,
    cargoactual: `Codirector del Programa de Derecho Público y académico de la Universidad Diego Portales`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/0X9NSy02DbeZmi815uTSU8HEUwM=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/L4UONLKQPZBOXPSDGOK2CAW37E.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Antonia`,
    apellido: `Rivas`,
    edad: `40`,
    profesion: `Abogada`,
    universidad: `Universidad Diego Portales`,
    filiacion: `CS`,
    cupo: `CS - Cámara`,
    posgrado: `Doctora en Antropología de la Universidad de California, Berkeley`,
    cargoactual: `Jefa de la Unidad de Investigación y Coordinación del Ministerio de Justicia`,
    cargosanteriores: `Exasesora de la exconvencional Tiare Aguilera`,
    foto: `https://www.latercera.com/resizer/zYNe33M2pf3-rt0MpFFpoBfCgP0=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/HFPI6JZUVFD2XPZZ3ISDCQFBMU.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Alexis`,
    apellido: `Cortés`,
    edad: `39`,
    profesion: `Sociólogo`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `PC`,
    cupo: `PC - Cámara`,
    posgrado: `Máster y doctor en sociología del Instituto de Estudios Sociales y Políticos de la Universidad del Estado de Rio de Janeiro`,
    cargoactual: `Académico de la Universidad Alberto Hurtado`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/INJtlRvk23ZRvlV6B7K07AYora4=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/O7RVXGORBVFRPP7FLPMWYF6OJ4.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Paz`,
    apellido: `Anastasiadis`,
    edad: `40`,
    profesion: `Abogada`,
    universidad: `Universidad Adolfo Ibáñez (sede Viña del Mar)`,
    filiacion: `DC`,
    cupo: `DC - Cámara`,
    posgrado: `Magíster (c) de cultura jurídica de la Universitat de Girona`,
    cargoactual: `Asesora legislativa de la bancada de diputados DC`,
    cargosanteriores: `Exseremi de Justicia de la Región de Valparaíso`,
    foto: `https://www.latercera.com/resizer/erloMH3BSaGrwW8tM3eGokZHXQw=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/62LLLW4EHVDMDNQGNKLSUTVWKM.jpg`,
    origen: `Cámara`,
  },
  {
    nombre: `Héctor`,
    apellido: `Mery`,
    edad: `59`,
    profesion: `Abogado`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `Independiente`,
    cupo: `UDI`,
    posgrado: `-`,
    cargoactual: `Asesor senadora Luz Ebensperger (UDI)`,
    cargosanteriores: `Exjefe de la División Judicial del Ministerio de Justicia y exabogado integrante de las Cortes de Apelaciones de San Miguel y de Santiago`,
    foto: `https://www.latercera.com/resizer/lErjfQ3owiCiQ_Rrs98IwY0pMkk=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/6FDN5277RVFRNO27352F7LD7NY.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Cecilia`,
    apellido: `Flores`,
    edad: `37`,
    profesion: `Abogada`,
    universidad: `Universidad de los Andes`,
    filiacion: `Independiente`,
    cupo: `UDI`,
    posgrado: `Magíster en derecho de la Pontificia Universidad Católica de Chile`,
    cargoactual: `Jefa de Faro de la Universidad del Desarrollo (sede Concepción)`,
    cargosanteriores: `Excoordinadora legislativa del Ministerio del Trabajo y exjefa de gabinete de la subsecretaría de la Segpres`,
    foto: `https://www.latercera.com/resizer/f2hluT-wIQffRWliLKLS8LGwJRc=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/UT75GBEUHFCNRNBIJPTZ76FXQQ.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Victor Manuel`,
    apellido: `Avilés`,
    edad: `52`,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: `RN`,
    cupo: `RN`,
    posgrado: `Magíster en derecho de la Universidad de Chile`,
    cargoactual: `Académico de la Universidad de Chile y socio en Larrain y Asociados Abogados`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/D7DOpeylvSL7juOxEmyPOjCLDY8=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/L5KUD3BGBBBZLBITSHF25R5MJU.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Marisol`,
    apellido: `Peña`,
    edad: `63`,
    profesion: `Abogada`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `Independiente`,
    cupo: `RN`,
    posgrado: `Magíster en Estudios Internacionales de la Universidad de Chile`,
    cargoactual: `Académica del Centro de Justicia Constitucional de la Universidad del Desarrollo`,
    cargosanteriores: `Exministra y expresidenta del Tribunal Constitucional`,
    foto: `https://www.latercera.com/resizer/rQp2OHs0zDjl6fGpy70dRL0CLVM=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/5XEFSZVMJVEFXHYTOXJE5VPRME.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Ana María`,
    apellido: `García`,
    edad: `77`,
    profesion: `Abogada`,
    universidad: `Universidad de Chile`,
    filiacion: `Independiente`,
    cupo: `Evópoli`,
    posgrado: `-`,
    cargoactual: `Académica de la Universidad de Chile`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/KZPyLsktQwVhc2oXdMaP_vViA2I=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/YDXTD4GII5ADTNNYJDBS3R6XDA.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Josefina`,
    apellido: `Soto`,
    edad: `49`,
    profesion: `Abogada`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `Independiente`,
    cupo: `Republicano`,
    posgrado: `-`,
    cargoactual: `Profesora de Diplomado de Derecho Administrativo Económico de la Universidad Católica y encargada del área de fiscalización de Ideas Republicanas`,
    cargosanteriores: `Excoordinadora legal del Ministerio de Hacienda y exjefa de gabinete del Ministerio de Energía`,
    foto: `https://www.latercera.com/resizer/vZHQdAnfrUVMczm2b2ryV7UHfj4=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/VS7AOB4CXJG3VPVQT3QDSOSTUI.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Enrique`,
    apellido: `García`,
    edad: `41`,
    profesion: `Abogado`,
    universidad: `Universidad de los Andes`,
    filiacion: `PDG`,
    cupo: `PDG`,
    posgrado: `Magíster en derecho de la Universidad de Los Andes`,
    cargoactual: `Socio en Corral y García Abogados`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/3TATbKQeaXkcguowdxOUv1gIRmk=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/6YDRK6HHRJCK5JCDEZGJ6QQWBU.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Juan Carlos`,
    apellido: `Ferrada`,
    edad: `54`,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: `Independiente`,
    cupo: `PS`,
    posgrado: `Doctor en derecho de la Universidad Carlos III de Madrid`,
    cargoactual: `Académico de la Universidad de Valparaíso y abogado integrante de la Corte de Apelaciones de Valparaíso`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/gT7EJPpbAgDuZ4sib2oD8cTBSc8=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/U6544UUNFJF77CIQY2QTHYUCJM.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Estefania`,
    apellido: `Esparza`,
    edad: `39`,
    profesion: `Abogada`,
    universidad: `Universidad Católica De Temuco`,
    filiacion: `PR`,
    cupo: `PR`,
    posgrado: `Doctora en derecho constitucional de la Universidad de Castilla-La Mancha`,
    cargoactual: `Académica del Departamento de Ciencias Jurídicas de la Universidad de La Frontera`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/b628qvR-Xl0aQf2HL0I8gX6YR20=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/3VFNP3FU5NHOBFY35MLZWAGUVE.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Claudio`,
    apellido: `Grossman`,
    edad: `75`,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: `Independiente`,
    cupo: `PPD`,
    posgrado: `Doctor en Ciencias del derecho de la Universidad de Amsterdam`,
    cargoactual: `Miembro de la Comisión de Derecho Internacional de la ONU`,
    cargosanteriores: `Agente ante la demanda marítima de Bolivia contra Chile ante la Corte Internacional de Justicia de La Haya`,
    foto: `https://www.latercera.com/resizer/CU7WI3AsXuIuW9waS83fpFtqt0U=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/LBJITQIVBBA47CAGDU7MDK6LOA.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Julia`,
    apellido: `Urquieta`,
    edad: `65`,
    profesion: `Abogada`,
    universidad: `Universidad de Chile`,
    filiacion: `PC`,
    cupo: `PC`,
    posgrado: `-`,
    cargoactual: `-`,
    cargosanteriores: `Exconcejal y exsubsecretaria de Previsión Social`,
    foto: `https://www.latercera.com/resizer/XfYAp4D63JYvF462ULTYhfth-c0=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/BUB6DAKM4BDTRGJQAPFY4UPPIQ.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Marcos`,
    apellido: `Contreras`,
    edad: `39`,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: `AH`,
    cupo: `FA`,
    posgrado: `Magíster en derecho penal de la Universidad de Chile, magíster en derecho alemán de la Rinische Friedrich-Wilhelms-Universität Bonn, candidato a doctor en derecho de la Universidad de Chile`,
    cargoactual: `Profesor derecho penal en la Universidad de Santiago, profesor invitado Universidad Adolfo Ibáñez y socio de Bascuñán, Barra, Awad, Contreras, Schürmann Abogados`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/9r7s1bqcebA-qHSmZMICljxXaQQ=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/7BIM5BXLRRGGHNDKWABKG4DVKM.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Tomás`,
    apellido: `Jordán`,
    edad: `46`,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: `DC`,
    cupo: `DC`,
    posgrado: `Magíster y diploma en derecho público de la Universidad Autónoma de Barcelona y magíster en Ciencia Política de la Universidad de Chile`,
    cargoactual: `Académico de la Universidad Alberto Hurtado y socio de Álvarez, Jordán Abogados`,
    cargosanteriores: `Exasesor de la Segpres`,
    foto: `https://www.latercera.com/resizer/6ZCgM5XC0ZzHla1-CVV7B05ynKo=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/2RYW542RYRA7HJUNMGMVEEQEKI.jpg`,
    origen: `Comité`,
  },
  {
    nombre: `Viviana`,
    apellido: `Ponce de León`,
    edad: `38`,
    profesion: `Abogada`,
    universidad: `Universidad Católica del Norte`,
    filiacion: `Independiente`,
    cupo: `FA`,
    posgrado: `Doctora en derecho de la Pontificia Universidad de Valparaíso`,
    cargoactual: `Académica del Instituto de Ciencias Jurídicas de la Universidad Austral`,
    cargosanteriores: `-`,
    foto: `https://www.latercera.com/resizer/q2OvfDmGozkLGdJ07U4ZQPnDyJ8=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/DEZB2HJE4VEZBNOT6XWHIUV6CQ.jpg`,
    origen: `Comité`,
  },
]

export default fichas
