const fichas = [
  {
    nombre: `Sebastián`,
    apellido: `Soto`,
    edad: `46`,
    profesion: `Abogado`,
    universidad: `Pontificia Universidad Católica`,
    filiacion: `Independiente`,
    cupo: `Evópoli`,
    posgrado: `Máster en Derecho de la Universidad de Columbia y Doctor en Derecho de la Universidad de Chile`,
    cargoactual: `-Director del Departamento de Derecho Público de la UC -Profesor de Derecho Constitucional de la UC -Consejero del Consejo de Defensa del Estado (CDE)`,
    cargosanteriores: `-Jefe de la División Jurídico Legislativa de la Segpres (2010-2014) -Formó parte de la mesa técnica del Acuerdo por la Paz para el primer proceso constituyente (2019)`,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Bettina`,
    apellido: `Horst`,
    edad: `52`,
    profesion: `Economista`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `UDI`,
    cupo: ``,
    posgrado: `Máster en economía con mención en políticas públicas en la Universidad Católica`,
    cargoactual: `Directora ejecutiva de Libertad y Desarrollo y Consejera del sistema de Alta Dirección Pública`,
    cargosanteriores: `-Economista del Banco Central de Chile (1995-2000) -Senior Fellow en Atlas Economic Research Foundation en Washington DC (2010-2013) y miembro del Consejo Regional de la Región Metropolitana en Chile (2005-2008) -Fue jefa del Área Monetaria del Departamento de Estudios del Banco Central en Chile -Integrante del Consejo Alta Dirección Pública (2018-2022) -Subdirectora de Políticas Públicas de Libertad y Desarrollo -Directora ejecutiva de Libertad y Desarrollo y Consejera del sistema de Alta Dirección Pública -Presidenta de la mesa directiva de la Red Liberal de América Latina (RELIAL) desde octubre de 2022`,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Hernán`,
    apellido: `Larraín`,
    edad: `75`,
    profesion: `Abogado`,
    universidad: `Universidad Católica`,
    filiacion: `UDI`,
    cupo: ``,
    posgrado: `Máster en Derecho de la London School of Economics (LSE) de Inglaterra`,
    cargoactual: ``,
    cargosanteriores: `-Ministro de Justicia del segundo gobierno de Sebastián Piñera (2018-2022) -Senador por la Región del Maule (1994-2018 por tres periodos consecutivos) -Político de la UDI a partir de 1991 -Presidente de UDI (2006-2008 y 2015-2017)`,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Teodoro`,
    apellido: `Ribera`,
    edad: `64`,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: `RN`,
    cupo: ``,
    posgrado: `Doctor en Derecho Constitucional de la Universidad Julius Maximilians de Wurzburgo, Alemania`,
    cargoactual: ``,
    cargosanteriores: `-diputado por el exdistrito 51 durante dos periodos consecutivos -director de Televisión Nacional de Chile (TVN) -abogado integrante del Tribunal Constitucional de Chile (2006 y 2009) -ministro de Justicia en el primer gobierno de Piñera (2011-2012) -canciller en el segundo gobierno de Piñera -Rector de la Universidad Autónoma`,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Katherine`,
    apellido: `Martorell`,
    edad: `41`,
    profesion: `Abogada`,
    universidad: `Universidad Central`,
    filiacion: `RN`,
    cupo: `RN`,
    posgrado: `Magister en derecho con mención en derecho regulatoria de la Universidad de Chile`,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Jaime`,
    apellido: `Arancibia`,
    edad: `55`,
    profesion: `Abogado`,
    universidad: `Pontificia Universidad Católica de Chile`,
    filiacion: `Independiente`,
    cupo: `RN`,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Gabriel`,
    apellido: `Osorio`,
    edad: `39`,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: ``,
    cupo: ``,
    posgrado: `Magíster en Derecho con mención en Derecho Público de la Universidad de Chile`,
    cargoactual: `Profesor de Derecho Administrativo en la Universidad Andrés Bello y de Derecho Electoral de la Universidad Central`,
    cargosanteriores: `abogado de la División Jurídica de la Segpres y de Interior durante el segundo gobierno de Michelle Bachelet -Formó parte de la mesa técnica del Acuerdo por la Paz para el primer proceso constituyente (2019) y del equipo de redactores del Acuerdo por Chile`,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Catalina`,
    apellido: `Lagos`,
    edad: `39`,
    profesion: `Abogada`,
    universidad: `Universidad Diego Portales`,
    filiacion: ``,
    cupo: ``,
    posgrado: `Magíster en Derecho, con mención en Derecho Público, de la Universidad de Chile`,
    cargoactual: `-Profesora del Departamento de Derecho Público de la UAH y asesora en el Ministerio del Interior`,
    cargosanteriores: `abogada litigante del Programa de Derechos Humanos del Ministerio del Interior, luego pasó a ser secretaria ejecutiva -asesora legislativa y jefa de Relaciones Internacionales en el Ministerio de la Mujer`,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Leslie`,
    apellido: `Sánchez`,
    edad: ``,
    profesion: ``,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Alejandra`,
    apellido: `Krauss`,
    edad: ``,
    profesion: ``,
    universidad: ``,
    filiacion: `DC`,
    cupo: `DC`,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Magaly`,
    apellido: `Fuenzalida`,
    edad: `55`,
    profesion: `Periodista`,
    universidad: `Universidad de Chile`,
    filiacion: ``,
    cupo: ``,
    posgrado: `posgrado en ciencias políticas en la U. de Chile`,
    cargoactual: `Presidenta del Partido Federación Regionalista Verde Social`,
    cargosanteriores: `-Es una de las fundadoras del partido -Candidata a Constituyente por el distrito 4 (Atacama) por la FRVS dentro del pacto Apruebo Dignidad`,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Francisco`,
    apellido: `Soto`,
    edad: ``,
    profesion: ``,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Senado`,
  },
  {
    nombre: `Natalia`,
    apellido: `González`,
    edad: `45`,
    profesion: `Abogada`,
    universidad: `Universidad Católica`,
    filiacion: ``,
    cupo: ``,
    posgrado: `Máster en Derecho (LLM) de la Universidad de Chicago`,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Máximo`,
    apellido: `Pavez`,
    edad: `39`,
    profesion: `Abogado`,
    universidad: `Uiversidad Católica`,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: `Vicepresidente de la UDI y profesor de la UC de los cursos:-Derecho Político
-Instituciones del Estado de Derecho Chileno
-Derechos Fundamentales y Derechos Humanos
-Clínica Jurídica I`,
    cargosanteriores: `-concejal por la Municipalidad de Conchalí (2012-2016) -estuvo a cargo del programa legislativo de la Fundación Jaime Guzmán -subsecretario de Segpres durante el segundo gobierno de Piñera - fue parte de la comisión a cargo de redactar el Acuerdo por Chile y la reforma constitucional para habilitar el segundo proceso constituyente`,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Catalina`,
    apellido: `Salem`,
    edad: `36`,
    profesion: `Abogada`,
    universidad: `Universidad Católica`,
    filiacion: ``,
    cupo: ``,
    posgrado: `Magíster en Derecho con mención en Derecho Constitucional de la Universidad Católica`,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Juan José`,
    apellido: `Ossa`,
    edad: `43`,
    profesion: `Abogado`,
    universidad: `Universidad Católica`,
    filiacion: ``,
    cupo: ``,
    posgrado: `Máster en Leyes de la London School of Economics (LSE) de Inglaterra`,
    cargoactual: `director del Centro de Políticas Públicas de la Universidad San Sebastián`,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Carlos`,
    apellido: `Frontaura`,
    edad: `58`,
    profesion: `Abogado`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Marcela`,
    apellido: `Peredo`,
    edad: ``,
    profesion: `Abogada`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Flavio`,
    apellido: `Quezada`,
    edad: `35`,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Verónica`,
    apellido: `Undurraga`,
    edad: ``,
    profesion: `Abogada`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Domingo`,
    apellido: `Lovera`,
    edad: `46`,
    profesion: `Abogado`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Antonia`,
    apellido: `Rivas`,
    edad: ``,
    profesion: `Abogada`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Alexis`,
    apellido: `Cortés`,
    edad: ``,
    profesion: `Sociólogo`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Paz`,
    apellido: `Anastasiadis`,
    edad: `40`,
    profesion: `Abogada`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Cámara`,
  },
  {
    nombre: `Héctor`,
    apellido: `Mery`,
    edad: ``,
    profesion: `Abogado`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Cecilia`,
    apellido: `Flores`,
    edad: ``,
    profesion: ``,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Victor Manuel`,
    apellido: `Avilés`,
    edad: ``,
    profesion: `Abogado`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Marisol`,
    apellido: `Peña`,
    edad: ``,
    profesion: `Abogada`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Ana María`,
    apellido: `García`,
    edad: ``,
    profesion: ``,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Josefina`,
    apellido: `Soto`,
    edad: ``,
    profesion: ``,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Enrique`,
    apellido: `García`,
    edad: ``,
    profesion: `Abogado`,
    universidad: `Universidad de los Andes`,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Juan Carlos`,
    apellido: `Ferrada`,
    edad: ``,
    profesion: ``,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Estefania`,
    apellido: `Esparza`,
    edad: ``,
    profesion: ``,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Claudio`,
    apellido: `Grossman`,
    edad: ``,
    profesion: `Abogado`,
    universidad: `Universidad de Chile`,
    filiacion: `Independiente`,
    cupo: `PPD`,
    posgrado: `Doctor en Ciencias del derecho de la Universidad de Amsterdam`,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Julia`,
    apellido: `Urquieta`,
    edad: `65`,
    profesion: ``,
    universidad: ``,
    filiacion: `PC`,
    cupo: `PC`,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Marcos`,
    apellido: `Contreras`,
    edad: ``,
    profesion: ``,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Tomás`,
    apellido: `Jordán`,
    edad: `46`,
    profesion: `Abogado`,
    universidad: ``,
    filiacion: `DC`,
    cupo: `DC`,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
  {
    nombre: `Viviana`,
    apellido: `Ponce de León`,
    edad: ``,
    profesion: `Abogada`,
    universidad: ``,
    filiacion: ``,
    cupo: ``,
    posgrado: ``,
    cargoactual: ``,
    cargosanteriores: ``,
    foto: ``,
    origen: `Comité`,
  },
]

export default fichas
