/* Generated by ai2react v0.102.0 - 2021-12-20 21:23 */
/* ai file: FichaPersonal.ai */

import { makeAi2React } from './src'
const img0 =
  'https://especiales.latercera.com/boric-presidente-assets/v2/FichaPersonal-small.jpg'
const img1 =
  'https://especiales.latercera.com/boric-presidente-assets/v2/FichaPersonal-large.jpg'

const styles = `
  #g-FichaPersonal-box ,
  #g-FichaPersonal-box .g-artboard {
    margin:0 auto;
  }
  #g-FichaPersonal-box p {
    margin:0;
  }
  #g-FichaPersonal-box .g-aiAbs {
    position:absolute;
  }
  #g-FichaPersonal-box .g-aiImg {
    position:absolute;
    top:0;
    display:block;
    width:100% !important;
  }
  #g-FichaPersonal-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-FichaPersonal-box .g-aiPointText p { white-space: nowrap; }
  #g-FichaPersonal-small {
    position:relative;
    overflow:hidden;
  }
  #g-FichaPersonal-small p {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:30px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:25px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-FichaPersonal-small .g-pstyle0 {
    height:30px;
  }
  #g-FichaPersonal-small .g-pstyle1 {
    line-height:29px;
    height:29px;
    font-size:24px;
  }
  #g-FichaPersonal-small .g-pstyle2 {
    line-height:32px;
    height:32px;
    font-size:26px;
  }
  #g-FichaPersonal-small .g-cstyle0 {
    letter-spacing:-0.016em;
  }
  #g-FichaPersonal-small .g-cstyle1 {
    letter-spacing:-0.019em;
  }
  #g-FichaPersonal-small .g-cstyle2 {
    letter-spacing:-0.023em;
  }
  #g-FichaPersonal-small .g-cstyle3 {
    letter-spacing:-0.015em;
  }
  #g-FichaPersonal-small .g-cstyle4 {
    letter-spacing:-0.018em;
  }
  #g-FichaPersonal-small .g-cstyle5 {
    letter-spacing:-0.025em;
  }
  #g-FichaPersonal-small .g-cstyle6 {
    letter-spacing:-0.014em;
  }
  #g-FichaPersonal-small .g-cstyle7 {
    letter-spacing:-0.008em;
  }
  #g-FichaPersonal-small .g-cstyle8 {
    letter-spacing:-0.005em;
  }
  #g-FichaPersonal-small .g-cstyle9 {
    letter-spacing:0.005em;
  }
  #g-FichaPersonal-small .g-cstyle10 {
    letter-spacing:-0.043em;
  }
  #g-FichaPersonal-small .g-cstyle11 {
    letter-spacing:-0.022em;
  }
  #g-FichaPersonal-small .g-cstyle12 {
    letter-spacing:-0.013em;
  }
  #g-FichaPersonal-small .g-cstyle13 {
    letter-spacing:-0.017em;
  }
  #g-FichaPersonal-small .g-cstyle14 {
    letter-spacing:0.01em;
  }
  #g-FichaPersonal-small .g-cstyle15 {
    letter-spacing:-0.038em;
  }
  #g-FichaPersonal-small .g-cstyle16 {
    letter-spacing:-0.063em;
  }
  #g-FichaPersonal-small .g-cstyle17 {
    letter-spacing:-0.02em;
  }
  #g-FichaPersonal-small .g-cstyle18 {
    letter-spacing:-0.006em;
  }
  #g-FichaPersonal-small .g-cstyle19 {
    letter-spacing:-0.009em;
  }
  #g-FichaPersonal-small .g-cstyle20 {
    letter-spacing:-0.011em;
  }
  #g-FichaPersonal-small .g-cstyle21 {
    letter-spacing:0.004em;
  }
  #g-FichaPersonal-small .g-cstyle22 {
    letter-spacing:-0.054em;
  }
  #g-FichaPersonal-small .g-cstyle23 {
    letter-spacing:-0.004em;
  }
  #g-FichaPersonal-small .g-cstyle24 {
    letter-spacing:-0.039em;
  }
  #g-FichaPersonal-small .g-cstyle25 {
    letter-spacing:-0.032em;
  }
  #g-FichaPersonal-small .g-cstyle26 {
    letter-spacing:-0.007em;
  }
  #g-FichaPersonal-small .g-cstyle27 {
    letter-spacing:-0.06em;
  }
  #g-FichaPersonal-small .g-cstyle28 {
    letter-spacing:0.006em;
  }
  #g-FichaPersonal-small .g-cstyle29 {
    letter-spacing:-0.047em;
  }
  #g-FichaPersonal-large {
    position:relative;
    overflow:hidden;
  }
  #g-FichaPersonal-large p {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:30px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:25px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-FichaPersonal-large .g-pstyle0 {
    line-height:38px;
    height:38px;
    font-size:32px;
  }
  #g-FichaPersonal-large .g-pstyle1 {
    height:30px;
  }
  #g-FichaPersonal-large .g-pstyle2 {
    line-height:29px;
    height:29px;
    font-size:24px;
  }
  #g-FichaPersonal-large .g-pstyle3 {
    line-height:32px;
    height:32px;
    font-size:26px;
  }
  #g-FichaPersonal-large .g-cstyle0 {
    letter-spacing:-0.016em;
  }
  #g-FichaPersonal-large .g-cstyle1 {
    letter-spacing:-0.023em;
  }
  #g-FichaPersonal-large .g-cstyle2 {
    letter-spacing:-0.015em;
  }
  #g-FichaPersonal-large .g-cstyle3 {
    letter-spacing:-0.019em;
  }
  #g-FichaPersonal-large .g-cstyle4 {
    letter-spacing:-0.018em;
  }
  #g-FichaPersonal-large .g-cstyle5 {
    letter-spacing:-0.025em;
  }
  #g-FichaPersonal-large .g-cstyle6 {
    letter-spacing:-0.014em;
  }
  #g-FichaPersonal-large .g-cstyle7 {
    letter-spacing:-0.043em;
  }
  #g-FichaPersonal-large .g-cstyle8 {
    letter-spacing:-0.022em;
  }
  #g-FichaPersonal-large .g-cstyle9 {
    letter-spacing:-0.013em;
  }
  #g-FichaPersonal-large .g-cstyle10 {
    letter-spacing:-0.005em;
  }
  #g-FichaPersonal-large .g-cstyle11 {
    letter-spacing:-0.017em;
  }
  #g-FichaPersonal-large .g-cstyle12 {
    letter-spacing:-0.021em;
  }
  #g-FichaPersonal-large .g-cstyle13 {
    letter-spacing:0.01em;
  }
  #g-FichaPersonal-large .g-cstyle14 {
    letter-spacing:-0.063em;
  }
  #g-FichaPersonal-large .g-cstyle15 {
    letter-spacing:-0.02em;
  }
  #g-FichaPersonal-large .g-cstyle16 {
    letter-spacing:-0.038em;
  }
  #g-FichaPersonal-large .g-cstyle17 {
    letter-spacing:-0.011em;
  }
  #g-FichaPersonal-large .g-cstyle18 {
    letter-spacing:0.004em;
  }
  #g-FichaPersonal-large .g-cstyle19 {
    letter-spacing:-0.006em;
  }
  #g-FichaPersonal-large .g-cstyle20 {
    letter-spacing:-0.009em;
  }
  #g-FichaPersonal-large .g-cstyle21 {
    letter-spacing:-0.008em;
  }
  #g-FichaPersonal-large .g-cstyle22 {
    letter-spacing:-0.004em;
  }
  #g-FichaPersonal-large .g-cstyle23 {
    letter-spacing:0.005em;
  }
  #g-FichaPersonal-large .g-cstyle24 {
    letter-spacing:-0.054em;
  }
  #g-FichaPersonal-large .g-cstyle25 {
    letter-spacing:-0.007em;
  }
  #g-FichaPersonal-large .g-cstyle26 {
    letter-spacing:-0.06em;
  }
  #g-FichaPersonal-large .g-cstyle27 {
    letter-spacing:0.006em;
  }
  #g-FichaPersonal-large .g-cstyle28 {
    letter-spacing:-0.039em;
  }
  #g-FichaPersonal-large .g-cstyle29 {
    letter-spacing:-0.032em;
  }
  #g-FichaPersonal-large .g-cstyle30 {
    letter-spacing:-0.047em;
  }

`

const html = props => `
<div id="g-FichaPersonal-box" class="ai2html">


  <!-- Artboard: small -->
  <div id="g-FichaPersonal-small" class="g-artboard" style="max-width: 360px;max-height: 2745px" data-aspect-ratio="0.131" data-min-width="0" data-max-width="1279">
<div style="padding: 0 0 762.5% 0;"></div>
    <img id="g-FichaPersonal-small-img" class="g-aiImg" alt="" src="${img0}"/>
    <div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:1.6304%;margin-top:-16.8px;left:4.598%;width:212px;">
      <p class="g-pstyle0">FICHA PERSONAL</p>
    </div>
    <div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:4.9455%;margin-top:-16.8px;left:23.964%;width:244px;">
      <p class="g-pstyle0">NOMBRE COMPLE<span class="g-cstyle0">T</span>O</p>
    </div>
    <div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:6.1269%;margin-top:-16.2px;left:23.964%;width:205px;">
      <p class="g-pstyle1">Gabriel Boric <span class="g-cstyle1">F</span>ont</p>
    </div>
    <div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.1514%;margin-top:-16.8px;left:23.964%;width:272px;">
      <p class="g-pstyle0">FECHA DE N<span class="g-cstyle2">A</span>CIMIEN<span class="g-cstyle3">T</span>O</p>
    </div>
    <div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.2963%;margin-top:-16.2px;left:23.964%;width:254px;">
      <p class="g-pstyle1"><span class="g-cstyle4">1</span>1 de <span class="g-cstyle5">f</span>ebre<span class="g-cstyle1">r</span>o de <span class="g-cstyle6">1</span>986</p>
    </div>
    <div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:11.4665%;margin-top:-16.8px;left:23.964%;width:83px;">
      <p class="g-pstyle0">E<span class="g-cstyle5">D</span>AD</p>
    </div>
    <div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:12.6479%;margin-top:-16.2px;left:23.964%;width:106px;">
      <p class="g-pstyle1">35 años</p>
    </div>
    <div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:14.4744%;margin-top:-17.3px;left:23.964%;width:148px;">
      <p class="g-pstyle0">P<span class="g-cstyle7">R</span>OFESIÓN</p>
    </div>
    <div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:15.6716%;margin-top:-16.2px;left:23.964%;width:272px;">
      <p class="g-pstyle1">Egresado de Derecho de</p>
    </div>
    <div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.8373%;margin-top:-16.2px;left:23.964%;width:255px;">
      <p class="g-pstyle1">la <span class="g-cstyle8">U</span>ni<span class="g-cstyle6">v</span>e<span class="g-cstyle9">r</span>sidad de Chile</p>
    </div>
    <div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:18.7837%;margin-top:-18.6px;left:23.964%;width:156px;">
      <p class="g-pstyle2">OCU<span class="g-cstyle10">P</span><span class="g-cstyle11">A</span>CIÓN</p>
    </div>
    <div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.9969%;margin-top:-16.9px;left:23.964%;width:121px;">
      <p class="g-pstyle0">Diputado</p>
    </div>
    <div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.849%;margin-top:-16.8px;left:23.964%;width:111px;">
      <p class="g-pstyle0"><span class="g-cstyle10">P</span>ADRES</p>
    </div>
    <div id="g-ai0-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:23.0304%;margin-top:-16.2px;left:23.964%;width:205px;">
      <p class="g-pstyle1"><span class="g-cstyle12">L</span>uis Boric Sca<span class="g-cstyle8">r</span>pa </p>
    </div>
    <div id="g-ai0-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:24.1962%;margin-top:-16.2px;left:23.964%;width:227px;">
      <p class="g-pstyle1">(75 años, Ingenie<span class="g-cstyle13">r</span>o </p>
    </div>
    <div id="g-ai0-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.3619%;margin-top:-16.2px;left:23.964%;width:114px;">
      <p class="g-pstyle1">Químico)</p>
    </div>
    <div id="g-ai0-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.9284%;margin-top:-16.2px;left:23.964%;width:177px;">
      <p class="g-pstyle1">María Soledad </p>
    </div>
    <div id="g-ai0-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.0942%;margin-top:-16.2px;left:23.964%;width:165px;">
      <p class="g-pstyle1"><span class="g-cstyle1">F</span>ont <span class="g-cstyle14">A</span>guilera </p>
    </div>
    <div id="g-ai0-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.2599%;margin-top:-16.2px;left:23.964%;width:119px;">
      <p class="g-pstyle1">(<span class="g-cstyle15">6</span>1 años)</p>
    </div>
    <div id="g-ai0-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:31.175%;margin-top:-16.8px;left:23.964%;width:149px;">
      <p class="g-pstyle0">HERMANOS</p>
    </div>
    <div id="g-ai0-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:32.3565%;margin-top:-16.2px;left:23.964%;width:198px;">
      <p class="g-pstyle1">Simón Boric <span class="g-cstyle4">F</span>ont</p>
    </div>
    <div id="g-ai0-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.5222%;margin-top:-16.2px;left:23.964%;width:235px;">
      <p class="g-pstyle1">(33 años, <span class="g-cstyle6">P</span>eriodista)</p>
    </div>
    <div id="g-ai0-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.1251%;margin-top:-16.2px;left:23.964%;width:199px;">
      <p class="g-pstyle1"><span class="g-cstyle16">T</span>omás Boric <span class="g-cstyle17">F</span>ont</p>
    </div>
    <div id="g-ai0-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.2909%;margin-top:-16.2px;left:23.964%;width:120px;">
      <p class="g-pstyle1">(29 años)</p>
    </div>
    <div id="g-ai0-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:38.2883%;margin-top:-18px;left:23.9643%;width:109px;">
      <p class="g-pstyle2"><span class="g-cstyle10">P</span>ARE<span class="g-cstyle0">J</span>A</p>
    </div>
    <div id="g-ai0-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.4504%;margin-top:-16.9px;left:23.9643%;width:279px;">
      <p class="g-pstyle0">Irina <span class="g-cstyle18">K</span>aramanos <span class="g-cstyle19">A</span>drian</p>
    </div>
    <div id="g-ai0-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.6162%;margin-top:-16.9px;left:23.9643%;width:254px;">
      <p class="g-pstyle0">32 años, Ant<span class="g-cstyle4">r</span>opóloga</p>
    </div>
    <div id="g-ai0-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.6235%;margin-top:-18px;left:23.9624%;width:288px;">
      <p class="g-pstyle2"><span class="g-cstyle20">L</span>U<span class="g-cstyle21">G</span>AR DE N<span class="g-cstyle11">A</span>CIMIEN<span class="g-cstyle6">T</span>O</p>
    </div>
    <div id="g-ai0-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.822%;margin-top:-16.9px;left:23.9643%;width:168px;">
      <p class="g-pstyle0">Punta Arenas</p>
    </div>
    <div id="g-ai0-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.002%;margin-top:-16.8px;left:23.9643%;width:249px;">
      <p class="g-pstyle0">COLEGIO DE EGRESO</p>
    </div>
    <div id="g-ai0-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.1834%;margin-top:-16.2px;left:23.9643%;width:244px;">
      <p class="g-pstyle1">The British School de </p>
    </div>
    <div id="g-ai0-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:48.3492%;margin-top:-16.2px;left:23.9643%;width:161px;">
      <p class="g-pstyle1">Punta Arenas</p>
    </div>
    <div id="g-ai0-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:51.0024%;margin-top:-18px;left:23.026%;width:167px;">
      <p class="g-pstyle2"><span class="g-cstyle10">P</span><span class="g-cstyle22">A</span>TRIMONIO</p>
    </div>
    <div id="g-ai0-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.3466%;margin-top:-16.9px;left:23.026%;width:201px;">
      <p class="g-pstyle0"><span class="g-cstyle23">U</span>n <span class="g-cstyle13">t</span>erreno en la </p>
    </div>
    <div id="g-ai0-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:53.5123%;margin-top:-16.9px;left:23.026%;width:258px;">
      <p class="g-pstyle0">comuna de Dalcahue </p>
    </div>
    <div id="g-ai0-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:54.6781%;margin-top:-16.9px;left:23.026%;width:242px;">
      <p class="g-pstyle0">con un <span class="g-cstyle11">a</span><span class="g-cstyle19">v</span>alúo <span class="g-cstyle9">f</span>iscal </p>
    </div>
    <div id="g-ai0-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.8439%;margin-top:-16.9px;left:23.026%;width:205px;">
      <p class="g-pstyle0">de $ 12<span class="g-cstyle24">.</span><span class="g-cstyle4">1</span><span class="g-cstyle25">1</span>0.823</p>
    </div>
    <div id="g-ai0-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:57.9932%;margin-top:-16.9px;left:23.026%;width:228px;">
      <p class="g-pstyle0"><span class="g-cstyle23">U</span>na m<span class="g-cstyle26">o</span><span class="g-cstyle3">t</span>o <span class="g-cstyle27">Y</span>amaha </p>
    </div>
    <div id="g-ai0-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:59.159%;margin-top:-16.9px;left:23.026%;width:242px;">
      <p class="g-pstyle0">con un <span class="g-cstyle11">a</span><span class="g-cstyle19">v</span>alúo <span class="g-cstyle9">f</span>iscal </p>
    </div>
    <div id="g-ai0-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:60.3247%;margin-top:-16.9px;left:23.026%;width:172px;">
      <p class="g-pstyle0">de $ 702.<span class="g-cstyle28">4</span>49</p>
    </div>
    <div id="g-ai0-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.6562%;margin-top:-16.9px;left:23.026%;width:228px;">
      <p class="g-pstyle0"><span class="g-cstyle1">F</span>ondos mutuos en </p>
    </div>
    <div id="g-ai0-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:63.822%;margin-top:-16.9px;left:23.026%;width:241px;">
      <p class="g-pstyle0">el Banco Santander </p>
    </div>
    <div id="g-ai0-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.9878%;margin-top:-16.9px;left:23.026%;width:193px;">
      <p class="g-pstyle0">con un <span class="g-cstyle19">v</span>alor de </p>
    </div>
    <div id="g-ai0-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.1535%;margin-top:-16.9px;left:23.026%;width:173px;">
      <p class="g-pstyle0">$ <span class="g-cstyle29">3</span><span class="g-cstyle18">1</span>.223.320</p>
    </div>
  </div>

  <!-- Artboard: large -->
  <div id="g-FichaPersonal-large" class="g-artboard" style="width:1280px; height:1113px;" data-aspect-ratio="1.15" data-min-width="1280">
<div style=""></div>
    <img id="g-FichaPersonal-large-img" class="g-aiImg" alt="" src="${img1}"/>
    <div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:6.1317%;margin-top:-21.2px;left:29.1586%;width:265px;">
      <p class="g-pstyle0">FICHA PERSONAL</p>
    </div>
    <div id="g-ai1-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.0606%;margin-top:-16.8px;left:38.9888%;width:244px;">
      <p class="g-pstyle1">NOMBRE COMPLE<span class="g-cstyle0">T</span>O</p>
    </div>
    <div id="g-ai1-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.0606%;margin-top:-16.8px;left:74.4684%;width:272px;">
      <p class="g-pstyle1">FECHA DE N<span class="g-cstyle1">A</span>CIMIEN<span class="g-cstyle2">T</span>O</p>
    </div>
    <div id="g-ai1-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:18.9744%;margin-top:-16.2px;left:38.9888%;width:205px;">
      <p class="g-pstyle2">Gabriel Boric <span class="g-cstyle3">F</span>ont</p>
    </div>
    <div id="g-ai1-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:18.9744%;margin-top:-16.2px;left:74.4684%;width:254px;">
      <p class="g-pstyle2"><span class="g-cstyle4">1</span>1 de <span class="g-cstyle5">f</span>ebre<span class="g-cstyle3">r</span>o de <span class="g-cstyle6">1</span>986</p>
    </div>
    <div id="g-ai1-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.0208%;margin-top:-18.6px;left:74.4684%;width:156px;">
      <p class="g-pstyle3">OCU<span class="g-cstyle7">P</span><span class="g-cstyle8">A</span>CIÓN</p>
    </div>
    <div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.9438%;margin-top:-16.8px;left:38.9888%;width:83px;">
      <p class="g-pstyle1">E<span class="g-cstyle5">D</span>AD</p>
    </div>
    <div id="g-ai1-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.9231%;margin-top:-16.9px;left:74.4684%;width:121px;">
      <p class="g-pstyle1">Diputado</p>
    </div>
    <div id="g-ai1-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.8576%;margin-top:-16.2px;left:38.9888%;width:106px;">
      <p class="g-pstyle2">35 años</p>
    </div>
    <div id="g-ai1-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.7489%;margin-top:-16.8px;left:74.4684%;width:149px;">
      <p class="g-pstyle1">HERMANOS</p>
    </div>
    <div id="g-ai1-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.7489%;margin-top:-16.8px;left:38.9888%;width:111px;">
      <p class="g-pstyle1"><span class="g-cstyle7">P</span>ADRES</p>
    </div>
    <div id="g-ai1-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.5727%;margin-top:-16.2px;left:74.4684%;width:198px;">
      <p class="g-pstyle2">Simón Boric <span class="g-cstyle4">F</span>ont</p>
    </div>
    <div id="g-ai1-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.5727%;margin-top:-16.2px;left:38.9888%;width:205px;">
      <p class="g-pstyle2"><span class="g-cstyle9">L</span>uis Boric Sca<span class="g-cstyle10">r</span>pa </p>
    </div>
    <div id="g-ai1-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.4478%;margin-top:-16.2px;left:74.4684%;width:235px;">
      <p class="g-pstyle2">(33 años, <span class="g-cstyle6">P</span>eriodista)</p>
    </div>
    <div id="g-ai1-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.4478%;margin-top:-16.2px;left:38.9888%;width:319px;">
      <p class="g-pstyle2">(75 años, Ingenie<span class="g-cstyle11">r</span>o Químico)</p>
    </div>
    <div id="g-ai1-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.491%;margin-top:-16.2px;left:38.9888%;width:319px;">
      <p class="g-pstyle2">María Soledad <span class="g-cstyle12">F</span>ont <span class="g-cstyle13">A</span>guilera </p>
    </div>
    <div id="g-ai1-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.491%;margin-top:-16.2px;left:74.4675%;width:199px;">
      <p class="g-pstyle2"><span class="g-cstyle14">T</span>omás Boric <span class="g-cstyle15">F</span>ont</p>
    </div>
    <div id="g-ai1-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.3661%;margin-top:-16.2px;left:38.9888%;width:119px;">
      <p class="g-pstyle2">(<span class="g-cstyle16">6</span>1 años)</p>
    </div>
    <div id="g-ai1-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.3661%;margin-top:-16.2px;left:74.4675%;width:120px;">
      <p class="g-pstyle2">(29 años)</p>
    </div>
    <div id="g-ai1-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.562%;margin-top:-18px;left:38.9888%;width:109px;">
      <p class="g-pstyle3"><span class="g-cstyle7">P</span>ARE<span class="g-cstyle0">J</span>A</p>
    </div>
    <div id="g-ai1-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.9214%;margin-top:-18px;left:74.4678%;width:288px;">
      <p class="g-pstyle3"><span class="g-cstyle17">L</span>U<span class="g-cstyle18">G</span>AR DE N<span class="g-cstyle8">A</span>CIMIEN<span class="g-cstyle6">T</span>O</p>
    </div>
    <div id="g-ai1-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.428%;margin-top:-16.9px;left:38.9888%;width:279px;">
      <p class="g-pstyle1">Irina <span class="g-cstyle19">K</span>aramanos <span class="g-cstyle20">A</span>drian</p>
    </div>
    <div id="g-ai1-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.8773%;margin-top:-16.9px;left:74.4684%;width:168px;">
      <p class="g-pstyle1">Punta Arenas</p>
    </div>
    <div id="g-ai1-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:58.3031%;margin-top:-16.9px;left:38.9888%;width:254px;">
      <p class="g-pstyle1">32 años, Ant<span class="g-cstyle4">r</span>opóloga</p>
    </div>
    <div id="g-ai1-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.1798%;margin-top:-17.3px;left:39.0321%;width:148px;">
      <p class="g-pstyle1">P<span class="g-cstyle21">R</span>OFESIÓN</p>
    </div>
    <div id="g-ai1-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.1289%;margin-top:-16.8px;left:74.4684%;width:249px;">
      <p class="g-pstyle1">COLEGIO DE EGRESO</p>
    </div>
    <div id="g-ai1-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.0426%;margin-top:-16.2px;left:74.4684%;width:244px;">
      <p class="g-pstyle2">The British School de </p>
    </div>
    <div id="g-ai1-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.1325%;margin-top:-16.2px;left:39.0321%;width:303px;">
      <p class="g-pstyle2">Egresado de Derecho de la </p>
    </div>
    <div id="g-ai1-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.9178%;margin-top:-16.2px;left:74.4684%;width:161px;">
      <p class="g-pstyle2">Punta Arenas</p>
    </div>
    <div id="g-ai1-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.0076%;margin-top:-16.2px;left:39.0321%;width:230px;">
      <p class="g-pstyle2"><span class="g-cstyle22">U</span>ni<span class="g-cstyle6">v</span>e<span class="g-cstyle23">r</span>sidad de Chile</p>
    </div>
    <div id="g-ai1-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.473%;margin-top:-18px;left:39.1021%;width:167px;">
      <p class="g-pstyle3"><span class="g-cstyle7">P</span><span class="g-cstyle24">A</span>TRIMONIO</p>
    </div>
    <div id="g-ai1-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5035%;margin-top:-16.9px;left:39.1013%;width:201px;">
      <p class="g-pstyle1"><span class="g-cstyle22">U</span>n <span class="g-cstyle11">t</span>erreno en la </p>
    </div>
    <div id="g-ai1-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5035%;margin-top:-16.9px;left:60.3555%;width:228px;">
      <p class="g-pstyle1"><span class="g-cstyle22">U</span>na m<span class="g-cstyle25">o</span><span class="g-cstyle2">t</span>o <span class="g-cstyle26">Y</span>amaha </p>
    </div>
    <div id="g-ai1-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.5035%;margin-top:-16.9px;left:80.9303%;width:228px;">
      <p class="g-pstyle1"><span class="g-cstyle3">F</span>ondos mutuos en </p>
    </div>
    <div id="g-ai1-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.3786%;margin-top:-16.9px;left:39.1013%;width:258px;">
      <p class="g-pstyle1">comuna de Dalcahue </p>
    </div>
    <div id="g-ai1-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.3786%;margin-top:-16.9px;left:60.3555%;width:242px;">
      <p class="g-pstyle1">con un <span class="g-cstyle8">a</span><span class="g-cstyle20">v</span>alúo <span class="g-cstyle23">f</span>iscal </p>
    </div>
    <div id="g-ai1-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.3786%;margin-top:-16.9px;left:80.9303%;width:241px;">
      <p class="g-pstyle1">el Banco Santander </p>
    </div>
    <div id="g-ai1-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.2537%;margin-top:-16.9px;left:39.1013%;width:242px;">
      <p class="g-pstyle1">con un <span class="g-cstyle8">a</span><span class="g-cstyle20">v</span>alúo <span class="g-cstyle23">f</span>iscal </p>
    </div>
    <div id="g-ai1-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.2537%;margin-top:-16.9px;left:60.3555%;width:172px;">
      <p class="g-pstyle1">de $ 702.<span class="g-cstyle27">4</span>49</p>
    </div>
    <div id="g-ai1-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.2537%;margin-top:-16.9px;left:80.9303%;width:193px;">
      <p class="g-pstyle1">con un <span class="g-cstyle20">v</span>alor de </p>
    </div>
    <div id="g-ai1-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.1288%;margin-top:-16.9px;left:39.1013%;width:205px;">
      <p class="g-pstyle1">de $ 12<span class="g-cstyle28">.</span><span class="g-cstyle4">1</span><span class="g-cstyle29">1</span>0.823</p>
    </div>
    <div id="g-ai1-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.1288%;margin-top:-16.9px;left:80.9303%;width:173px;">
      <p class="g-pstyle1">$ <span class="g-cstyle30">3</span><span class="g-cstyle19">1</span>.223.320</p>
    </div>
  </div>


</div>
`

const containerId = 'g-FichaPersonal-box'
const namespace = 'g-'
const name = 'FichaPersonal'

export default makeAi2React({ html, styles, containerId, namespace, name })

/* End ai2react - 2021-12-20 21:23 */
