/* Generated by ai2react v0.102.0 - 2021-12-20 22:27 */
/* ai file: HistorialVotaciones.ai */

import { makeAi2React } from './src/'
const img0 =
  'https://especiales.latercera.com/boric-presidente-assets/v2/HistorialVotaciones-small.jpg'
const img1 =
  'https://especiales.latercera.com/boric-presidente-assets/v2/HistorialVotaciones-large.jpg'

const styles = `
  #g-HistorialVotaciones-box ,
  #g-HistorialVotaciones-box .g-artboard {
    margin:0 auto;
  }
  #g-HistorialVotaciones-box p {
    margin:0;
  }
  #g-HistorialVotaciones-box .g-aiAbs {
    position:absolute;
  }
  #g-HistorialVotaciones-box .g-aiImg {
    position:absolute;
    top:0;
    display:block;
    width:100% !important;
  }
  #g-HistorialVotaciones-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-HistorialVotaciones-box .g-aiPointText p { white-space: nowrap; }
  #g-HistorialVotaciones-small {
    position:relative;
    overflow:hidden;
  }
  #g-HistorialVotaciones-small p {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:30px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:25px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-HistorialVotaciones-small .g-pstyle0 {
    height:30px;
  }
  #g-HistorialVotaciones-small .g-pstyle1 {
    line-height:41px;
    height:41px;
    font-size:34px;
  }
  #g-HistorialVotaciones-small .g-pstyle2 {
    line-height:40px;
    height:40px;
    font-size:33px;
  }
  #g-HistorialVotaciones-small .g-pstyle3 {
    line-height:41px;
    height:41px;
    font-size:34px;
    color:rgb(255,255,255);
  }
  #g-HistorialVotaciones-small .g-pstyle4 {
    line-height:40px;
    height:40px;
    font-size:33px;
    color:rgb(255,255,255);
  }
  #g-HistorialVotaciones-small .g-pstyle5 {
    line-height:24px;
    height:24px;
    font-size:20px;
  }
  #g-HistorialVotaciones-small .g-cstyle0 {
    letter-spacing:-0.014em;
  }
  #g-HistorialVotaciones-small .g-cstyle1 {
    letter-spacing:-0.018em;
  }
  #g-HistorialVotaciones-small .g-cstyle2 {
    letter-spacing:-0.012em;
  }
  #g-HistorialVotaciones-small .g-cstyle3 {
    letter-spacing:-0.051em;
  }
  #g-HistorialVotaciones-small .g-cstyle4 {
    letter-spacing:-0.022em;
  }
  #g-HistorialVotaciones-small .g-cstyle5 {
    letter-spacing:-0.043em;
  }
  #g-HistorialVotaciones-small .g-cstyle6 {
    letter-spacing:-0.038em;
  }
  #g-HistorialVotaciones-small .g-cstyle7 {
    letter-spacing:-0.008em;
  }
  #g-HistorialVotaciones-small .g-cstyle8 {
    letter-spacing:-0.004em;
  }
  #g-HistorialVotaciones-small .g-cstyle9 {
    letter-spacing:0.012em;
  }
  #g-HistorialVotaciones-small .g-cstyle10 {
    letter-spacing:-0.035em;
  }
  #g-HistorialVotaciones-small .g-cstyle11 {
    letter-spacing:-0.059em;
  }
  #g-HistorialVotaciones-small .g-cstyle12 {
    letter-spacing:-0.007em;
  }
  #g-HistorialVotaciones-small .g-cstyle13 {
    letter-spacing:-0.015em;
  }
  #g-HistorialVotaciones-small .g-cstyle14 {
    letter-spacing:-0.068em;
  }
  #g-HistorialVotaciones-small .g-cstyle15 {
    letter-spacing:-0.001em;
  }
  #g-HistorialVotaciones-small .g-cstyle16 {
    letter-spacing:0.001em;
  }
  #g-HistorialVotaciones-small .g-cstyle17 {
    letter-spacing:0.022em;
  }
  #g-HistorialVotaciones-small .g-cstyle18 {
    letter-spacing:-0.058em;
  }
  #g-HistorialVotaciones-small .g-cstyle19 {
    letter-spacing:-0.02em;
  }
  #g-HistorialVotaciones-small .g-cstyle20 {
    letter-spacing:-0.027em;
  }
  #g-HistorialVotaciones-small .g-cstyle21 {
    letter-spacing:-0.024em;
  }
  #g-HistorialVotaciones-small .g-cstyle22 {
    letter-spacing:-0.026em;
  }
  #g-HistorialVotaciones-small .g-cstyle23 {
    letter-spacing:-0.085em;
  }
  #g-HistorialVotaciones-small .g-cstyle24 {
    letter-spacing:0.029em;
  }
  #g-HistorialVotaciones-small .g-cstyle25 {
    letter-spacing:0.025em;
  }
  #g-HistorialVotaciones-small .g-cstyle26 {
    letter-spacing:-0.054em;
  }
  #g-HistorialVotaciones-small .g-cstyle27 {
    letter-spacing:-0.037em;
  }
  #g-HistorialVotaciones-small .g-cstyle28 {
    letter-spacing:-0.016em;
  }
  #g-HistorialVotaciones-small .g-cstyle29 {
    letter-spacing:-0.063em;
  }
  #g-HistorialVotaciones-large {
    position:relative;
    overflow:hidden;
  }
  #g-HistorialVotaciones-large p {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:24px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:20px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-HistorialVotaciones-large .g-pstyle0 {
    line-height:38px;
    height:38px;
    font-size:32px;
  }
  #g-HistorialVotaciones-large .g-pstyle1 {
    line-height:30px;
    height:30px;
    font-size:25px;
  }
  #g-HistorialVotaciones-large .g-pstyle2 {
    line-height:29px;
    height:29px;
    font-size:24px;
  }
  #g-HistorialVotaciones-large .g-pstyle3 {
    line-height:30px;
    height:30px;
    font-size:25px;
    color:rgb(255,255,255);
  }
  #g-HistorialVotaciones-large .g-pstyle4 {
    line-height:29px;
    height:29px;
    font-size:24px;
    color:rgb(255,255,255);
  }
  #g-HistorialVotaciones-large .g-pstyle5 {
    height:24px;
  }
  #g-HistorialVotaciones-large .g-cstyle0 {
    letter-spacing:-0.014em;
  }
  #g-HistorialVotaciones-large .g-cstyle1 {
    letter-spacing:-0.02em;
  }
  #g-HistorialVotaciones-large .g-cstyle2 {
    letter-spacing:-0.012em;
  }
  #g-HistorialVotaciones-large .g-cstyle3 {
    letter-spacing:-0.051em;
  }
  #g-HistorialVotaciones-large .g-cstyle4 {
    letter-spacing:-0.022em;
  }
  #g-HistorialVotaciones-large .g-cstyle5 {
    letter-spacing:-0.043em;
  }
  #g-HistorialVotaciones-large .g-cstyle6 {
    letter-spacing:-0.053em;
  }
  #g-HistorialVotaciones-large .g-cstyle7 {
    letter-spacing:-0.06em;
  }
  #g-HistorialVotaciones-large .g-cstyle8 {
    letter-spacing:-0.025em;
  }
  #g-HistorialVotaciones-large .g-cstyle9 {
    letter-spacing:-0.059em;
  }
  #g-HistorialVotaciones-large .g-cstyle10 {
    letter-spacing:-0.038em;
  }
  #g-HistorialVotaciones-large .g-cstyle11 {
    letter-spacing:-0.008em;
  }
  #g-HistorialVotaciones-large .g-cstyle12 {
    letter-spacing:-0.068em;
  }
  #g-HistorialVotaciones-large .g-cstyle13 {
    letter-spacing:-0.015em;
  }
  #g-HistorialVotaciones-large .g-cstyle14 {
    letter-spacing:-0.035em;
  }
  #g-HistorialVotaciones-large .g-cstyle15 {
    letter-spacing:-0.004em;
  }
  #g-HistorialVotaciones-large .g-cstyle16 {
    letter-spacing:0.012em;
  }
  #g-HistorialVotaciones-large .g-cstyle17 {
    letter-spacing:0.022em;
  }
  #g-HistorialVotaciones-large .g-cstyle18 {
    letter-spacing:-0.026em;
  }
  #g-HistorialVotaciones-large .g-cstyle19 {
    letter-spacing:-0.085em;
  }
  #g-HistorialVotaciones-large .g-cstyle20 {
    letter-spacing:-0.007em;
  }
  #g-HistorialVotaciones-large .g-cstyle21 {
    letter-spacing:-0.034em;
  }
  #g-HistorialVotaciones-large .g-cstyle22 {
    letter-spacing:0.025em;
  }
  #g-HistorialVotaciones-large .g-cstyle23 {
    letter-spacing:-0.019em;
  }
  #g-HistorialVotaciones-large .g-cstyle24 {
    letter-spacing:-0.054em;
  }
  #g-HistorialVotaciones-large .g-cstyle25 {
    letter-spacing:-0.037em;
  }
  #g-HistorialVotaciones-large .g-cstyle26 {
    letter-spacing:-0.016em;
  }
  #g-HistorialVotaciones-large .g-cstyle27 {
    letter-spacing:-0.024em;
  }
  #g-HistorialVotaciones-large .g-cstyle28 {
    letter-spacing:-0.064em;
  }

`

const html = props => `
<div id="g-HistorialVotaciones-box" class="ai2html">


  <!-- Artboard: small -->
  <div id="g-HistorialVotaciones-small" class="g-artboard" style="max-width: 360px;max-height: 2445px" data-aspect-ratio="0.147" data-min-width="0" data-max-width="1279">
<div style="padding: 0 0 679.1917% 0;"></div>
    <img id="g-HistorialVotaciones-small-img" class="g-aiImg" alt="" src="${img0}"/>
    <div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:1.8304%;margin-top:-16.8px;left:4.2259%;width:315px;">
      <p class="g-pstyle0">HIS<span class="g-cstyle0">T</span>ORIAL DE <span class="g-cstyle1">V</span><span class="g-cstyle2">O</span><span class="g-cstyle3">T</span><span class="g-cstyle4">A</span>CIONES</p>
    </div>
    <div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:5.225%;margin-top:-16.8px;left:4.2259%;width:228px;">
      <p class="g-pstyle0"><span class="g-cstyle5">P</span>ARLAMEN<span class="g-cstyle3">T</span>ARIAS </p>
    </div>
    <div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:6.4519%;margin-top:-16.8px;left:4.2259%;width:134px;">
      <p class="g-pstyle0">Año 2<span class="g-cstyle6">0</span><span class="g-cstyle7">1</span>3 </p>
    </div>
    <div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:7.6789%;margin-top:-16.8px;left:4.2259%;width:171px;">
      <p class="g-pstyle0">Exdistri<span class="g-cstyle0">t</span>o 60*</p>
    </div>
    <div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.6557%;margin-top:-23.1px;left:10.4726%;width:138px;">
      <p class="g-pstyle1">26<span class="g-cstyle8">,</span><span class="g-cstyle9">1</span>8%</p>
    </div>
    <div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:13.5819%;margin-top:-23.1px;left:32.1078%;width:128px;">
      <p class="g-pstyle1">15.<span class="g-cstyle10">4</span><span class="g-cstyle11">1</span>7</p>
    </div>
    <div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:14.8995%;margin-top:-22.3px;left:36.6149%;width:96px;">
      <p class="g-pstyle2"><span class="g-cstyle0">v</span><span class="g-cstyle12">o</span><span class="g-cstyle13">t</span>os</p>
    </div>
    <div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.8706%;margin-top:-16.8px;left:4.2259%;width:228px;">
      <p class="g-pstyle0"><span class="g-cstyle5">P</span>ARLAMEN<span class="g-cstyle3">T</span>ARIAS </p>
    </div>
    <div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:23.0975%;margin-top:-16.8px;left:4.2259%;width:132px;">
      <p class="g-pstyle0">Año 2<span class="g-cstyle6">0</span><span class="g-cstyle14">1</span>7 </p>
    </div>
    <div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:24.3245%;margin-top:-16.8px;left:4.2259%;width:149px;">
      <p class="g-pstyle0">Distri<span class="g-cstyle0">t</span>o 28*</p>
    </div>
    <div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.3422%;margin-top:-23.1px;left:11.1787%;width:137px;">
      <p class="g-pstyle1">32,82%</p>
    </div>
    <div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.3277%;margin-top:-23.1px;left:30.7488%;width:131px;">
      <p class="g-pstyle1"><span class="g-cstyle9">1</span>8.626</p>
    </div>
    <div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.6453%;margin-top:-22.3px;left:35.7607%;width:96px;">
      <p class="g-pstyle2"><span class="g-cstyle0">v</span><span class="g-cstyle12">o</span><span class="g-cstyle13">t</span>os</p>
    </div>
    <div id="g-ai0-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:38.4753%;margin-top:-16.8px;left:4.2259%;width:153px;">
      <p class="g-pstyle0">PRIM<span class="g-cstyle15">A</span>RIAS </p>
    </div>
    <div id="g-ai0-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.7022%;margin-top:-16.8px;left:4.2259%;width:216px;">
      <p class="g-pstyle0">PRESIDENCIALES </p>
    </div>
    <div id="g-ai0-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.9292%;margin-top:-16.8px;left:4.2259%;width:128px;">
      <p class="g-pstyle0">Año 20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai0-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.1561%;margin-top:-16.8px;left:4.2259%;width:214px;">
      <p class="g-pstyle0">Apruebo Digni<span class="g-cstyle16">d</span>ad</p>
    </div>
    <div id="g-ai0-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.4601%;margin-top:-23.1px;left:12.5245%;width:137px;">
      <p class="g-pstyle1">60,42%</p>
    </div>
    <div id="g-ai0-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.4088%;margin-top:-23.1px;left:24.6814%;width:180px;">
      <p class="g-pstyle1"><span class="g-cstyle17">1</span>.059.060</p>
    </div>
    <div id="g-ai0-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:50.6855%;margin-top:-22.3px;left:36.4899%;width:96px;">
      <p class="g-pstyle2"><span class="g-cstyle0">v</span><span class="g-cstyle12">o</span><span class="g-cstyle13">t</span>os</p>
    </div>
    <div id="g-ai0-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:59.1289%;margin-top:-16.8px;left:4.2259%;width:209px;">
      <p class="g-pstyle0">PRIM<span class="g-cstyle15">E</span>RA VUE<span class="g-cstyle18">L</span><span class="g-cstyle3">T</span>A</p>
    </div>
    <div id="g-ai0-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:60.3558%;margin-top:-16.8px;left:4.2259%;width:182px;">
      <p class="g-pstyle0">PRESIDENCIAL</p>
    </div>
    <div id="g-ai0-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:61.5828%;margin-top:-16.8px;left:4.2259%;width:128px;">
      <p class="g-pstyle0">Año 20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai0-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.0913%;margin-top:-23.1px;left:13.4208%;width:137px;">
      <p class="g-pstyle1">25,82%</p>
    </div>
    <div id="g-ai0-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.0809%;margin-top:-23.1px;left:25.563%;width:179px;">
      <p class="g-pstyle1"><span class="g-cstyle17">1</span>.<span class="g-cstyle19">8</span>15.0<span class="g-cstyle20">2</span>4</p>
    </div>
    <div id="g-ai0-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.3985%;margin-top:-22.3px;left:37.1431%;width:96px;">
      <p class="g-pstyle2"><span class="g-cstyle0">v</span><span class="g-cstyle12">o</span><span class="g-cstyle13">t</span>os</p>
    </div>
    <div id="g-ai0-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.4882%;margin-top:-16.8px;left:4.2259%;width:219px;">
      <p class="g-pstyle0">SEGUN<span class="g-cstyle21">D</span>A VUE<span class="g-cstyle18">L</span><span class="g-cstyle3">T</span>A </p>
    </div>
    <div id="g-ai0-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:76.7152%;margin-top:-16.8px;left:4.2259%;width:182px;">
      <p class="g-pstyle0">PRESIDENCIAL</p>
    </div>
    <div id="g-ai0-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:77.9421%;margin-top:-16.8px;left:4.2259%;width:128px;">
      <p class="g-pstyle0">Año 20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai0-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.0416%;margin-top:-23.1px;left:18.6812%;width:117px;">
      <p class="g-pstyle1">55,9%</p>
    </div>
    <div id="g-ai0-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:85.2357%;margin-top:-23.1px;left:26.612%;width:174px;">
      <p class="g-pstyle3">4.<span class="g-cstyle22">6</span><span class="g-cstyle11">1</span><span class="g-cstyle23">7</span>.385</p>
    </div>
    <div id="g-ai0-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:86.5124%;margin-top:-22.3px;left:37.4987%;width:96px;">
      <p class="g-pstyle4"><span class="g-cstyle0">v</span><span class="g-cstyle12">o</span><span class="g-cstyle13">t</span>os</p>
    </div>
    <div id="g-ai0-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:94.4507%;margin-top:-13.4px;left:4.2259%;width:326px;">
      <p class="g-pstyle5">*Ambos distri<span class="g-cstyle13">t</span>os representan a las </p>
    </div>
    <div id="g-ai0-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.3095%;margin-top:-13.4px;left:4.2259%;width:296px;">
      <p class="g-pstyle5">comunas de Antá<span class="g-cstyle24">r</span>tica, Cabo de </p>
    </div>
    <div id="g-ai0-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.1684%;margin-top:-13.4px;left:4.2259%;width:305px;">
      <p class="g-pstyle5">Hornos, Laguna Blanca, Natales, </p>
    </div>
    <div id="g-ai0-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.0273%;margin-top:-13.4px;left:4.2259%;width:325px;">
      <p class="g-pstyle5"><span class="g-cstyle0">P</span>o<span class="g-cstyle25">r</span><span class="g-cstyle13">v</span>eni<span class="g-cstyle26">r</span>, Prim<span class="g-cstyle4">a</span><span class="g-cstyle13">v</span>era, Punta Arenas, </p>
    </div>
    <div id="g-ai0-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.8861%;margin-top:-13.4px;left:4.2259%;width:323px;">
      <p class="g-pstyle5">Río <span class="g-cstyle27">V</span>e<span class="g-cstyle28">r</span>de, San Gregorio, Timau<span class="g-cstyle21">k</span>el, </p>
    </div>
    <div id="g-ai0-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.745%;margin-top:-13.4px;left:4.2259%;width:159px;">
      <p class="g-pstyle5"><span class="g-cstyle29">T</span>orres del <span class="g-cstyle12">P</span>aine</p>
    </div>
  </div>

  <!-- Artboard: large -->
  <div id="g-HistorialVotaciones-large" class="g-artboard" style="width:1280px; height:601px;" data-aspect-ratio="2.13" data-min-width="1280">
<div style=""></div>
    <img id="g-HistorialVotaciones-large-img" class="g-aiImg" alt="" src="${img1}"/>
    <div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.8579%;margin-top:-21.2px;left:1.9939%;width:397px;">
      <p class="g-pstyle0">HIS<span class="g-cstyle0">T</span>ORIAL DE <span class="g-cstyle1">V</span><span class="g-cstyle2">O</span><span class="g-cstyle3">T</span><span class="g-cstyle4">A</span>CIONES</p>
    </div>
    <div id="g-ai1-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.2504%;margin-top:-16.8px;left:1.958%;width:228px;">
      <p class="g-pstyle1"><span class="g-cstyle5">P</span>ARLAMEN<span class="g-cstyle6">T</span>ARIAS </p>
    </div>
    <div id="g-ai1-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.2504%;margin-top:-16.8px;left:21.5008%;width:228px;">
      <p class="g-pstyle1"><span class="g-cstyle5">P</span>ARLAMEN<span class="g-cstyle6">T</span>ARIAS </p>
    </div>
    <div id="g-ai1-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.2504%;margin-top:-16.8px;left:41.3258%;width:153px;">
      <p class="g-pstyle1">PRIMARIAS </p>
    </div>
    <div id="g-ai1-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.2504%;margin-top:-16.8px;left:61.1269%;width:209px;">
      <p class="g-pstyle1">PRIMERA VUE<span class="g-cstyle7">L</span><span class="g-cstyle3">T</span>A</p>
    </div>
    <div id="g-ai1-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.2504%;margin-top:-16.8px;left:81.1623%;width:219px;">
      <p class="g-pstyle1">SEGUN<span class="g-cstyle8">D</span>A VUE<span class="g-cstyle9">L</span><span class="g-cstyle3">T</span>A </p>
    </div>
    <div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.1472%;margin-top:-16.2px;left:1.958%;width:129px;">
      <p class="g-pstyle2">Año 2<span class="g-cstyle10">0</span><span class="g-cstyle11">1</span>3 </p>
    </div>
    <div id="g-ai1-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.1472%;margin-top:-16.2px;left:21.5008%;width:128px;">
      <p class="g-pstyle2">Año 2<span class="g-cstyle10">0</span><span class="g-cstyle12">1</span>7 </p>
    </div>
    <div id="g-ai1-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.242%;margin-top:-16.8px;left:41.3258%;width:216px;">
      <p class="g-pstyle1">PRESIDENCIALES </p>
    </div>
    <div id="g-ai1-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.242%;margin-top:-16.8px;left:61.1269%;width:182px;">
      <p class="g-pstyle1">PRESIDENCIAL</p>
    </div>
    <div id="g-ai1-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.242%;margin-top:-16.8px;left:81.1623%;width:182px;">
      <p class="g-pstyle1">PRESIDENCIAL</p>
    </div>
    <div id="g-ai1-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.8061%;margin-top:-16.2px;left:1.958%;width:165px;">
      <p class="g-pstyle2">Exdistri<span class="g-cstyle13">t</span>o 60*</p>
    </div>
    <div id="g-ai1-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.8061%;margin-top:-16.2px;left:21.5008%;width:144px;">
      <p class="g-pstyle2">Distri<span class="g-cstyle13">t</span>o 28*</p>
    </div>
    <div id="g-ai1-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.1389%;margin-top:-16.2px;left:41.3258%;width:124px;">
      <p class="g-pstyle2">Año 20<span class="g-cstyle14">2</span>1</p>
    </div>
    <div id="g-ai1-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.1389%;margin-top:-16.2px;left:61.1269%;width:124px;">
      <p class="g-pstyle2">Año 20<span class="g-cstyle14">2</span>1</p>
    </div>
    <div id="g-ai1-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.1389%;margin-top:-16.2px;left:81.1623%;width:124px;">
      <p class="g-pstyle2">Año 20<span class="g-cstyle14">2</span>1</p>
    </div>
    <div id="g-ai1-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.7978%;margin-top:-16.2px;left:41.3258%;width:206px;">
      <p class="g-pstyle2">Apruebo Dignidad</p>
    </div>
    <div id="g-ai1-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.0441%;margin-top:-16.8px;left:2.5639%;width:106px;">
      <p class="g-pstyle1">26<span class="g-cstyle15">,</span><span class="g-cstyle16">1</span>8%</p>
    </div>
    <div id="g-ai1-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.0441%;margin-top:-16.8px;left:22.6088%;width:106px;">
      <p class="g-pstyle1">32,82%</p>
    </div>
    <div id="g-ai1-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.0441%;margin-top:-16.8px;left:42.4037%;width:106px;">
      <p class="g-pstyle1">60,42%</p>
    </div>
    <div id="g-ai1-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.0441%;margin-top:-16.8px;left:62.5893%;width:106px;">
      <p class="g-pstyle1">25,82%</p>
    </div>
    <div id="g-ai1-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.0441%;margin-top:-16.8px;left:83.2906%;width:91px;">
      <p class="g-pstyle1">55,9%</p>
    </div>
    <div id="g-ai1-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.1855%;margin-top:-16.8px;left:45.347%;width:137px;">
      <p class="g-pstyle1"><span class="g-cstyle17">1</span>.059.060</p>
    </div>
    <div id="g-ai1-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.1855%;margin-top:-16.8px;left:65.1878%;width:136px;">
      <p class="g-pstyle1"><span class="g-cstyle17">1</span>.<span class="g-cstyle1">8</span>15.0<span class="g-cstyle18">2</span>4</p>
    </div>
    <div id="g-ai1-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.1855%;margin-top:-16.8px;left:85.0426%;width:132px;">
      <p class="g-pstyle3">4.<span class="g-cstyle18">6</span><span class="g-cstyle9">1</span><span class="g-cstyle19">7</span>.385</p>
    </div>
    <div id="g-ai1-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:68.084%;margin-top:-16.2px;left:47.7637%;width:76px;">
      <p class="g-pstyle2"><span class="g-cstyle0">v</span><span class="g-cstyle20">o</span><span class="g-cstyle13">t</span>os</p>
    </div>
    <div id="g-ai1-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:68.084%;margin-top:-16.2px;left:67.5578%;width:76px;">
      <p class="g-pstyle2"><span class="g-cstyle0">v</span><span class="g-cstyle20">o</span><span class="g-cstyle13">t</span>os</p>
    </div>
    <div id="g-ai1-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:68.084%;margin-top:-16.2px;left:87.2701%;width:76px;">
      <p class="g-pstyle4"><span class="g-cstyle0">v</span><span class="g-cstyle20">o</span><span class="g-cstyle13">t</span>os</p>
    </div>
    <div id="g-ai1-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.3436%;margin-top:-16.8px;left:26.841%;width:102px;">
      <p class="g-pstyle1"><span class="g-cstyle16">1</span>8.626</p>
    </div>
    <div id="g-ai1-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.3436%;margin-top:-16.8px;left:6.9916%;width:99px;">
      <p class="g-pstyle1">15.<span class="g-cstyle21">4</span><span class="g-cstyle9">1</span>7</p>
    </div>
    <div id="g-ai1-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:73.242%;margin-top:-16.2px;left:7.914%;width:76px;">
      <p class="g-pstyle2"><span class="g-cstyle0">v</span><span class="g-cstyle20">o</span><span class="g-cstyle13">t</span>os</p>
    </div>
    <div id="g-ai1-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:73.242%;margin-top:-16.2px;left:27.8667%;width:76px;">
      <p class="g-pstyle2"><span class="g-cstyle0">v</span><span class="g-cstyle20">o</span><span class="g-cstyle13">t</span>os</p>
    </div>
    <div id="g-ai1-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:91.9141%;margin-top:-13.4px;left:2.177%;width:1185px;">
      <p class="g-pstyle5">*Ambos distri<span class="g-cstyle13">t</span>os representan a las comunas de Antá<span class="g-cstyle22">r</span>tica, Cabo de Hornos, Laguna Blanca, Natales, <span class="g-cstyle23">P</span>o<span class="g-cstyle22">r</span><span class="g-cstyle13">v</span>eni<span class="g-cstyle24">r</span>, Prim<span class="g-cstyle4">a</span><span class="g-cstyle13">v</span>era, Punta Arenas, </p>
    </div>
    <div id="g-ai1-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.9075%;margin-top:-13.4px;left:2.177%;width:460px;">
      <p class="g-pstyle5">Río <span class="g-cstyle25">V</span>e<span class="g-cstyle26">r</span>de, San Gregorio, Timau<span class="g-cstyle27">k</span>el, <span class="g-cstyle28">T</span>orres del <span class="g-cstyle20">P</span>aine</p>
    </div>
  </div>


</div>
`

const containerId = 'g-HistorialVotaciones-box'
const namespace = 'g-'
const name = 'HistorialVotaciones'

export default makeAi2React({ html, styles, containerId, namespace, name })

/* End ai2react - 2021-12-20 22:27 */
