/* Generated by ai2react v0.102.0 - 2021-12-20 22:30 */
/* ai file: HistorialPolitico.ai */

import { makeAi2React } from './src/'
const img0 =
  'https://especiales.latercera.com/boric-presidente-assets/v2/HistorialPolitico-large.jpg'
const img1 =
  'https://especiales.latercera.com/boric-presidente-assets/v2/HistorialPolitico-small.jpg'

const styles = `
  #g-HistorialPolitico-box ,
  #g-HistorialPolitico-box .g-artboard {
    margin:0 auto;
  }
  #g-HistorialPolitico-box p {
    margin:0;
  }
  #g-HistorialPolitico-box .g-aiAbs {
    position:absolute;
  }
  #g-HistorialPolitico-box .g-aiImg {
    position:absolute;
    top:0;
    display:block;
    width:100% !important;
  }
  #g-HistorialPolitico-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-HistorialPolitico-box .g-aiPointText p { white-space: nowrap; }
  #g-HistorialPolitico-large {
    position:relative;
    overflow:hidden;
  }
  #g-HistorialPolitico-large p {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:24px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:20px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-HistorialPolitico-large .g-pstyle0 {
    line-height:38px;
    height:38px;
    font-size:32px;
  }
  #g-HistorialPolitico-large .g-pstyle1 {
    line-height:30px;
    height:30px;
    font-size:25px;
  }
  #g-HistorialPolitico-large .g-pstyle2 {
    line-height:28px;
    height:28px;
    font-size:23px;
  }
  #g-HistorialPolitico-large .g-pstyle3 {
    line-height:29px;
    height:29px;
    font-size:24px;
  }
  #g-HistorialPolitico-large .g-pstyle4 {
    height:24px;
  }
  #g-HistorialPolitico-large .g-cstyle0 {
    letter-spacing:-0.014em;
  }
  #g-HistorialPolitico-large .g-cstyle1 {
    letter-spacing:-0.02em;
  }
  #g-HistorialPolitico-large .g-cstyle2 {
    letter-spacing:-0.053em;
  }
  #g-HistorialPolitico-large .g-cstyle3 {
    letter-spacing:-0.038em;
  }
  #g-HistorialPolitico-large .g-cstyle4 {
    letter-spacing:-0.032em;
  }
  #g-HistorialPolitico-large .g-cstyle5 {
    letter-spacing:-0.018em;
  }
  #g-HistorialPolitico-large .g-cstyle6 {
    letter-spacing:-0.037em;
  }
  #g-HistorialPolitico-large .g-cstyle7 {
    letter-spacing:-0.008em;
  }
  #g-HistorialPolitico-large .g-cstyle8 {
    letter-spacing:-0.034em;
  }
  #g-HistorialPolitico-large .g-cstyle9 {
    letter-spacing:-0.068em;
  }
  #g-HistorialPolitico-large .g-cstyle10 {
    letter-spacing:-0.006em;
  }
  #g-HistorialPolitico-large .g-cstyle11 {
    letter-spacing:-0.013em;
  }
  #g-HistorialPolitico-large .g-cstyle12 {
    letter-spacing:-0.009em;
  }
  #g-HistorialPolitico-large .g-cstyle13 {
    letter-spacing:-0.016em;
  }
  #g-HistorialPolitico-large .g-cstyle14 {
    letter-spacing:-0.017em;
  }
  #g-HistorialPolitico-large .g-cstyle15 {
    letter-spacing:-0.022em;
  }
  #g-HistorialPolitico-large .g-cstyle16 {
    letter-spacing:-0.015em;
  }
  #g-HistorialPolitico-large .g-cstyle17 {
    letter-spacing:-0.004em;
  }
  #g-HistorialPolitico-large .g-cstyle18 {
    letter-spacing:-0.007em;
  }
  #g-HistorialPolitico-large .g-cstyle19 {
    letter-spacing:-0.054em;
  }
  #g-HistorialPolitico-large .g-cstyle20 {
    letter-spacing:-0.021em;
  }
  #g-HistorialPolitico-large .g-cstyle21 {
    letter-spacing:0.028em;
  }
  #g-HistorialPolitico-large .g-cstyle22 {
    letter-spacing:0.025em;
  }
  #g-HistorialPolitico-large .g-cstyle23 {
    letter-spacing:-0.04em;
  }
  #g-HistorialPolitico-large .g-cstyle24 {
    letter-spacing:-0.024em;
  }
  #g-HistorialPolitico-large .g-cstyle25 {
    letter-spacing:-0.064em;
  }
  #g-HistorialPolitico-small {
    position:relative;
    overflow:hidden;
  }
  #g-HistorialPolitico-small p {
    font-family:franklin-gothic-urw, helvetica, arial, verdana, sans-serif;;
    font-weight:normal;
    line-height:24px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:20px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-HistorialPolitico-small .g-pstyle0 {
    line-height:30px;
    height:30px;
    font-size:25px;
  }
  #g-HistorialPolitico-small .g-pstyle1 {
    line-height:28px;
    height:28px;
    font-size:23px;
  }
  #g-HistorialPolitico-small .g-pstyle2 {
    line-height:29px;
    height:29px;
    font-size:24px;
  }
  #g-HistorialPolitico-small .g-pstyle3 {
    height:24px;
  }
  #g-HistorialPolitico-small .g-cstyle0 {
    letter-spacing:-0.014em;
  }
  #g-HistorialPolitico-small .g-cstyle1 {
    letter-spacing:-0.053em;
  }
  #g-HistorialPolitico-small .g-cstyle2 {
    letter-spacing:-0.009em;
  }
  #g-HistorialPolitico-small .g-cstyle3 {
    letter-spacing:-0.016em;
  }
  #g-HistorialPolitico-small .g-cstyle4 {
    letter-spacing:-0.038em;
  }
  #g-HistorialPolitico-small .g-cstyle5 {
    letter-spacing:-0.032em;
  }
  #g-HistorialPolitico-small .g-cstyle6 {
    letter-spacing:-0.018em;
  }
  #g-HistorialPolitico-small .g-cstyle7 {
    letter-spacing:-0.037em;
  }
  #g-HistorialPolitico-small .g-cstyle8 {
    letter-spacing:-0.008em;
  }
  #g-HistorialPolitico-small .g-cstyle9 {
    letter-spacing:-0.017em;
  }
  #g-HistorialPolitico-small .g-cstyle10 {
    letter-spacing:-0.034em;
  }
  #g-HistorialPolitico-small .g-cstyle11 {
    letter-spacing:-0.015em;
  }
  #g-HistorialPolitico-small .g-cstyle12 {
    letter-spacing:-0.068em;
  }
  #g-HistorialPolitico-small .g-cstyle13 {
    letter-spacing:-0.006em;
  }
  #g-HistorialPolitico-small .g-cstyle14 {
    letter-spacing:-0.022em;
  }
  #g-HistorialPolitico-small .g-cstyle15 {
    letter-spacing:-0.013em;
  }
  #g-HistorialPolitico-small .g-cstyle16 {
    letter-spacing:-0.02em;
  }
  #g-HistorialPolitico-small .g-cstyle17 {
    letter-spacing:-0.004em;
  }
  #g-HistorialPolitico-small .g-cstyle18 {
    letter-spacing:-0.007em;
  }
  #g-HistorialPolitico-small .g-cstyle19 {
    letter-spacing:-0.054em;
  }
  #g-HistorialPolitico-small .g-cstyle20 {
    letter-spacing:-0.021em;
  }
  #g-HistorialPolitico-small .g-cstyle21 {
    letter-spacing:0.029em;
  }
  #g-HistorialPolitico-small .g-cstyle22 {
    letter-spacing:0.025em;
  }
  #g-HistorialPolitico-small .g-cstyle23 {
    letter-spacing:-0.024em;
  }
  #g-HistorialPolitico-small .g-cstyle24 {
    letter-spacing:-0.063em;
  }

`

const html = props => `
<div id="g-HistorialPolitico-box" class="ai2html">


  <!-- Artboard: large -->
  <div id="g-HistorialPolitico-large" class="g-artboard" style="width:1280px; height:652px;" data-aspect-ratio="1.963" data-min-width="1280">
<div style=""></div>
    <img id="g-HistorialPolitico-large-img" class="g-aiImg" alt="" src="${img0}"/>
    <div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:10.4251%;margin-top:-22px;left:2.0266%;width:305px;">
      <p class="g-pstyle0">HIS<span class="g-cstyle0">T</span>ORIAL POLÍTICO</p>
    </div>
    <div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:10.852%;margin-top:-16.8px;left:58.2466%;width:167px;">
      <p class="g-pstyle1">C<span class="g-cstyle1">O</span>ALICIONES</p>
    </div>
    <div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.4103%;margin-top:-16.8px;left:2.0259%;width:146px;">
      <p class="g-pstyle1">MILI<span class="g-cstyle2">T</span>ANCIA</p>
    </div>
    <div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:2.3782%;width:76px;">
      <p class="g-pstyle2">2008</p>
    </div>
    <div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:9.1417%;width:76px;">
      <p class="g-pstyle2">2009</p>
    </div>
    <div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:15.968%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>0</p>
    </div>
    <div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:22.7171%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle5">1</span>1</p>
    </div>
    <div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:29.4625%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle6">0</span>12</p>
    </div>
    <div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:36.2331%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle7">1</span>3</p>
    </div>
    <div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:43.0164%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>4</p>
    </div>
    <div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:49.7636%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle0">1</span>5</p>
    </div>
    <div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:56.545%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle8">1</span>6</p>
    </div>
    <div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:63.339%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle9">1</span>7</p>
    </div>
    <div id="g-ai0-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:70.0468%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle10">1</span>8</p>
    </div>
    <div id="g-ai0-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:76.8156%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle11">1</span>9</p>
    </div>
    <div id="g-ai0-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:83.5323%;width:76px;">
      <p class="g-pstyle2">2020</p>
    </div>
    <div id="g-ai0-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8304%;margin-top:-15.6px;left:90.3263%;width:75px;">
      <p class="g-pstyle2">20<span class="g-cstyle8">2</span>1</p>
    </div>
    <div id="g-ai0-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.9731%;margin-top:-16.2px;left:3.223%;width:116px;">
      <p class="g-pstyle3">Iz<span class="g-cstyle12">q</span>uie<span class="g-cstyle13">r</span>da</p>
    </div>
    <div id="g-ai0-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.9731%;margin-top:-16.2px;left:57.5924%;width:142px;">
      <p class="g-pstyle3">M<span class="g-cstyle14">o</span>vimien<span class="g-cstyle0">t</span>o</p>
    </div>
    <div id="g-ai0-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.9731%;margin-top:-16.2px;left:77.8406%;width:160px;">
      <p class="g-pstyle3">Co<span class="g-cstyle15">n</span><span class="g-cstyle16">v</span>ergencia</p>
    </div>
    <div id="g-ai0-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.6541%;margin-top:-16.2px;left:3.223%;width:129px;">
      <p class="g-pstyle3"><span class="g-cstyle13">A</span>utónoma</p>
    </div>
    <div id="g-ai0-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.6541%;margin-top:-16.2px;left:57.5924%;width:153px;">
      <p class="g-pstyle3"><span class="g-cstyle13">A</span>u<span class="g-cstyle16">t</span>onomista</p>
    </div>
    <div id="g-ai0-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.6541%;margin-top:-16.2px;left:77.8406%;width:84px;">
      <p class="g-pstyle3">Social</p>
    </div>
    <div id="g-ai0-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.7793%;margin-top:-17.3px;left:2.0265%;width:353px;">
      <p class="g-pstyle1"><span class="g-cstyle17">C</span>A<span class="g-cstyle18">R</span>GOS DE REPRESEN<span class="g-cstyle19">T</span><span class="g-cstyle20">A</span>CIÓN</p>
    </div>
    <div id="g-ai0-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:2.3782%;width:76px;">
      <p class="g-pstyle2">2008</p>
    </div>
    <div id="g-ai0-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:9.1417%;width:76px;">
      <p class="g-pstyle2">2009</p>
    </div>
    <div id="g-ai0-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:15.968%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>0</p>
    </div>
    <div id="g-ai0-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:22.7171%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle5">1</span>1</p>
    </div>
    <div id="g-ai0-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:29.4625%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle6">0</span>12</p>
    </div>
    <div id="g-ai0-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:36.2331%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle7">1</span>3</p>
    </div>
    <div id="g-ai0-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:43.0164%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>4</p>
    </div>
    <div id="g-ai0-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:49.7636%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle0">1</span>5</p>
    </div>
    <div id="g-ai0-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:56.545%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle8">1</span>6</p>
    </div>
    <div id="g-ai0-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:63.339%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle9">1</span>7</p>
    </div>
    <div id="g-ai0-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:70.0468%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle10">1</span>8</p>
    </div>
    <div id="g-ai0-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:76.8156%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle3">0</span><span class="g-cstyle11">1</span>9</p>
    </div>
    <div id="g-ai0-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:83.5323%;width:76px;">
      <p class="g-pstyle2">2020</p>
    </div>
    <div id="g-ai0-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.4194%;margin-top:-15.6px;left:90.3263%;width:75px;">
      <p class="g-pstyle2">20<span class="g-cstyle8">2</span>1</p>
    </div>
    <div id="g-ai0-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:77.0222%;margin-top:-16.2px;left:23.9381%;width:132px;">
      <p class="g-pstyle3">1<span class="g-cstyle5">t</span>e</p>
    </div>
    <div id="g-ai0-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:77.0222%;margin-top:-16.2px;left:44.1356%;width:116px;">
      <p class="g-pstyle3">Diputado</p>
    </div>
    <div id="g-ai0-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:77.0222%;margin-top:-16.2px;left:70.9013%;width:116px;">
      <p class="g-pstyle3">Diputado</p>
    </div>
    <div id="g-ai0-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:77.0222%;margin-top:-16.2px;left:91.32%;width:132px;">
      <p class="g-pstyle3">Presiden<span class="g-cstyle5">t</span>e</p>
    </div>
    <div id="g-ai0-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.7032%;margin-top:-16.2px;left:44.1356%;width:151px;">
      <p class="g-pstyle3">Exdistri<span class="g-cstyle16">t</span>o 60</p>
    </div>
    <div id="g-ai0-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.7032%;margin-top:-16.2px;left:70.9013%;width:144px;">
      <p class="g-pstyle3">Distri<span class="g-cstyle16">t</span>o 28*</p>
    </div>
    <div id="g-ai0-45" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.7032%;margin-top:-16.2px;left:91.32%;width:72px;">
      <p class="g-pstyle3">de la</p>
    </div>
    <div id="g-ai0-46" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.47%;margin-top:-16.2px;left:23.9381%;width:133px;">
      <p class="g-pstyle3">de la FECH</p>
    </div>
    <div id="g-ai0-47" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.3841%;margin-top:-16.2px;left:91.32%;width:130px;">
      <p class="g-pstyle3"><span class="g-cstyle14">R</span>epública </p>
    </div>
    <div id="g-ai0-48" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:88.0651%;margin-top:-16.2px;left:91.32%;width:98px;">
      <p class="g-pstyle3">(elec<span class="g-cstyle16">t</span>o)</p>
    </div>
    <div id="g-ai0-49" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.7061%;margin-top:-13.4px;left:2.0265%;width:846px;">
      <p class="g-pstyle4">*Antiguo distri<span class="g-cstyle13">t</span>o 60, co<span class="g-cstyle12">m</span>pues<span class="g-cstyle13">t</span>o por las comunas de Antá<span class="g-cstyle21">r</span>tica, Cabo de Hornos, Laguna Blanca, </p>
    </div>
    <div id="g-ai0-50" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:94.3871%;margin-top:-13.4px;left:2.0265%;width:838px;">
      <p class="g-pstyle4">Natales, <span class="g-cstyle16">P</span>o<span class="g-cstyle22">r</span><span class="g-cstyle16">v</span>eni<span class="g-cstyle19">r</span>, Prim<span class="g-cstyle15">a</span><span class="g-cstyle16">v</span>era, Punta Arenas, Río <span class="g-cstyle23">V</span>e<span class="g-cstyle13">r</span>de, San Gregorio, Timau<span class="g-cstyle24">k</span>el, <span class="g-cstyle25">T</span>orres del <span class="g-cstyle18">P</span>aine</p>
    </div>
  </div>

  <!-- Artboard: small -->
  <div id="g-HistorialPolitico-small" class="g-artboard" style="max-width: 360px;max-height: 1891px" data-aspect-ratio="0.19" data-min-width="0" data-max-width="1279">
<div style="padding: 0 0 525.2778% 0;"></div>
    <img id="g-HistorialPolitico-small-img" class="g-aiImg" alt="" src="${img1}"/>
    <div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:2.3967%;margin-top:-17.3px;left:4.6246%;width:243px;">
      <p class="g-pstyle0">HIS<span class="g-cstyle0">T</span>ORIAL POLÍTICO</p>
    </div>
    <div id="g-ai1-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:6.4915%;margin-top:-16.8px;left:6.2904%;width:146px;">
      <p class="g-pstyle0">MILI<span class="g-cstyle1">T</span>ANCIA</p>
    </div>
    <div id="g-ai1-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.6523%;margin-top:-15.6px;left:6.291%;width:76px;">
      <p class="g-pstyle1">2008</p>
    </div>
    <div id="g-ai1-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.7353%;margin-top:-16.2px;left:40.3649%;width:116px;">
      <p class="g-pstyle2">Iz<span class="g-cstyle2">q</span>uie<span class="g-cstyle3">r</span>da</p>
    </div>
    <div id="g-ai1-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:10.0045%;margin-top:-16.2px;left:40.3649%;width:129px;">
      <p class="g-pstyle2"><span class="g-cstyle3">A</span>utónoma</p>
    </div>
    <div id="g-ai1-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:11.2435%;margin-top:-15.6px;left:6.291%;width:76px;">
      <p class="g-pstyle1">2009</p>
    </div>
    <div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:13.7818%;margin-top:-15.6px;left:6.7383%;width:74px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle5">1</span>0</p>
    </div>
    <div id="g-ai1-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.3731%;margin-top:-15.6px;left:6.6488%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle6">1</span>1</p>
    </div>
    <div id="g-ai1-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:18.9114%;margin-top:-15.6px;left:6.5337%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle7">0</span>12</p>
    </div>
    <div id="g-ai1-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.5026%;margin-top:-15.6px;left:6.5913%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle8">1</span>3</p>
    </div>
    <div id="g-ai1-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:24.0938%;margin-top:-15.6px;left:6.7383%;width:74px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle5">1</span>4</p>
    </div>
    <div id="g-ai1-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.6322%;margin-top:-15.6px;left:6.6233%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle0">1</span>5</p>
    </div>
    <div id="g-ai1-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.2535%;margin-top:-16.2px;left:40.3649%;width:142px;">
      <p class="g-pstyle2">M<span class="g-cstyle9">o</span>vimien<span class="g-cstyle0">t</span>o</p>
    </div>
    <div id="g-ai1-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.2234%;margin-top:-15.6px;left:6.751%;width:74px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle10">1</span>6</p>
    </div>
    <div id="g-ai1-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.5227%;margin-top:-16.2px;left:40.3649%;width:153px;">
      <p class="g-pstyle2"><span class="g-cstyle3">A</span>u<span class="g-cstyle11">t</span>onomista</p>
    </div>
    <div id="g-ai1-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:31.8146%;margin-top:-15.6px;left:6.9748%;width:74px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle12">1</span>7</p>
    </div>
    <div id="g-ai1-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.3529%;margin-top:-15.6px;left:6.5785%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle13">1</span>8</p>
    </div>
    <div id="g-ai1-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.8686%;margin-top:-16.2px;left:39.898%;width:160px;">
      <p class="g-pstyle2">Co<span class="g-cstyle14">n</span><span class="g-cstyle11">v</span>ergencia</p>
    </div>
    <div id="g-ai1-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.9442%;margin-top:-15.6px;left:6.617%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle15">1</span>9</p>
    </div>
    <div id="g-ai1-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:38.1377%;margin-top:-16.2px;left:39.898%;width:84px;">
      <p class="g-pstyle2">Social</p>
    </div>
    <div id="g-ai1-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.5354%;margin-top:-15.6px;left:6.291%;width:76px;">
      <p class="g-pstyle1">2020</p>
    </div>
    <div id="g-ai1-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.0737%;margin-top:-15.6px;left:6.5148%;width:75px;">
      <p class="g-pstyle1">20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai1-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:45.307%;margin-top:-16.8px;left:4.7906%;width:167px;">
      <p class="g-pstyle0">C<span class="g-cstyle16">O</span>ALICIONES</p>
    </div>
    <div id="g-ai1-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.8462%;margin-top:-17.3px;left:4.6246%;width:353px;">
      <p class="g-pstyle0"><span class="g-cstyle17">C</span>A<span class="g-cstyle18">R</span>GOS DE REPRESEN<span class="g-cstyle19">T</span><span class="g-cstyle20">A</span>CIÓN</p>
    </div>
    <div id="g-ai1-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.1356%;margin-top:-15.6px;left:6.291%;width:76px;">
      <p class="g-pstyle1">2008</p>
    </div>
    <div id="g-ai1-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:57.7268%;margin-top:-15.6px;left:6.291%;width:76px;">
      <p class="g-pstyle1">2009</p>
    </div>
    <div id="g-ai1-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:60.318%;margin-top:-15.6px;left:6.7383%;width:74px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle5">1</span>0</p>
    </div>
    <div id="g-ai1-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.8564%;margin-top:-15.6px;left:6.6488%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle6">1</span>1</p>
    </div>
    <div id="g-ai1-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.9923%;margin-top:-16.2px;left:39.898%;width:132px;">
      <p class="g-pstyle2">Presiden<span class="g-cstyle6">t</span>e</p>
    </div>
    <div id="g-ai1-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.2615%;margin-top:-16.2px;left:39.898%;width:133px;">
      <p class="g-pstyle2">de la FECH</p>
    </div>
    <div id="g-ai1-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:65.4476%;margin-top:-15.6px;left:6.5337%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle7">0</span>12</p>
    </div>
    <div id="g-ai1-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:68.0388%;margin-top:-15.6px;left:6.5913%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle8">1</span>3</p>
    </div>
    <div id="g-ai1-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.6073%;margin-top:-16.2px;left:39.898%;width:116px;">
      <p class="g-pstyle2">Diputado</p>
    </div>
    <div id="g-ai1-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.5772%;margin-top:-15.6px;left:6.7383%;width:74px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle5">1</span>4</p>
    </div>
    <div id="g-ai1-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:71.8765%;margin-top:-16.2px;left:39.898%;width:151px;">
      <p class="g-pstyle2">Exdistri<span class="g-cstyle11">t</span>o 60</p>
    </div>
    <div id="g-ai1-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:73.1684%;margin-top:-15.6px;left:6.6233%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle0">1</span>5</p>
    </div>
    <div id="g-ai1-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.7067%;margin-top:-15.6px;left:6.751%;width:74px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle10">1</span>6</p>
    </div>
    <div id="g-ai1-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:78.298%;margin-top:-15.6px;left:6.9748%;width:74px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle12">1</span>7</p>
    </div>
    <div id="g-ai1-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.8892%;margin-top:-15.6px;left:6.5785%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle13">1</span>8</p>
    </div>
    <div id="g-ai1-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.9722%;margin-top:-16.2px;left:39.898%;width:116px;">
      <p class="g-pstyle2">Diputado</p>
    </div>
    <div id="g-ai1-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:82.2414%;margin-top:-16.2px;left:39.898%;width:144px;">
      <p class="g-pstyle2">Distri<span class="g-cstyle11">t</span>o 28*</p>
    </div>
    <div id="g-ai1-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:83.4275%;margin-top:-15.6px;left:6.617%;width:75px;">
      <p class="g-pstyle1">2<span class="g-cstyle4">0</span><span class="g-cstyle15">1</span>9</p>
    </div>
    <div id="g-ai1-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:86.0187%;margin-top:-15.6px;left:6.291%;width:76px;">
      <p class="g-pstyle1">2020</p>
    </div>
    <div id="g-ai1-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:88.5872%;margin-top:-16.2px;left:39.898%;width:194px;">
      <p class="g-pstyle2">Presiden<span class="g-cstyle6">t</span>e de la </p>
    </div>
    <div id="g-ai1-45" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:88.61%;margin-top:-15.6px;left:6.5148%;width:75px;">
      <p class="g-pstyle1">20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai1-46" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:89.8564%;margin-top:-16.2px;left:39.898%;width:207px;">
      <p class="g-pstyle2"><span class="g-cstyle9">R</span>epública (elec<span class="g-cstyle3">t</span>o)</p>
    </div>
    <div id="g-ai1-47" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:92.9352%;margin-top:-13.4px;left:7.3711%;width:326px;">
      <p class="g-pstyle3">*Ambos distri<span class="g-cstyle11">t</span>os representan a las </p>
    </div>
    <div id="g-ai1-48" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:94.0457%;margin-top:-13.4px;left:7.3711%;width:296px;">
      <p class="g-pstyle3">comunas de Antá<span class="g-cstyle21">r</span>tica, Cabo de </p>
    </div>
    <div id="g-ai1-49" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.1562%;margin-top:-13.4px;left:7.3711%;width:305px;">
      <p class="g-pstyle3">Hornos, Laguna Blanca, Natales, </p>
    </div>
    <div id="g-ai1-50" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.2667%;margin-top:-13.4px;left:7.3711%;width:325px;">
      <p class="g-pstyle3"><span class="g-cstyle0">P</span>o<span class="g-cstyle22">r</span><span class="g-cstyle11">v</span>eni<span class="g-cstyle19">r</span>, Prim<span class="g-cstyle14">a</span><span class="g-cstyle11">v</span>era, Punta Arenas, </p>
    </div>
    <div id="g-ai1-51" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.3773%;margin-top:-13.4px;left:7.3711%;width:323px;">
      <p class="g-pstyle3">Río <span class="g-cstyle7">V</span>e<span class="g-cstyle3">r</span>de, San Gregorio, Timau<span class="g-cstyle23">k</span>el, </p>
    </div>
    <div id="g-ai1-52" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.4878%;margin-top:-13.4px;left:7.3711%;width:159px;">
      <p class="g-pstyle3"><span class="g-cstyle24">T</span>orres del <span class="g-cstyle18">P</span>aine</p>
    </div>
  </div>


</div>
`

const containerId = 'g-HistorialPolitico-box'
const namespace = 'g-'
const name = 'HistorialPolitico'

export default makeAi2React({ html, styles, containerId, namespace, name })

/* End ai2react - 2021-12-20 22:30 */
