const fichas = [
  {
    nombre: 'Carolina Tohá',
    cargo: 'Ministerio del Interior y Seguridad Pública',
    edad: '57',
    partido: 'PPD',
    profesion: 'Cientista política',
    nivelAcademico: 'Doctora en Ciencias Políticas',
    colegio: 'Colegio Francisco de Miranda',
    universidad: 'Università degli Studi di Milano',
    biografia:
      'Carolina Tohá es cientista política. Fue Diputada entre 2002 y 2009 para luego asumir como ministra de la Segpres durante el gobierno de Michelle Bachelet. Posteriormente se desempeñó como alcaldesa de Santiago durante el periodo 2012-2016. ',
    url: 'https://www.latercera.com/politica/noticia/carolina-toha-el-revival-de-una-figura-historica-de-la-ex-concertacion/4Q3ONGCPWVG33ADLHEG6LD5TF4/',
    foto: 'https://www.latercera.com/resizer/uBgdMmIpR8dJssFQsD3OCK_BVv4=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/FC5BJCUFOBAWDMPK4NNNJHQ4MY.jpg',
  },
  {
    nombre: 'Antonia Urrejola',
    cargo: 'Ministerio de Relaciones Exteriores',
    edad: '53',
    partido: 'Independiente cercana al Partido Socialista',
    profesion: 'Abogada',
    nivelAcademico:
      'Postítulo en Derechos Humanos y Procesos de Democratización',
    colegio: "Saint George's College, Vitacura",
    universidad: 'Universidad de Chile',
    biografia:
      'Antonia Urrejola es cercana al Partido Socialista, abogada de la Universidad de Chile y ha estado vinculada a los derechos humanos. Urrejola ha tenido un largo historial como asesora de diversos gobiernos, tanto de la Concertación como de la Nueva Mayoría. Fue asesora de Mideplan durante la administración del expresidente Frei, luego asesora del Ministerio del Interior en el mandato de Lagos. También fue asesora del exsecretario general de la OEA José Miguel Insulza. Además fue asesora en derechos humanos durante el segundo gobierno de Bachelet. En el último tiempo fue comisionada y expresidenta de la CIDH.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-antonia-urrejola-la-nueva-ministra-de-relaciones-exteriores-de-gabriel-boric/PON6JSXZKNFUFLWMU75WRBOHSE/',
    foto: 'https://www.latercera.com/resizer/J3jiAcwFGyG-l9q6nKx3ByZIHxA=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/ZYIAYIESPBCNXO3HTWAYECYP7Q.jpg',
  },
  {
    nombre: 'Maya Fernández',
    cargo: 'Ministerio de Defensa',
    edad: '50',
    partido: 'Partido Socialista',
    profesion: 'Bióloga y Médica Veterinaria',
    nivelAcademico: 'Universitario',
    colegio: 'Escuela Primaria Solidaridad con Chile (Cuba)',
    universidad: 'Universidad de Chile',
    biografia:
      'Maya Fernández es militante del Partido Socialista. Tiene dos títulos profesionales: es bióloga y veterinaria. Es nieta del expresidente Salvador Allende y sobrina de la senadora Isabel Allende. Vivió en el exilio en Cuba desde 1973 hasta 1990. Ha sido diputada por dos periodos y concejala de Ñuñoa. Presidió la Cámara en 2018.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-maya-fernandez-la-nueva-ministra-de-defensa-de-gabriel-boric/XD4G4O2QRZF2DPV5C4ZKGESX6M/',
    foto: 'https://www.latercera.com/resizer/R-kX9CxagoTs5Wnpe7Rn6cupyFg=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/NBFAKGAJS5GOHC6XNEV2CUHMZU.jpg',
  },
  {
    nombre: 'Mario Marcel',
    cargo: 'Ministerio de Hacienda',
    edad: '62',
    partido: 'Exmilitante del Partido Socialista',
    profesion: 'Ingeniero Comercial',
    nivelAcademico: 'M. Phil. en Economía',
    colegio: 'Instituto Nacional, Santiago',
    universidad: 'Universidad de Chile',
    biografia:
      'El Presidente electo optó por el actual presidente del Banco Central para dirigir la sede ministerial de Teatinos 120. El economista es consejero del instituto emisor desde 2015 y preside el organismo desde 2016. De hecho el Presidente Sebastián Piñera el año pasado optó por renovarle el cargo por otros cinco años. Es exmilitante del Partido Socialista y su nombre ha estado presente en cargos macroeconómicos en casi todos los gobiernos desde el retorno a la democracia. En el último tiempo fue un férreo opositor a los retiros anticipados de los fondos previsionales, lo que lo llevó a enfrentarse a parlamentarios del Frente Amplio y del Partido Comunista.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-mario-marcel-el-nuevo-ministro-de-hacienda-de-gabriel-boric/K6M7AIMLXZHSJLKUH2PDYBJO5A/',
    foto: 'https://www.latercera.com/resizer/5qucg8ezlediT4k7KWPM2-xKkMU=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/NB5RDMTATBGXDBYRGH7BBEBKJY.jpg',
  },
  {
    nombre: 'Ana Lya Uriarte',
    cargo: 'Ministerio Secretaría General de la Presidencia',
    edad: '60',
    partido: 'Partido Socialista',
    profesion: 'Abogada',
    nivelAcademico: 'Universitario',
    colegio: 'Liceo 4, Recoleta',
    universidad: 'Universidad de Chile',
    biografia:
      'Ana Lya Uriarte es abogada de la Universidad de Chile. Se desempeñó como jefa de gabinete del gobierno de Michelle Bachelet. También, en 2007 fue presidenta de la Comisión Nacional del Medio Ambiente (CONAMA). En mayo de 2022 llegó al gobierno de Gabriel Boric, para desempañerase como jefa de gabinete del Ministerio del Interior. ',
    url: 'https://www.latercera.com/politica/noticia/ana-lya-uriarte-la-mano-derecha-de-bachelet-que-llega-a-la-segpres-y-a-impulsar-un-acuerdo-constituyente/H23NDPUESBGOHAXSYDPFLZ4LQY/',
    foto: 'https://www.latercera.com/resizer/0rBrq66xIY4oFAoFzJDjMWWte70=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/IROIEXBEERHSVEAQ3PVCFVTLHQ.jpg',
  },
  {
    nombre: 'Camila Vallejo',
    cargo: 'Ministerio Secretaría General de Gobierno',
    edad: '34',
    partido: 'Partido Comunista',
    profesion: 'Geógrafa',
    nivelAcademico: 'Universitario',
    colegio: 'Colegio Raimapu, La Florida',
    universidad: 'Universidad de Chile',
    biografia:
      'Camila Vallejo es geógrafa de la Universidad de Chile. Ha sido diputada durante dos periodos parlamentarios. Es militante del Partido Comunista y en 2011 fue presidenta de la Fech. Ese año además fue vocera de la Confech. En 2012 asumió como vicepresidenta de la Fech, el mismo año en que Boric le tocó presidir la mesa de esa federación estudiantil.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-camila-vallejo-la-nueva-ministra-vocera-de-gobierno-de-gabriel-boric/TMTFGJBKWRFDFK5PLYY54KPB4E/',
    foto: 'https://www.latercera.com/resizer/qo29MXVzKULQvPS8l4yU43ZJgxo=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/6RA2ODUTENDR3EBJKAOFZO7YL4.jpg',
  },
  {
    nombre: 'Nicolás Grau',
    cargo: 'Ministerio de Economía, Fomento y Turismo',
    edad: '39',
    partido: 'Convergencia Social',
    profesion: 'Ingeniero Comercial',
    nivelAcademico: 'Magister y Ph.D. en Economía',
    colegio: 'Colegio Raimapu, La Florida',
    universidad: 'Universidad de Chile',
    biografia:
      'Nicolás Grau es economista y milita en Convergencia Social. Tiene un doctorado en Economía de la Universidad de Pennsylvania. Es profesor del Departamento de Economía de la Universidad de Chile y ha sido investigador adjunto en el Centro de Estudios de Conflicto y Cohesión Social. Fue presidente de la FECH en 2006.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-nicolas-grau-el-nuevo-ministro-de-economia-de-gabriel-boric/LELPOC6FHZDZ3DELICVPNOSTYA/',
    foto: 'https://www.latercera.com/resizer/OotEq3kjQAmozGUT0pdkgIEv-VQ=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/OPP5N3SKVVEM7KRKIIIU3YYIA4.jpg',
  },
  {
    nombre: 'Giorgio Jackson',
    cargo: 'Ministerio de Desarrollo Social y Familia',
    edad: '35',
    partido: 'Revolución Democrática',
    profesion: 'Ingeniero civil industrial',
    nivelAcademico: 'Universitario',
    colegio: 'Colegio Alemán Thomas Morus, Providencia',
    universidad: 'Pontificia Universidad Católica',
    biografia:
      'Giorgio Jackson es ingeniero de la Universidad Católica y ha sido diputado durante dos periodos parlamentarios. Es militante de Revolución Democrática y en 2011 fue presidente de la FEUC y vocero de la Confech.',
    url: 'https://www.latercera.com/politica/noticia/giorgio-jackson-se-mantiene-en-el-gobierno-y-asumira-ministerio-de-desarrollo-social/TCM5MN42RJEFJERCFG2OH2LITA/',
    foto: 'https://www.latercera.com/resizer/Evj6fvcMt_Uf6hKyp0i3JWBEJGk=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/EFTW3D5QFJE3THT6JKM37ZPFSY.jpg',
  },
  {
    nombre: 'Marco Antonio Ávila',
    cargo: 'Ministerio de Educación',
    edad: '44',
    partido: 'Revolución Democrática',
    profesion: 'Profesor',
    nivelAcademico: 'Magister en Educación',
    colegio: 'Liceo Andrés Bello, San Miguel',
    universidad: 'Universidad Católica Cardenal Raúl Silva Henríquez',
    biografia:
      'Marco Antonio Ávila es profesor y jefe de Proyectos en la Fundación Chile, donde se dedica a las materias educativas, especialmente en contextos de vulnerabilidad. Sus áreas de interés son el desarrollo profesional docente y mejoramiento educativo. Trabajó en el Mineduc en el segundo gobierno de Bachelet, como coordinador nacional de Enseñanza Media.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-marco-antonio-avila-el-nuevo-ministro-de-educacion-de-gabriel-boric/SSFS3TEOJJH4VMDVM2DKX337KA/',
    foto: 'https://www.latercera.com/resizer/RWgz6jHVPm2tJe2zUmkCHxYjhaM=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/DNHBLJHP7JDAZHDW3NKS2L276U.jpg',
  },
  {
    nombre: 'Marcela Ríos',
    cargo: 'Ministerio de Justicia',
    edad: '55',
    partido: 'Convergencia Social',
    profesion: 'Socióloga',
    nivelAcademico: 'Doctora en Filosofía',
    colegio: '-',
    universidad: 'Universidad de York (Canadá)',
    biografia:
      'Marcela Ríos es socióloga y la mayor parte de su carrera la ha hecho desde el Programa de las Naciones Unidas para el Desarrollo. Desde ahí se ha dedicado con fuerza a impulsar temas de desigualdad, justicia y sobre todo de género. Es académica y tiene estudios de posgrado en la Facultad Latinoamericana de Ciencias Sociales y un doctorado en filosofía en la Universidad de Wisconsin-Madison.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-marcela-rios-la-nueva-ministra-de-justicia-de-gabriel-boric/QOMVUIBOGZECHMURKA3HDJKYSE/',
    foto: 'https://www.latercera.com/resizer/Axh3BPgoPrNQIox2iRHAKOd-Cdc=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/XKWYW7XEOJBHLL7KDFT2VC4QGA.jpg',
  },
  {
    nombre: 'Jeannette Jara',
    cargo: 'Ministerio de Trabajo y Previsión Social',
    edad: '48',
    partido: 'Partido Comunista',
    profesion: 'Abogada',
    nivelAcademico: 'Magíster en Administración Pública',
    colegio: 'Liceo Isaura Dinator de Guzmán, Santiago',
    universidad: 'Universidad Central',
    biografia:
      'Jeannete Jara es abogada de la Universidad Central. Tiene estudios en derecho tributario y también de magíster en Gerencia Pública. Fue subsecretaria de Previsión Social durante el segundo gobierno de la expresidenta Bachelet. Es administradora municipal en la comuna de Santiago.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-jeannette-jara-la-nueva-ministra-de-trabajo-de-gabriel-boric/66DNYJQMDRAZXDAT5LAW5QQB4E/',
    foto: 'https://www.latercera.com/resizer/5-1FQEGQB6P3WsvbS8OPSslsoGo=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/Y4WD77CJ2VB4LOI7675GNC3HO4.jpg',
  },
  {
    nombre: 'Juan Carlos García',
    cargo: 'Ministerio de Obras Públicas',
    edad: '51',
    partido: 'Partido Liberal',
    profesion: 'Arquitecto',
    nivelAcademico: 'Magíster en Gestión Urbana',
    colegio: "Saint George's College, Vitacura",
    universidad: 'Pontificia Universidad Católica de Valparaíso',
    biografia:
      'Juan Carlos García es arquitecto de la Universidad Católica de Valparaíso. Participó en el Servicio País en la Región de Aysén, desde donde impulsó iniciativas reconocidas a nivel nacional. Se formó como urbanista en Francia y fue candidato a gobernador.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-juan-carlos-garcia-el-nuevo-ministro-de-obras-publicas-de-gabriel-boric/C2CVB2CU7JF6JB4O7TOZ4UROGU/',
    foto: 'https://www.latercera.com/resizer/mHQFaHEMYqsNYunkOzeN6WrIQlI=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/OAS6KGPGHVH37EWQWWIU6TAVWI.jpg',
  },
  {
    nombre: 'Ximena Aguilera',
    cargo: 'Ministerio de Salud',
    edad: '57',
    partido: '',
    profesion: 'Médica ',
    nivelAcademico: 'Magíster en Salud Pública',
    colegio: '',
    universidad: 'Universidad de Chile',
    biografia:
      'Ximena Aguilera es médico cirujana de la Universidad de Chile. Antes de asumir como Ministra se desempeñó como directora del Centro de Epidemiología y Políticas de Salud de la Facultad de Medicina de la Universidad del Desarrollo (UDD). Entre los años 1999 y 2005 fue fue jefa nacional de Epidemiología en el Ministerio de Salud y jefa de la división de Planificación Sanitaria. Además, durante la pandemia formó parte del Consejo Asesor Externo.',
    url: 'https://www.latercera.com/nacional/noticia/quien-es-la-nueva-ministra-de-salud-ximena-aguilera-presidio-la-comision-de-respuesta-pandemica-y-en-la-ops-lucho-contra-la-influenza-h1n1/VMU3LVMWGNHIPHGFSHYXOCXAIU/',
    foto: 'https://www.latercera.com/resizer/K-9vcjd_Z9SwxqpKgssDoKVy3FI=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/OFJ6QPU43ND47PJ5BRA73PAOPU.jpg',
  },
  {
    nombre: 'Carlos Montes',
    cargo: 'Ministerio de Vivienda y Urbanismo',
    edad: '76',
    partido: 'Partido Socialista',
    profesion: 'Egresado de Ingeniería Comercial',
    nivelAcademico: 'Universitario',
    colegio: "Saint George's College",
    universidad: 'Pontificia Universidad Católica',
    biografia:
      'Carlos Montes es senador por la Región Metropolitana. Tiene una larga carrera política que incluye además seis periodos parlamentarios consecutivos como diputado. Es egresado de Ingeniería Comercial de la Universidad Católica y fue presidente del Senado en 2018.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-carlos-montes-el-nuevo-ministro-de-vivienda-y-urbanismo-de-gabriel-boric/4PTPGY7FTJGS5DOL2O2RETXSCU/',
    foto: 'https://www.latercera.com/resizer/RwtFx-PduuqWw19xYzjHJbwjyxM=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/4RC5OGT5BNDWPGBELQCZLVLL7I.jpg',
  },
  {
    nombre: 'Esteban Valenzuela',
    cargo: 'Ministerio de Agricultura',
    edad: '57',
    partido: 'Federación Regionalista Verde Social',
    profesion: 'Periodista',
    nivelAcademico: 'Magíster en Desarrollo y Gestión Pública',
    colegio: "Instituto O'Higgins, Rancagua",
    universidad: 'Pontificia Universidad Católica',
    biografia:
      'Esteban Valenzuela es militante del Frente Regionalista Verde Social. Es periodista, cientista político e historiador. Ha sido asesor sindical y director de Convergencias Regionalistas de Estudios Aplicados del Sur (Creasur).',
    url: 'https://www.latercera.com/politica/noticia/quien-es-esteban-valenzuela-el-nuevo-ministro-de-agricultura-de-gabriel-boric/KYI4ASZGJBFTZE3FYEAPZ6XUDY/',
    foto: 'https://www.latercera.com/resizer/lQ0jxEHJ5t3yAqqZIDNOKdZumYE=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/BIAIDIIXGVCRBDUC6QQS7ZE77I.jpg',
  },
  {
    nombre: 'Marcela Hernando',
    cargo: 'Ministerio de Minería',
    edad: '62',
    partido: 'Partido Radical',
    profesion: 'Médica',
    nivelAcademico: 'Magíster en Salud Pública',
    colegio: 'Liceo María Auxiliadora, Santiago',
    universidad: 'Universidad de Chile',
    biografia:
      'La médica Marcela Hernando es militante del Partido Radical. Durante dos periodos parlamentarios ha sido diputada por la región de Antofagasta. Entre los años 2008 y 2012 fue alcaldesa de la comuna de Antofagasta y también fue intendenta por esta misma región durante el primer gobierno de la expresidente Michelle Bachelet. Toda su carrera ha estado ligada a cargos públicos en el mundo de la salud. Desde marzo deberá asumir un nuevo desafío, pero esta vez a cargo del ministerio de Minería.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-marcela-hernando-la-nueva-ministra-de-mineria-de-gabriel-boric/L6BLSQMDOZE7NNOYK6BYNVZ7II/',
    foto: 'https://www.latercera.com/resizer/FG927mwmb8fCPlPE9hrx-uWLwwY=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/KVJ4FWBMKVD7TMBPMD5IAX3GGE.jpg',
  },
  {
    nombre: 'Juan Carlos Muñoz',
    cargo: 'Ministerio de Transportes y Telecomunicaciones',
    edad: '52',
    partido: 'Independiente',
    profesion: 'Ingeniero Civil',
    nivelAcademico: 'Doctor en Ingeniería Civil y Ambiental',
    colegio: 'Craighouse School',
    universidad: 'Pontificia Universidad Católica',
    biografia:
      'Juan Carlos Muñoz es ingeniero civil de la Universidad Católica. Toda su carrera la ha dedicado a los temas de transportes, desde el mundo público y también desde la academia. Entre 2003 y 2004 fue asesor del Ministro de Transportes y Telecomunicaciones para el plan Transantiago. En 2008 también fue miembro del comité de expertos creado por esa misma cartera para mejorar el proyecto Transantiago. Estuvo en el directorio del Metro regional de Valparaíso. También ejerció como director de Metro y asesor de la Dirección de Transporte Público Metropolitano',
    url: 'https://www.latercera.com/politica/noticia/quien-es-juan-carlos-munoz-el-nuevo-ministro-de-ministerio-de-transportes-y-telecomunicaciones-de-gabriel-boric/3Y33LNMB6FBINDY65GBMFIUSHU/',
    foto: 'https://www.latercera.com/resizer/We0B10QcSGI-HxQ_3N0tgAXFxNY=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/MTOFCJDV2FCSLMTUGN3Q4P7XGA.jpg',
  },
  {
    nombre: 'Javiera Toro',
    cargo: 'Ministerio de Bienes Nacionales',
    edad: '34',
    partido: 'Comunes',
    profesion: 'Abogada',
    nivelAcademico: 'Universitario',
    colegio: 'Colegio la Girouette, Las Condes',
    universidad: 'Universidad de Chile',
    biografia:
      'Javiera Toro es abogada de la Universidad de Chile. Fue presidenta de Comunes y es directora de la Fundación Nodo XXI. Ha trabajado como abogada en estudios privados.',
    url: '',
    foto: 'https://www.latercera.com/resizer/skmi57ieLoDu6MVqqVoBYpb2zn0=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/OMLEPHKHJNFMFNRRFKSHKRWMMQ.jpg',
  },
  {
    nombre: 'Diego Pardow',
    cargo: 'Ministerio de Energía',
    edad: '42',
    partido: 'Convergencia Social',
    profesion: 'Abogado',
    nivelAcademico: 'Magister y Doctor en Derecho',
    colegio: "Colegio Granville's College",
    universidad: 'Universidad de Chile',
    biografia:
      'Diego Pardow es abogado de la Universidad de Chile. Además tiene un magíster y un doctorado en Derecho en la Universidad de California, Berkeley. Su carrera ha sido principalmente académica, siendo profesor de la Facultad de Derecho de la Universidad de Chile. A su vez es director ejecutivo de Espacio Público, cargo que tiene suspendido. Es cercano a Convergencia Social y un asesor cercano de Boric. Durante su campaña fue vocero de la candidatura y además ejerció como uno de los coordinadores programáticos.',
    url: 'https://www.latercera.com/pulso/noticia/asesor-del-segundo-piso-diego-pardow-es-el-nuevo-ministro-de-energia/P7A5HRABDRHHLPDFTTE4Q42EN4/',
    foto: 'https://www.latercera.com/resizer/0f7hLsrvhaNM-iNRDAjZuFOkOtc=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/5GGKXSWQMRHD3OVDTR4NJFDJNA.jpg',
  },
  {
    nombre: 'Maisa Rojas',
    cargo: 'Ministerio de Medio Ambiente',
    edad: '50',
    partido: '',
    profesion: 'Licenciatura en Física',
    nivelAcademico: 'Doctorado en Física de la Atmósfera',
    colegio: 'Colegio Instituto Santa María',
    universidad: 'Universidad de Chile',
    biografia:
      'Maisa Rojas es una reconocida climatóloga chilena. Es independiente. También es académica de la Universidad de Chile y Directora del Centro de Ciencia del Clima y la Resiliencia. Estudió física en la Universidad de Chile y un doctorado en física atmosférica en la Universidad de Oxford. Fue una de las autoras del informe del Panel Intergubernamental de Cambio Climático (IPCC). También se desempeñó como coordinadora del comité científico asesor para la COP25.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-maisa-rojas-la-nueva-ministra-de-medio-ambiente-de-gabriel-boric/WABEL2PBEFA2ZPTZYFDFKAU6PY/',
    foto: 'https://www.latercera.com/resizer/sNT08c4guG8FMBsRS2uenlBj3VQ=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/5XPGSF2DIRA5VKBEYPQNKSOJXM.jpg',
  },
  {
    nombre: 'Julieta Brodsky',
    cargo: 'Ministerio de las Culturas, las Artes y el Patrimonio',
    edad: '38',
    partido: 'Convergencia Social',
    profesion: 'Antropóloga social y cultural',
    nivelAcademico: 'Magíster en Antropología Urbana',
    colegio: 'Colegio Altamira, Peñalolén',
    universidad: 'Universidad de Granada (España)',
    biografia:
      'Julieta Brodsky es antropóloga social y cultural de la Universidad de Granada (España) y egresada del magíster en Antropología Urbana de la Universidad Academia de Humanismo Cristiano. Su carrera ha estado ligada al mundo de la cultura. Actualmente es directora de Investigación del Observatorio de Políticas Culturales y socia de la Asociación Cultural Tramados.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-julieta-brodsky-la-nueva-ministra-de-las-culturas-las-artes-y-el-patrimonio-de-gabriel-boric/4E342HUIMNA5RDFL6U4HKEYIQM/',
    foto: 'https://www.latercera.com/resizer/UJuwKOgza3_LXX7-dVU_7sqcFNU=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/KTVFVXBOKBHKNF6LH57O37Z5FE.jpg',
  },
  {
    nombre: 'Alexandra Benado',
    cargo: 'Ministerio de Deporte',
    edad: '45',
    partido: '',
    profesion: 'Profesor',
    nivelAcademico: 'Universitario',
    colegio: 'Colegio Rubén Darío, La Reina',
    universidad: 'Universidad Metropolitana de Ciencias de la Educación',
    biografia:
      'Alexandra Benado nació en Suecia, es futbolista y también ha sido directora técnica. Es activista LGTBI. Desde ahí ha luchado por los derechos filiativos de sus hijos mellizos. Denunció al Estado ante la Corte Interamericana de derechos humanos para que parejas homoparentales, como ella, tuvieran reconocimiento jurídico. Además es coordinadora ejecutiva en Londres 38.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-alexandra-benado-la-nueva-ministra-del-deporte-de-gabriel-boric/NI2VSDQRSVDOJPD3XPTE4CSDHA/',
    foto: 'https://www.latercera.com/resizer/xReiLo5ZsNxbxQ7xDKx0LXP-uaw=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/DQ7Z7MTU35F6PI6ZZZMSQXZT64.jpg',
  },
  {
    nombre: 'Antonia Orellana',
    cargo: 'Ministerio de la Mujer y la Equidad de Género',
    edad: '32',
    partido: 'Convergencia Social',
    profesion: 'Periodista',
    nivelAcademico: 'Universitario',
    colegio: 'Liceo Tajamar, Providencia',
    universidad: 'Universidad de Chile',
    biografia:
      'Antonia Orellana es periodista y militante de Convergencia Social. Su carrera ha estado siempre enfocada en temas de género. Forma parte de la Red Chilena Contra la Violencia hacia las Mujeres. Fue candidata a convencional por el distrito 10, pero no logró su escaño. Es parte del círculo más íntimo de Boric.',
    url: 'https://www.latercera.com/politica/noticia/quien-es-antonia-orellana-la-nueva-ministra-de-de-la-mujer-y-la-equidad-de-genero-de-gabriel-boric/YJTVWXNJXJDX7J4AVFIABM4ASE/',
    foto: 'https://www.latercera.com/resizer/CthA2q0oNq_Yvdy67pWdiKmERHo=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/6LKW7GK7TBCQLHBDZBUVLPY7JE.jpg',
  },
  {
    nombre: 'Silvia Díaz',
    cargo: 'Ministerio de Ciencia, Tecnología, Conocimiento e Innovación',
    edad: '35',
    partido: '',
    profesion: 'Química',
    nivelAcademico: 'Doctora en Química',
    colegio: 'Colegio Santa María, Ovalle',
    universidad: 'Pontificia Universidad Católica',
    biografia:
      'Silvia Díaz Acosta es doctora en química y primera mujer en asuir el cargo en el ministerio. Fue directora científica en la Fundación Encuentros del Futuro. Además fue parte de la conformación del Ministerio de Ciencia, Tecnología, Conocimiento e Innovación, en 2018.',
    url: 'https://www.latercera.com/que-pasa/noticia/silvia-diaz-cientifica-de-la-fundacion-que-organiza-el-congreso-futuro-es-la-nueva-ministra-de-ciencia/4TL5TRCSG5E37H7D7H7HG3YTNE/',
    foto: 'https://www.latercera.com/resizer/LdXYsxMAxPUTDkY00eVMf86447Y=/0x300/filters:quality(75)/arc-anglerfish-arc2-prod-copesa/public/LGUIUVUXMFBR7PYXKUEHEYRFM4.jpg',
  },
]

export default fichas
