const fichas = [
  {
    nombre: 'Giorgio Jackson',
    cargo: 'Ministerio del Interior y Seguridad Pública',
    edad: '34',
    partido: 'Revolución Democrática',
    profesion: 'Ingeniero civil industrial ',
    nivelAcademico: '',
    colegio: 'Colegio Alemán Thomas Morus, Providencia',
    universidad: 'U. Católica',
    biografia:
      'Giorgio Jackson (34) es ingeniero de la Universidad Católica y ha sido diputado durante dos periodos parlamentarios. Es militante de Revolución Democrática y en 2011 fue presidente de la FEUC y vocero de la Confech.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/30cvnqApLZnKdFlizqRm51X31rY=/arc-anglerfish-arc2-prod-copesa/public/RG3DS7BUFBGRZJTFTH62S6T2QM.jpg',
  },
  {
    nombre: 'Antonia Urrejola',
    cargo: 'Ministerio de Relaciones Exteriores',
    edad: '53',
    partido: '',
    profesion: 'Abogada',
    nivelAcademico:
      'Postítulo en Derechos Humanos y Procesos de Democratización',
    colegio: '',
    universidad: 'U. de Chile',
    biografia:
      'Antonia Urrejola es cercana al Partido Socialista, es abogada de la Universidad de Chile y ha estado vinculada a los derechos humanos. Urrejola ha tenido un largo historial como asesora de diversos gobiernos, tanto de la Concertación como de la Nueva Mayoría. Fue asesora de Mideplan durante la administración del expresidente Frei, luego asesora del Ministerio del Interior en el mandato de Lagos. También fue asesora del exsecretario general de la OEA José Miguel Insulza. También fue asesora en derechos humanos durante el segundo gobierno de Bachelet. En el último tiempo fue comisionada y expresidenta de la CIDH.',
    url: 'https://google.com/',
    foto: '',
  },
  {
    nombre: 'Paulina Vodanovic',
    cargo: 'Ministerio de Defensa',
    edad: '50',
    partido: 'Partido Socialista',
    profesion: 'Abogada',
    nivelAcademico: 'Magíster en Derecho Público',
    colegio: 'Liceo 1 Javiera Carrera, Santiago',
    universidad: 'U. de Chile',
    biografia:
      'Paulina Vodanovic es una abogada socialista. Estudió en la Universidad de Chile, donde también cursó estudios de magíster en Derecho Público. Ha ejercido libremente su profesión, hasta que en 2014 asumió como jefa de la División Jurídica del Ministerio de Justicia. Luego fue subsecretaria para las Fuerzas Armadas. Es la presidente del directorio de la Fundación Horizonte Ciudadano, la instancia creada por la expresidenta Michelle Bachelet luego de su segundo mandato.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/P7EB0Ty5NhzwkE6-hl4g28Azp5U=/arc-anglerfish-arc2-prod-copesa/public/HIVAEVBESJHGFETEHCDRUJGABY.jpg',
  },
  {
    nombre: 'Mario Marcel',
    cargo: 'Ministerio de Hacienda',
    edad: '62',
    partido: '',
    profesion: 'Ingeniero Comercial',
    nivelAcademico: 'M. Phil. en Economía ',
    colegio: '',
    universidad: 'U. de Chile',
    biografia: '',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/phrzmeeonTjGzyalWcyn8di4XgY=/arc-anglerfish-arc2-prod-copesa/public/N7A2FRFGDJFOTJ566AKEJYW3TM.jpg',
  },
  {
    nombre: 'Miguel Crispi',
    cargo: 'Ministerio Secretaría General de la Presidencia',
    edad: '36',
    partido: 'Revolución Democrática',
    profesion: 'Sociólogo',
    nivelAcademico: '',
    colegio: "Saint George's College, Vitacura",
    universidad: 'U. Católica',
    biografia:
      'El actual diputado de Revolución Democrática (RD) tiene 36 años y es parlamentario por el distrito 12 de la Región Metropolitana. Militó en el Partido Socialista hasta 2012 y luego fue fundador y coordinador general de RD antes de que se constituyera como partido político. Presidió la FEUC en 2009. Es sociólogo y trabajó como asesor en el Mineduc a cargo de la reforma educacional durante la segunda administración de la expresidenta Michelle Bachelet.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/2OGBU4Kgun2Ib6TnB7zrxF5OlIM=/arc-anglerfish-arc2-prod-copesa/public/4EWMVU4ETBDBVIETASGPYPRFR4.jpg',
  },
  {
    nombre: 'Izkia Siches',
    cargo: 'Ministerio Secretaría General de Gobierno',
    edad: '35',
    partido: 'Independiente',
    profesion: 'Médica',
    nivelAcademico: 'Magíster en Salud Pública',
    colegio: "Instituto de Humanidades Bernardo O'Higgins, Maipú",
    universidad: 'U. de Chile',
    biografia:
      'Izkia Siches es médica de la Universidad de Chile. Hizo su especialidad de Medicina Interna con una beca estatal del Minsal en el Hospital San Juan de Dios. Fue presidenta del Colegio Médico, pero renunció a su cargo para asumir como jefa de campaña de Boric. Cuando era estudiante universitaria, militó en las Juventudes Comunistas. Actualmente es independiente.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/mdHinED1DSGGoPxmlPtBU_lz5Ms=/arc-anglerfish-arc2-prod-copesa/public/GWYAATTBSZDKHGVGAGVNECAD7A.jpg',
  },
  {
    nombre: 'Nicolás Grau',
    cargo: 'Ministerio de Economía, Fomento y Turismo',
    edad: '38',
    partido: '',
    profesion: 'Ingeniero Comercial',
    nivelAcademico: 'Magister y Ph.D. en Economía',
    colegio: 'Colegio Raimapu',
    universidad: 'U. de Chile',
    biografia:
      'Nicolás Grau (38) es economista y milita en Convergencia Social. Tiene un doctorado en Economía de la Universidad de Pennsylvania. Es profesor del Departamento de Economía de la Universidad de Chile y ha sido investigador adjunto en el Centro de Estudios de Conflicto y Cohesión Social. Fue presidente de la FECH en 2006.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/MxOu1KCrF42WQCUW31nnaJrxqJA=/arc-anglerfish-arc2-prod-copesa/public/U56EBTBEO5FALCLMLFL4ETHCRY.jpg',
  },
  {
    nombre: 'Camila Vallejo',
    cargo: 'Ministerio de Desarrollo Social y Familia',
    edad: '33',
    partido: 'Partido Comunista',
    profesion: 'Geógrafa',
    nivelAcademico: '',
    colegio: 'Colegio Raimapu Tierra Florida',
    universidad: 'U. de Chile',
    biografia: '',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/PudXU9xGFrIGEdc-9npt6rc4cZQ=/arc-anglerfish-arc2-prod-copesa/public/BXELLX642JAAHAJQB4CA2QZWTU.jpg',
  },
  {
    nombre: 'Cristian Bellei',
    cargo: 'Ministerio de Educación',
    edad: '50',
    partido: '',
    profesion: 'Sociólogo',
    nivelAcademico: 'Máster en Política Educacional y Doctor en Educación',
    colegio: '',
    universidad: 'U. de Chile',
    biografia: '',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/pe7tWCDu30_3BBC35IDCC4eES7c=/arc-anglerfish-arc2-prod-copesa/public/IVMPYJRGCNBBBH32XWPN7ZICUI.jpg',
  },
  {
    nombre: 'Carlos Gajardo',
    cargo: 'Ministerio de Justicia',
    edad: '49',
    partido: '',
    profesion: 'Abogado',
    nivelAcademico: '',
    colegio: '',
    universidad: 'U. de Chile',
    biografia: '',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/_diS1PcHoq9gS4BpvwUSBl1u7BY=/arc-anglerfish-arc2-prod-copesa/public/N7OHFLHCWFAEPBW4LK2MZFOBLY.jpg',
  },
  {
    nombre: 'Bárbara Figueroa',
    cargo: 'Ministerio de Trabajo y Previsión Social',
    edad: '42',
    partido: 'Partido Comunista',
    profesion: 'Profesora de Filosofía',
    nivelAcademico: '',
    colegio: 'Liceo José Gregorio Argomedo, San Fernando',
    universidad: 'UMCE',
    biografia: '',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/5gpepF8edyFwQ06Pqwd1RpHqZ9M=/arc-anglerfish-arc2-prod-copesa/public/EK4B4JD67RGYFM5R4TJ4FCLSZ4.jpg',
  },
  {
    nombre: 'Paula Narváez',
    cargo: 'Ministerio de Obras Públicas',
    edad: '49',
    partido: 'Partido Socialista',
    profesion: 'Sicóloga',
    nivelAcademico: 'Magíster en Economía y Gestión Regional',
    colegio: 'Colegio Inmaculada Concepción, Concepción',
    universidad: 'U. Andrés Bello',
    biografia:
      'Paula Narváez es psicóloga de la Universidad Andrés Bello. Tiene un magíster en Economía y Gestión Regional de la Universidad Austral y otro en Relaciones Internacionales de la Universidad de Georgetown. Nació en Puerto Montt y milita en el Partido Socialista. Ha sido Seremi del Trabajo durante el primer gobierno de Bachelet. En ese periodo también fue delegada presidencial para la reconstrucción de Chaitén. Fue jefe de gabinete en el segundo mandato de Bachelet y luego fue su vocera. Es exprecandidata presidencial y también ha trabajado en ONU Mujeres.',
    url: 'https://google.com/',
    foto: '',
  },
  {
    nombre: 'Matías Goyenechea',
    cargo: 'Ministerio de Salud',
    edad: '38',
    partido: '',
    profesion: 'Cientista político',
    nivelAcademico: '',
    colegio: 'Francisco de Miranda, Peñalolén',
    universidad: 'U. Arcis',
    biografia: '',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/H9qJN0edfb2j3-XJpU36fiC3sDk=/arc-anglerfish-arc2-prod-copesa/public/NGCXY7SK4VH43E3ZTM5VGVZLLA.jpg',
  },
  {
    nombre: 'Carlos Montes',
    cargo: 'Ministerio de Vivienda y Urbanismo',
    edad: '75',
    partido: 'Partido Socialista',
    profesion: 'Economista',
    nivelAcademico: '',
    colegio: 'Saint Georges College',
    universidad: 'U. Católica',
    biografia:
      'Carlos Montes (75) es senador por la Región Metropolitana. Tiene una larga carrera política que incluye además seis periodos parlamentarios consecutivos como diputado. Es egresado de Ingeniería Comercial de la Universidad Católica y fue presidente del Senado en 2018.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/6NH7yDdiMiLjySCEJLRIgJ3YNa0=/arc-anglerfish-arc2-prod-copesa/public/AEZON37O3NDPRJNNFZ6PBOVVHE.jpg',
  },
  {
    nombre: 'Maya Fernández',
    cargo: 'Ministerio de Agricultura',
    edad: '50',
    partido: 'Partido Socialista',
    profesion: 'Bióloga y Médico Veterinaria ',
    nivelAcademico: '',
    colegio: '',
    universidad: 'U. de Chile',
    biografia:
      'Maya Fernández es militante del Partido Socialista. Tiene dos títulos profesionales: es bióloga y veterinaria. Es nieta del expresidente Salvador Allende y sobrina de la senadora Isabel Allende. Vivió en el exilio en Cuba desde 1973 hasta 1990. Ha sido diputada por dos periodos y concejala de Ñuñoa. Presidió la Cámara en 2018. ',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/Dzldq_2ie99P4Bl7jEHQrsSmtuQ=/arc-anglerfish-arc2-prod-copesa/public/DYCRMNPXEZD5JL7LOC4NIFJEX4.jpg',
  },
  {
    nombre: 'Willy Kracht',
    cargo: 'Ministerio de Minería',
    edad: '42',
    partido: 'Ex PS, Convergencia Social',
    profesion: 'Ingeniero Civil Químico',
    nivelAcademico: 'PhD in Mining and Materials Engineering',
    colegio: '',
    universidad: 'U. de Chile',
    biografia: '',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/OYLTFdKg_jqaLjTtM7Iowek4wzs=/arc-anglerfish-arc2-prod-copesa/public/GB4KVLIH55CVNKUZVLRHCNJOQ4.jpg',
  },
  {
    nombre: 'Cristóbal Pineda',
    cargo: 'Ministerio de Transportes y Telecomunicaciones',
    edad: '34',
    partido: '',
    profesion: 'Ingeniero Civil',
    nivelAcademico: 'Magíster en Economía y MSc en Economía ',
    colegio: 'Instituto Nacional, Santiago',
    universidad: 'U. de Chile',
    biografia: '',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/6GXIhcwT0ftwB2UyJYcnAVlGuqI=/arc-anglerfish-arc2-prod-copesa/public/VW5GMMFYDJBNTOXUFR5Y5GVMFQ.jpg',
  },
  {
    nombre: 'Javiera Toro',
    cargo: 'Ministerio de Bienes Nacionales',
    edad: '34',
    partido: 'Comunes',
    profesion: 'Abogada',
    nivelAcademico: '',
    colegio: 'Colegio la Girouette, Las Condes',
    universidad: 'U. de Chile',
    biografia:
      'Javiera Toro es abogada de la Universidad de Chile. Fue presidenta de Comunes y es directora de la Fundación Nodo XXI. Ha trabajado como abogada en estudios privados.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/A1GGYZSMY2_lh2hsz4TaCarLMIM=/arc-anglerfish-arc2-prod-copesa/public/IVB4HZGVDVARHBKZZIAKHNDN7Q.jpg',
  },
  {
    nombre: 'Diego Pardow',
    cargo: 'Ministerio de Energía',
    edad: '41',
    partido: '',
    profesion: 'Abogado',
    nivelAcademico: 'Magister y Doctor en Derecho',
    colegio: "Colegio Granville's College",
    universidad: 'U. de Chile',
    biografia:
      'Diego Pardow es abogado de la Universidad de Chile. Además tiene un magíster y un doctorado en Derecho en la Universidad de California, Berkeley. Su carrera ha sido principalmente académica, siendo profesor de la Facultad de Derecho de la Universidad de Chile. A su vez es director ejecutivo de Espacio Público, cargo que tiene suspendido. Es cercano a Convergencia Social y un asesor cercano de Boric. Durante su campaña fue vocero de la candidatura y además ejerció como uno de los coordinadores programáticos.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/3IsPdRVeyakbbGGy1OChoLc2O5I=/arc-anglerfish-arc2-prod-copesa/public/5KSKZM7KINBEPKPKTWZDXLBKQQ.jpg',
  },
  {
    nombre: 'Ezio Costa',
    cargo: 'Ministerio de Medio Ambiente',
    edad: '38',
    partido: '',
    profesion: 'Abogado',
    nivelAcademico: 'Magíster en Regulación y Doctor en Derecho',
    colegio: 'Colegio Scuola Italiana, Las Condes',
    universidad: 'U. de Chile',
    biografia: '',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/qj-76bwfY8O6H-sDIlE3jndhOzk=/arc-anglerfish-arc2-prod-copesa/public/RH5DJS7ILRASTFFWZW4CEH4VP4.jpg',
  },
  {
    nombre: 'Pablo Paredes',
    cargo: 'Ministerio de las Culturas, las Artes y el Patrimonio',
    edad: '39',
    partido: 'Revolución Democrática',
    profesion: 'Comunicaciones',
    nivelAcademico: 'Magíster en Comunicación Política',
    colegio: 'Liceo Manuel Barros Borgoño, Santiago',
    universidad: 'U. de Santiago',
    biografia:
      'Pablo Paredes (39) es militante de Revolución Democrática. Fue el coordinador general de ese partido en 2014, antes de que se constituyera como un partido político. Estudió comunicaciones en la Universidad de Santiago y es magíster en Comunicación Política de la Universidad de Chile. Es guionista y ha trabajado en la parte creativa y audiovisual de campañas políticas, como la de Beatriz Sánchez en 2017 y la del Presidente electo.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/v_ephzboMXhUQ_9KC6D9cfH8pME=/arc-anglerfish-arc2-prod-copesa/public/OKV65X6YIVEJZAZVP5SEOBFYUQ.jpg',
  },
  {
    nombre: 'Fernando Monsalve',
    cargo: 'Ministerio de Deporte',
    edad: '41',
    partido: 'Partido Comunista',
    profesion: 'Abogado',
    nivelAcademico: 'Magister politica y gobierno',
    colegio: 'Colegio San Ignacio, Santiago',
    universidad: 'U. Diego Portales',
    biografia:
      'Fernando Monsalve es un abogado penalista militante del Partido Comunista. Fue candidato a diputado por el distrito 12, pero perdió. Fue presidente del Club Social y Deportivo de Colo Colo. Como penalista ha sido querellante de varias causas emblemáticas como el caso del adolescente que cayó al Río Mapocho o también en la causa que llevó el exfiscal Manuel Guerra contra el Presidente Sebastián Piñera por la minera Dominga.',
    url: 'https://google.com/',
    foto: '',
  },
  {
    nombre: 'Luna Follegati',
    cargo: 'Ministerio de la Mujer y la Equidad de Género',
    edad: '38',
    partido: 'Convergencia Social',
    profesion: 'Historiadora',
    nivelAcademico: 'Doctora en Filosofía',
    colegio: 'Colegio San Juan Evangelista',
    universidad: 'U. de Chile',
    biografia:
      'Luna Follegati (38) es una historiadora de la Universidad de Chile. Además tiene un magíster en Comunicación Política y un doctorado en Filosofía en esa misma casa de estudios. Además es académica de la Universidad Metropolitana de Ciencias de la Educación. Es militante de Convergencia Social y una de las principales referentes actuales del feminismo. Fue la encargada de hacerle clases sobre esta materia a Boric al inicio de la campaña presidencial.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/wZV0zqR7LBeWrg_FJAbt1osQEZA=/arc-anglerfish-arc2-prod-copesa/public/DALODAMPFVDSJDFDQJHBF53XDA.jpg',
  },
  {
    nombre: 'Maisa Rojas',
    cargo: 'Ministerio de Ciencia, Tecnología, Conocimiento e Innovación',
    edad: '49',
    partido: '',
    profesion: 'Licenciatura en Física ',
    nivelAcademico: 'Doctorado en Física de la Atmósfera',
    colegio: '',
    universidad: 'U. de Chile',
    biografia:
      'Maisa Rojas (49) es una reconocida climatóloga chilena. Es independiente. También es académica de la Universidad de Chile y Directora del Centro de Ciencia del Clima y la Resiliencia. Estudió física en la Universidad de Chile y un doctorado en física atmosférica en la Universidad de Oxford. Fue una de las autoras del informe del Panel Intergubernamental de Cambio Climático (IPCC). También se desempeñó como coordinadora del comité científico asesor para la COP25.',
    url: 'https://google.com/',
    foto:
      'https://www.latercera.com/resizer/Kcm_ooxNhoZ1RYv3veB-pbAKkkY=/arc-anglerfish-arc2-prod-copesa/public/ILBYZQBH5JGPRCRIBCDXX5CVX4.jpg',
  },
]

export default fichas
