/* Generated by ai2react v0.102.0 - 2022-03-11 22:14 */
/* ai file: amigos-trazado.ai */

import { makeAi2React } from '../src'
const img0 =
  'https://especiales.latercera.com/boric-presidente-assets/v3/amigos-trazado-large.jpg'
const img1 =
  'https://especiales.latercera.com/boric-presidente-assets/v3/amigos-trazado-small.jpg'

const styles = `
  #g-amigos-trazado-box ,
  #g-amigos-trazado-box .g-artboard {
    margin:0 auto;
  }
  #g-amigos-trazado-box p {
    margin:0;
  }
  #g-amigos-trazado-box .g-aiAbs {
    position:absolute;
  }
  #g-amigos-trazado-box .g-aiImg {
    position:absolute;
    top:0;
    display:block;
    width:100% !important;
  }
  #g-amigos-trazado-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-amigos-trazado-box .g-aiPointText p { white-space: nowrap; }
  #g-amigos-trazado-large {
    position:relative;
    overflow:hidden;
  }
  #g-amigos-trazado-large p {
    font-weight:500;
    line-height:56px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:47px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-amigos-trazado-large .g-pstyle0 {
    height:56px;
  }
  #g-amigos-trazado-small {
    position:relative;
    overflow:hidden;
  }
  #g-amigos-trazado-small p {
    font-weight:500;
    line-height:19px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:16px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-amigos-trazado-small .g-pstyle0 {
    height:19px;
  }

`

const html = props => `
<div id="g-amigos-trazado-box" class="ai2html">


  <!-- Artboard: large -->
  <div id="g-amigos-trazado-large" class="g-artboard" style="width:1280px; height:2262.1201171875px;" data-aspect-ratio="0.566" data-min-width="1280">
<div style=""></div>
    <img id="g-amigos-trazado-large-img" class="g-aiImg" alt="" src="${img0}"/>
    <div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:4.1821%;margin-top:-29.6px;left:3.8081%;width:229px;">
      <p class="g-pstyle0">Boricismo</p>
    </div>
  </div>

  <!-- Artboard: small -->
  <div id="g-amigos-trazado-small" class="g-artboard" style="max-width: 360px;max-height: 1915px" data-aspect-ratio="0.188" data-min-width="0" data-max-width="1279">
<div style="padding: 0 0 531.9278% 0;"></div>
    <img id="g-amigos-trazado-small-img" class="g-aiImg" alt="" src="${img1}"/>
    <div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:1.7714%;margin-top:-9.9px;left:9.0549%;width:91px;">
      <p class="g-pstyle0">Boricismo</p>
    </div>
  </div>


</div>
`

const containerId = 'g-amigos-trazado-box'
const namespace = 'g-'
const name = 'amigos-trazado'

export default makeAi2React({ html, styles, containerId, namespace, name })

/* End ai2react - 2022-03-11 22:14 */
