/* Generated by ai2react v0.102.0 - 2022-03-11 09:52 */
/* ai file: fichapersonal.ai */

import { makeAi2React } from '../src'
const img0 =
  'https://especiales.latercera.com/boric-presidente-assets/v3/fichapersonal-small.jpg'
const img1 =
  'https://especiales.latercera.com/boric-presidente-assets/v3/fichapersonal-large.jpg'

const styles = `
  #g-fichapersonal-box ,
  #g-fichapersonal-box .g-artboard {
    margin:0 auto;
  }
  #g-fichapersonal-box p {
    margin:0;
  }
  #g-fichapersonal-box .g-aiAbs {
    position:absolute;
  }
  #g-fichapersonal-box .g-aiImg {
    position:absolute;
    top:0;
    display:block;
    width:100% !important;
  }
  #g-fichapersonal-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-fichapersonal-box .g-aiPointText p { white-space: nowrap; }
  #g-fichapersonal-small {
    position:relative;
    overflow:hidden;
  }
  #g-fichapersonal-small p {
    font-weight:500;
    line-height:31px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:26px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-fichapersonal-small .g-pstyle0 {
    line-height:46px;
    height:46px;
    font-size:38px;
  }
  #g-fichapersonal-small .g-pstyle1 {
    line-height:32px;
    height:32px;
    font-size:27px;
  }
  #g-fichapersonal-small .g-pstyle2 {
    height:31px;
  }
  #g-fichapersonal-small .g-cstyle0 {
    letter-spacing:-0.02em;
  }
  #g-fichapersonal-small .g-cstyle1 {
    letter-spacing:-0.019em;
  }
  #g-fichapersonal-small .g-cstyle2 {
    letter-spacing:-0.004em;
  }
  #g-fichapersonal-small .g-cstyle3 {
    letter-spacing:-0.018em;
  }
  #g-fichapersonal-small .g-cstyle4 {
    letter-spacing:-0.025em;
  }
  #g-fichapersonal-small .g-cstyle5 {
    letter-spacing:-0.014em;
  }
  #g-fichapersonal-small .g-cstyle6 {
    letter-spacing:-0.005em;
  }
  #g-fichapersonal-small .g-cstyle7 {
    letter-spacing:0.005em;
  }
  #g-fichapersonal-small .g-cstyle8 {
    letter-spacing:-0.079em;
  }
  #g-fichapersonal-small .g-cstyle9 {
    letter-spacing:-0.013em;
  }
  #g-fichapersonal-small .g-cstyle10 {
    letter-spacing:-0.017em;
  }
  #g-fichapersonal-small .g-cstyle11 {
    letter-spacing:0.01em;
  }
  #g-fichapersonal-small .g-cstyle12 {
    letter-spacing:-0.038em;
  }
  #g-fichapersonal-small .g-cstyle13 {
    letter-spacing:-0.063em;
  }
  #g-fichapersonal-small .g-cstyle14 {
    letter-spacing:0.039em;
  }
  #g-fichapersonal-small .g-cstyle15 {
    letter-spacing:-0.049em;
  }
  #g-fichapersonal-small .g-cstyle16 {
    letter-spacing:-0.006em;
  }
  #g-fichapersonal-small .g-cstyle17 {
    letter-spacing:-0.011em;
  }
  #g-fichapersonal-small .g-cstyle18 {
    letter-spacing:-0.029em;
  }
  #g-fichapersonal-small .g-cstyle19 {
    letter-spacing:-0.024em;
  }
  #g-fichapersonal-small .g-cstyle20 {
    letter-spacing:-0.009em;
  }
  #g-fichapersonal-small .g-cstyle21 {
    letter-spacing:0.004em;
  }
  #g-fichapersonal-small .g-cstyle22 {
    letter-spacing:-0.032em;
  }
  #g-fichapersonal-small .g-cstyle23 {
    letter-spacing:-0.008em;
  }
  #g-fichapersonal-small .g-cstyle24 {
    letter-spacing:-0.015em;
  }
  #g-fichapersonal-small .g-cstyle25 {
    letter-spacing:-0.06em;
  }
  #g-fichapersonal-small .g-cstyle26 {
    letter-spacing:0.007em;
  }
  #g-fichapersonal-small .g-cstyle27 {
    letter-spacing:-0.01em;
  }
  #g-fichapersonal-small .g-cstyle28 {
    letter-spacing:-0.047em;
  }
  #g-fichapersonal-large {
    position:relative;
    overflow:hidden;
  }
  #g-fichapersonal-large p {
    font-weight:500;
    line-height:31px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:26px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-fichapersonal-large .g-pstyle0 {
    line-height:47px;
    height:47px;
    font-size:39px;
  }
  #g-fichapersonal-large .g-pstyle1 {
    line-height:32px;
    height:32px;
    font-size:27px;
  }
  #g-fichapersonal-large .g-pstyle2 {
    height:31px;
  }
  #g-fichapersonal-large .g-cstyle0 {
    letter-spacing:-0.019em;
  }
  #g-fichapersonal-large .g-cstyle1 {
    letter-spacing:-0.02em;
  }
  #g-fichapersonal-large .g-cstyle2 {
    letter-spacing:-0.004em;
  }
  #g-fichapersonal-large .g-cstyle3 {
    letter-spacing:-0.018em;
  }
  #g-fichapersonal-large .g-cstyle4 {
    letter-spacing:-0.025em;
  }
  #g-fichapersonal-large .g-cstyle5 {
    letter-spacing:-0.014em;
  }
  #g-fichapersonal-large .g-cstyle6 {
    letter-spacing:-0.079em;
  }
  #g-fichapersonal-large .g-cstyle7 {
    letter-spacing:-0.013em;
  }
  #g-fichapersonal-large .g-cstyle8 {
    letter-spacing:-0.005em;
  }
  #g-fichapersonal-large .g-cstyle9 {
    letter-spacing:-0.017em;
  }
  #g-fichapersonal-large .g-cstyle10 {
    letter-spacing:-0.063em;
  }
  #g-fichapersonal-large .g-cstyle11 {
    letter-spacing:0.01em;
  }
  #g-fichapersonal-large .g-cstyle12 {
    letter-spacing:-0.038em;
  }
  #g-fichapersonal-large .g-cstyle13 {
    letter-spacing:0.039em;
  }
  #g-fichapersonal-large .g-cstyle14 {
    letter-spacing:-0.049em;
  }
  #g-fichapersonal-large .g-cstyle15 {
    letter-spacing:-0.006em;
  }
  #g-fichapersonal-large .g-cstyle16 {
    letter-spacing:-0.011em;
  }
  #g-fichapersonal-large .g-cstyle17 {
    letter-spacing:0.005em;
  }
  #g-fichapersonal-large .g-cstyle18 {
    letter-spacing:-0.029em;
  }
  #g-fichapersonal-large .g-cstyle19 {
    letter-spacing:-0.008em;
  }
  #g-fichapersonal-large .g-cstyle20 {
    letter-spacing:-0.015em;
  }
  #g-fichapersonal-large .g-cstyle21 {
    letter-spacing:-0.06em;
  }
  #g-fichapersonal-large .g-cstyle22 {
    letter-spacing:-0.024em;
  }
  #g-fichapersonal-large .g-cstyle23 {
    letter-spacing:-0.009em;
  }
  #g-fichapersonal-large .g-cstyle24 {
    letter-spacing:0.004em;
  }
  #g-fichapersonal-large .g-cstyle25 {
    letter-spacing:0.007em;
  }
  #g-fichapersonal-large .g-cstyle26 {
    letter-spacing:-0.01em;
  }
  #g-fichapersonal-large .g-cstyle27 {
    letter-spacing:-0.032em;
  }
  #g-fichapersonal-large .g-cstyle28 {
    letter-spacing:-0.047em;
  }

`

const html = props => `
<div id="g-fichapersonal-box" class="ai2html">


  <!-- Artboard: small -->
  <div id="g-fichapersonal-small" class="g-artboard" style="max-width: 360px;max-height: 3195px" data-aspect-ratio="0.113" data-min-width="0" data-max-width="1279">
<div style="padding: 0 0 887.5416% 0;"></div>
    <img id="g-fichapersonal-small-img" class="g-aiImg" alt="" src="${img0}"/>
    <div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:2.2688%;margin-top:-24.5px;left:4.2535%;width:154px;">
      <p class="g-pstyle0">FICHA </p>
    </div>
    <div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:3.6772%;margin-top:-24.5px;left:4.2535%;width:229px;">
      <p class="g-pstyle0">PERSO<span class="g-cstyle0">N</span>AL</p>
    </div>
    <div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:6.0736%;margin-top:-17.1px;left:3.6979%;width:308px;">
      <p class="g-pstyle1">NOMBRE COMPLETO</p>
    </div>
    <div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:7.7503%;margin-top:-17.6px;left:22.407%;width:218px;">
      <p class="g-pstyle2">Gabriel Boric <span class="g-cstyle1">F</span>ont</p>
    </div>
    <div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:10.017%;margin-top:-17.1px;left:3.6979%;width:352px;">
      <p class="g-pstyle1">FECHA DE <span class="g-cstyle0">N</span><span class="g-cstyle2">A</span>CIMIENTO</p>
    </div>
    <div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:11.7563%;margin-top:-17.6px;left:22.407%;width:272px;">
      <p class="g-pstyle2"><span class="g-cstyle3">1</span>1 de <span class="g-cstyle4">f</span>ebre<span class="g-cstyle1">r</span>o de <span class="g-cstyle5">1</span>986</p>
    </div>
    <div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:14.3048%;margin-top:-17.1px;left:3.6979%;width:101px;">
      <p class="g-pstyle1">E<span class="g-cstyle1">D</span>AD</p>
    </div>
    <div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:15.7937%;margin-top:-17.6px;left:22.407%;width:112px;">
      <p class="g-pstyle2">36 años</p>
    </div>
    <div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:17.8796%;margin-top:-18.3px;left:3.6979%;width:183px;">
      <p class="g-pstyle1">PROFESIÓN</p>
    </div>
    <div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.299%;margin-top:-17.6px;left:22.407%;width:291px;">
      <p class="g-pstyle2">Egresado de Derecho de</p>
    </div>
    <div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:20.3005%;margin-top:-17.6px;left:22.407%;width:272px;">
      <p class="g-pstyle2">la <span class="g-cstyle6">U</span>ni<span class="g-cstyle5">v</span>e<span class="g-cstyle7">r</span>sidad de Chile</p>
    </div>
    <div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:22.0109%;margin-top:-18.3px;left:3.6979%;width:341px;">
      <p class="g-pstyle1">OCU<span class="g-cstyle8">P</span><span class="g-cstyle2">A</span>CIÓN ANTERIOR</p>
    </div>
    <div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:23.8059%;margin-top:-17.6px;left:22.4067%;width:122px;">
      <p class="g-pstyle2">Diputado</p>
    </div>
    <div id="g-ai0-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.8222%;margin-top:-17.1px;left:3.6979%;width:129px;">
      <p class="g-pstyle1"><span class="g-cstyle8">P</span>ADRES</p>
    </div>
    <div id="g-ai0-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:27.1547%;margin-top:-17.6px;left:22.407%;width:219px;">
      <p class="g-pstyle2"><span class="g-cstyle9">L</span>uis Boric Sca<span class="g-cstyle6">r</span>pa </p>
    </div>
    <div id="g-ai0-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.1562%;margin-top:-17.6px;left:22.407%;width:242px;">
      <p class="g-pstyle2">(75 años, Ingenie<span class="g-cstyle10">r</span>o </p>
    </div>
    <div id="g-ai0-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.1577%;margin-top:-17.6px;left:22.407%;width:119px;">
      <p class="g-pstyle2">Químico)</p>
    </div>
    <div id="g-ai0-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.4722%;margin-top:-17.6px;left:22.407%;width:188px;">
      <p class="g-pstyle2">María Soledad </p>
    </div>
    <div id="g-ai0-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:31.4737%;margin-top:-17.6px;left:22.407%;width:172px;">
      <p class="g-pstyle2"><span class="g-cstyle1">F</span>ont <span class="g-cstyle11">A</span>guilera </p>
    </div>
    <div id="g-ai0-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:32.4752%;margin-top:-17.6px;left:22.407%;width:127px;">
      <p class="g-pstyle2">(<span class="g-cstyle12">6</span>1 años)</p>
    </div>
    <div id="g-ai0-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:34.3977%;margin-top:-17.1px;left:3.6979%;width:185px;">
      <p class="g-pstyle1">HERMANOS</p>
    </div>
    <div id="g-ai0-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.8241%;margin-top:-17.6px;left:22.407%;width:209px;">
      <p class="g-pstyle2">Simón Boric <span class="g-cstyle3">F</span>ont</p>
    </div>
    <div id="g-ai0-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:36.8256%;margin-top:-17.6px;left:22.407%;width:250px;">
      <p class="g-pstyle2">(33 años, <span class="g-cstyle5">P</span>eriodista)</p>
    </div>
    <div id="g-ai0-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:38.234%;margin-top:-17.6px;left:22.407%;width:211px;">
      <p class="g-pstyle2"><span class="g-cstyle13">T</span>omás Boric <span class="g-cstyle0">F</span>ont</p>
    </div>
    <div id="g-ai0-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.2355%;margin-top:-17.6px;left:22.407%;width:128px;">
      <p class="g-pstyle2">(29 años)</p>
    </div>
    <div id="g-ai0-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:41.0641%;margin-top:-17.1px;left:3.6979%;width:126px;">
      <p class="g-pstyle1"><span class="g-cstyle8">P</span>AR<span class="g-cstyle14">E</span><span class="g-cstyle15">J</span>A</p>
    </div>
    <div id="g-ai0-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.3965%;margin-top:-17.6px;left:22.407%;width:281px;">
      <p class="g-pstyle2">Irina <span class="g-cstyle16">K</span>aramanos <span class="g-cstyle17">A</span>drian</p>
    </div>
    <div id="g-ai0-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.3981%;margin-top:-17.6px;left:22.407%;width:256px;">
      <p class="g-pstyle2">32 años, Ant<span class="g-cstyle3">r</span>opóloga</p>
    </div>
    <div id="g-ai0-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:45.4457%;margin-top:-17.1px;left:3.6979%;width:354px;">
      <p class="g-pstyle1"><span class="g-cstyle1">L</span>UGAR DE <span class="g-cstyle1">N</span><span class="g-cstyle2">A</span>CIMIENTO</p>
    </div>
    <div id="g-ai0-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.2476%;margin-top:-17.6px;left:22.4067%;width:169px;">
      <p class="g-pstyle2">Punta Arenas</p>
    </div>
    <div id="g-ai0-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.7335%;margin-top:-17.1px;left:3.6979%;width:312px;">
      <p class="g-pstyle1">COLEGIO DE EGRESO</p>
    </div>
    <div id="g-ai0-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:51.3789%;margin-top:-17.6px;left:22.407%;width:219px;">
      <p class="g-pstyle2">The British School</p>
    </div>
    <div id="g-ai0-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.3804%;margin-top:-17.6px;left:22.407%;width:203px;">
      <p class="g-pstyle2">de Punta Arenas</p>
    </div>
    <div id="g-ai0-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:54.6785%;margin-top:-17.1px;left:3.6979%;width:203px;">
      <p class="g-pstyle1"><span class="g-cstyle8">P</span><span class="g-cstyle18">A</span>TRIMONIO</p>
    </div>
    <div id="g-ai0-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:56.0735%;margin-top:-17.6px;left:22.407%;width:204px;">
      <p class="g-pstyle2"><span class="g-cstyle2">U</span>n <span class="g-cstyle10">t</span>erreno en la </p>
    </div>
    <div id="g-ai0-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:57.075%;margin-top:-17.6px;left:22.407%;width:262px;">
      <p class="g-pstyle2">comuna de Dalcahue </p>
    </div>
    <div id="g-ai0-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:58.0765%;margin-top:-17.6px;left:22.407%;width:246px;">
      <p class="g-pstyle2">con un <span class="g-cstyle19">a</span><span class="g-cstyle20">v</span>alúo <span class="g-cstyle21">f</span>iscal </p>
    </div>
    <div id="g-ai0-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:59.0781%;margin-top:-17.6px;left:22.407%;width:210px;">
      <p class="g-pstyle2">de $ 12<span class="g-cstyle12">.</span><span class="g-cstyle3">1</span><span class="g-cstyle22">1</span>0.823</p>
    </div>
    <div id="g-ai0-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:60.8933%;margin-top:-17.6px;left:22.407%;width:229px;">
      <p class="g-pstyle2"><span class="g-cstyle2">U</span>na m<span class="g-cstyle23">o</span><span class="g-cstyle24">t</span>o <span class="g-cstyle25">Y</span>amaha </p>
    </div>
    <div id="g-ai0-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:61.8948%;margin-top:-17.6px;left:22.407%;width:246px;">
      <p class="g-pstyle2">con un <span class="g-cstyle19">a</span><span class="g-cstyle20">v</span>alúo <span class="g-cstyle21">f</span>iscal </p>
    </div>
    <div id="g-ai0-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.8964%;margin-top:-17.6px;left:22.407%;width:176px;">
      <p class="g-pstyle2">de $ 702.<span class="g-cstyle26">4</span>49</p>
    </div>
    <div id="g-ai0-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.7429%;margin-top:-17.6px;left:23.0279%;width:232px;">
      <p class="g-pstyle2"><span class="g-cstyle1">F</span>ondos mutuos en </p>
    </div>
    <div id="g-ai0-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:65.7444%;margin-top:-17.6px;left:23.0279%;width:245px;">
      <p class="g-pstyle2">el Banco Santander </p>
    </div>
    <div id="g-ai0-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.7459%;margin-top:-17.6px;left:23.0279%;width:197px;">
      <p class="g-pstyle2">con un <span class="g-cstyle27">v</span>alor de </p>
    </div>
    <div id="g-ai0-45" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.7475%;margin-top:-17.6px;left:23.0279%;width:177px;">
      <p class="g-pstyle2">$ <span class="g-cstyle28">3</span><span class="g-cstyle16">1</span>.223.320</p>
    </div>
  </div>

  <!-- Artboard: large -->
  <div id="g-fichapersonal-large" class="g-artboard" style="width:1280px; height:1208.66003417969px;" data-aspect-ratio="1.059" data-min-width="1280">
<div style=""></div>
    <img id="g-fichapersonal-large-img" class="g-aiImg" alt="" src="${img1}"/>
    <div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:7.2833%;margin-top:-25px;left:2.9968%;width:370px;">
      <p class="g-pstyle0">FICHA PERSO<span class="g-cstyle0">N</span>AL</p>
    </div>
    <div id="g-ai1-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:12.9945%;margin-top:-17.1px;left:2.9968%;width:308px;">
      <p class="g-pstyle1">NOMBRE COMPLETO</p>
    </div>
    <div id="g-ai1-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:12.9945%;margin-top:-17.1px;left:34.9982%;width:352px;">
      <p class="g-pstyle1">FECHA DE <span class="g-cstyle1">N</span><span class="g-cstyle2">A</span>CIMIENTO</p>
    </div>
    <div id="g-ai1-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:17.427%;margin-top:-17.6px;left:8.7299%;width:218px;">
      <p class="g-pstyle2">Gabriel Boric <span class="g-cstyle0">F</span>ont</p>
    </div>
    <div id="g-ai1-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:17.6752%;margin-top:-17.6px;left:41.1974%;width:272px;">
      <p class="g-pstyle2"><span class="g-cstyle3">1</span>1 de <span class="g-cstyle4">f</span>ebre<span class="g-cstyle0">r</span>o de <span class="g-cstyle5">1</span>986</p>
    </div>
    <div id="g-ai1-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:23.934%;margin-top:-18.3px;left:34.9982%;width:341px;">
      <p class="g-pstyle1">OCU<span class="g-cstyle6">P</span><span class="g-cstyle2">A</span>CIÓN ANTERIOR</p>
    </div>
    <div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:23.833%;margin-top:-17.1px;left:2.9969%;width:101px;">
      <p class="g-pstyle1">E<span class="g-cstyle0">D</span>AD</p>
    </div>
    <div id="g-ai1-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.4309%;margin-top:-17.6px;left:8.7299%;width:112px;">
      <p class="g-pstyle2">36 años</p>
    </div>
    <div id="g-ai1-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.7618%;margin-top:-17.6px;left:41.1969%;width:122px;">
      <p class="g-pstyle2">Diputado</p>
    </div>
    <div id="g-ai1-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.9268%;margin-top:-17.1px;left:2.9969%;width:129px;">
      <p class="g-pstyle1"><span class="g-cstyle6">P</span>ADRES</p>
    </div>
    <div id="g-ai1-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.9268%;margin-top:-17.1px;left:34.9982%;width:185px;">
      <p class="g-pstyle1">HERMANOS</p>
    </div>
    <div id="g-ai1-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.7801%;margin-top:-17.6px;left:8.7299%;width:219px;">
      <p class="g-pstyle2"><span class="g-cstyle7">L</span>uis Boric Sca<span class="g-cstyle8">r</span>pa </p>
    </div>
    <div id="g-ai1-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.7801%;margin-top:-17.6px;left:41.1974%;width:209px;">
      <p class="g-pstyle2">Simón Boric <span class="g-cstyle3">F</span>ont</p>
    </div>
    <div id="g-ai1-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.4276%;margin-top:-17.6px;left:8.7299%;width:242px;">
      <p class="g-pstyle2">(75 años, Ingenie<span class="g-cstyle9">r</span>o </p>
    </div>
    <div id="g-ai1-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.4276%;margin-top:-17.6px;left:41.1974%;width:250px;">
      <p class="g-pstyle2">(33 años, <span class="g-cstyle5">P</span>eriodista)</p>
    </div>
    <div id="g-ai1-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.0752%;margin-top:-17.6px;left:8.7299%;width:119px;">
      <p class="g-pstyle2">Químico)</p>
    </div>
    <div id="g-ai1-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.3163%;margin-top:-17.6px;left:41.1974%;width:211px;">
      <p class="g-pstyle2"><span class="g-cstyle10">T</span>omás Boric <span class="g-cstyle1">F</span>ont</p>
    </div>
    <div id="g-ai1-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.9638%;margin-top:-17.6px;left:41.1974%;width:128px;">
      <p class="g-pstyle2">(29 años)</p>
    </div>
    <div id="g-ai1-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.0465%;margin-top:-17.6px;left:8.7299%;width:188px;">
      <p class="g-pstyle2">María Soledad </p>
    </div>
    <div id="g-ai1-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.6941%;margin-top:-17.6px;left:8.7299%;width:172px;">
      <p class="g-pstyle2"><span class="g-cstyle0">F</span>ont <span class="g-cstyle11">A</span>guilera </p>
    </div>
    <div id="g-ai1-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.3417%;margin-top:-17.6px;left:8.7299%;width:127px;">
      <p class="g-pstyle2">(<span class="g-cstyle12">6</span>1 años)</p>
    </div>
    <div id="g-ai1-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:56.4311%;margin-top:-17.1px;left:2.9969%;width:126px;">
      <p class="g-pstyle1"><span class="g-cstyle6">P</span>AR<span class="g-cstyle13">E</span><span class="g-cstyle14">J</span>A</p>
    </div>
    <div id="g-ai1-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:56.4311%;margin-top:-17.1px;left:34.9982%;width:354px;">
      <p class="g-pstyle1"><span class="g-cstyle0">L</span>UGAR DE <span class="g-cstyle0">N</span><span class="g-cstyle2">A</span>CIMIENTO</p>
    </div>
    <div id="g-ai1-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:60.1189%;margin-top:-17.6px;left:8.7299%;width:281px;">
      <p class="g-pstyle2">Irina <span class="g-cstyle15">K</span>aramanos <span class="g-cstyle16">A</span>drian</p>
    </div>
    <div id="g-ai1-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:61.6081%;margin-top:-17.6px;left:41.1969%;width:169px;">
      <p class="g-pstyle2">Punta Arenas</p>
    </div>
    <div id="g-ai1-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.7664%;margin-top:-17.6px;left:8.7299%;width:256px;">
      <p class="g-pstyle2">32 años, Ant<span class="g-cstyle3">r</span>opóloga</p>
    </div>
    <div id="g-ai1-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:68.676%;margin-top:-17.1px;left:34.9982%;width:312px;">
      <p class="g-pstyle1">COLEGIO DE EGRESO</p>
    </div>
    <div id="g-ai1-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:68.7771%;margin-top:-18.3px;left:2.9969%;width:183px;">
      <p class="g-pstyle1">PROFESIÓN</p>
    </div>
    <div id="g-ai1-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:72.5293%;margin-top:-17.6px;left:41.1969%;width:219px;">
      <p class="g-pstyle2">The British School</p>
    </div>
    <div id="g-ai1-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:72.5293%;margin-top:-17.6px;left:8.7299%;width:291px;">
      <p class="g-pstyle2">Egresado de Derecho de</p>
    </div>
    <div id="g-ai1-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.1769%;margin-top:-17.6px;left:41.1969%;width:203px;">
      <p class="g-pstyle2">de Punta Arenas</p>
    </div>
    <div id="g-ai1-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.1769%;margin-top:-17.6px;left:8.7299%;width:272px;">
      <p class="g-pstyle2">la <span class="g-cstyle8">U</span>ni<span class="g-cstyle5">v</span>e<span class="g-cstyle17">r</span>sidad de Chile</p>
    </div>
    <div id="g-ai1-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.921%;margin-top:-17.1px;left:2.7544%;width:203px;">
      <p class="g-pstyle1"><span class="g-cstyle6">P</span><span class="g-cstyle18">A</span>TRIMONIO</p>
    </div>
    <div id="g-ai1-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.3606%;margin-top:-17.6px;left:7.5193%;width:204px;">
      <p class="g-pstyle2"><span class="g-cstyle2">U</span>n <span class="g-cstyle9">t</span>erreno en la </p>
    </div>
    <div id="g-ai1-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.3606%;margin-top:-17.6px;left:33.1821%;width:229px;">
      <p class="g-pstyle2"><span class="g-cstyle2">U</span>na m<span class="g-cstyle19">o</span><span class="g-cstyle20">t</span>o <span class="g-cstyle21">Y</span>amaha </p>
    </div>
    <div id="g-ai1-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.3606%;margin-top:-17.6px;left:56.9802%;width:232px;">
      <p class="g-pstyle2"><span class="g-cstyle0">F</span>ondos mutuos en </p>
    </div>
    <div id="g-ai1-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.0082%;margin-top:-17.6px;left:7.5193%;width:262px;">
      <p class="g-pstyle2">comuna de Dalcahue </p>
    </div>
    <div id="g-ai1-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.0082%;margin-top:-17.6px;left:33.1821%;width:246px;">
      <p class="g-pstyle2">con un <span class="g-cstyle22">a</span><span class="g-cstyle23">v</span>alúo <span class="g-cstyle24">f</span>iscal </p>
    </div>
    <div id="g-ai1-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.0082%;margin-top:-17.6px;left:56.9802%;width:245px;">
      <p class="g-pstyle2">el Banco Santander </p>
    </div>
    <div id="g-ai1-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:89.6557%;margin-top:-17.6px;left:7.5193%;width:246px;">
      <p class="g-pstyle2">con un <span class="g-cstyle22">a</span><span class="g-cstyle23">v</span>alúo <span class="g-cstyle24">f</span>iscal </p>
    </div>
    <div id="g-ai1-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:89.6557%;margin-top:-17.6px;left:33.1821%;width:176px;">
      <p class="g-pstyle2">de $ 702.<span class="g-cstyle25">4</span>49</p>
    </div>
    <div id="g-ai1-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:89.6557%;margin-top:-17.6px;left:56.9802%;width:197px;">
      <p class="g-pstyle2">con un <span class="g-cstyle26">v</span>alor de </p>
    </div>
    <div id="g-ai1-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:92.3033%;margin-top:-17.6px;left:7.5193%;width:210px;">
      <p class="g-pstyle2">de $ 12<span class="g-cstyle12">.</span><span class="g-cstyle3">1</span><span class="g-cstyle27">1</span>0.823</p>
    </div>
    <div id="g-ai1-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:92.3033%;margin-top:-17.6px;left:56.9802%;width:177px;">
      <p class="g-pstyle2">$ <span class="g-cstyle28">3</span><span class="g-cstyle15">1</span>.223.320</p>
    </div>
  </div>


</div>
`

const containerId = 'g-fichapersonal-box'
const namespace = 'g-'
const name = 'fichapersonal'

export default makeAi2React({ html, styles, containerId, namespace, name })

/* End ai2react - 2022-03-11 09:52 */
