/* Generated by ai2react v0.102.0 - 2022-03-11 09:52 */
/* ai file: historialvotaciones.ai */

import { makeAi2React } from '../src'
const img0 =
  'https://especiales.latercera.com/boric-presidente-assets/v3/historialvotaciones-large.jpg'
const img1 =
  'https://especiales.latercera.com/boric-presidente-assets/v3/historialvotaciones-small.jpg'

const styles = `
  #g-historialvotaciones-box ,
  #g-historialvotaciones-box .g-artboard {
    margin:0 auto;
  }
  #g-historialvotaciones-box p {
    margin:0;
  }
  #g-historialvotaciones-box .g-aiAbs {
    position:absolute;
  }
  #g-historialvotaciones-box .g-aiImg {
    position:absolute;
    top:0;
    display:block;
    width:100% !important;
  }
  #g-historialvotaciones-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-historialvotaciones-box .g-aiPointText p { white-space: nowrap; }
  #g-historialvotaciones-large {
    position:relative;
    overflow:hidden;
  }
  #g-historialvotaciones-large p {
    font-weight:500;
    line-height:24px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:20px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-historialvotaciones-large .g-pstyle0 {
    line-height:47px;
    height:47px;
    font-size:39px;
  }
  #g-historialvotaciones-large .g-pstyle1 {
    line-height:34px;
    height:34px;
    font-size:28px;
  }
  #g-historialvotaciones-large .g-pstyle2 {
    line-height:30px;
    height:30px;
    font-size:25px;
  }
  #g-historialvotaciones-large .g-pstyle3 {
    line-height:43px;
    height:43px;
    font-size:36px;
  }
  #g-historialvotaciones-large .g-pstyle4 {
    line-height:46px;
    height:46px;
    font-size:38px;
  }
  #g-historialvotaciones-large .g-pstyle5 {
    line-height:46px;
    height:46px;
    font-size:38px;
    color:rgb(255,255,255);
  }
  #g-historialvotaciones-large .g-pstyle6 {
    line-height:34px;
    height:34px;
    font-size:28px;
    color:rgb(255,255,255);
  }
  #g-historialvotaciones-large .g-pstyle7 {
    line-height:34px;
    height:34px;
    font-size:28px;
    color:rgb(31,67,124);
  }
  #g-historialvotaciones-large .g-pstyle8 {
    height:24px;
  }
  #g-historialvotaciones-large .g-cstyle0 {
    letter-spacing:-0.005em;
  }
  #g-historialvotaciones-large .g-cstyle1 {
    letter-spacing:-0.04em;
  }
  #g-historialvotaciones-large .g-cstyle2 {
    letter-spacing:-0.004em;
  }
  #g-historialvotaciones-large .g-cstyle3 {
    letter-spacing:-0.079em;
  }
  #g-historialvotaciones-large .g-cstyle4 {
    letter-spacing:-0.039em;
  }
  #g-historialvotaciones-large .g-cstyle5 {
    letter-spacing:-0.038em;
  }
  #g-historialvotaciones-large .g-cstyle6 {
    letter-spacing:-0.008em;
  }
  #g-historialvotaciones-large .g-cstyle7 {
    letter-spacing:-0.068em;
  }
  #g-historialvotaciones-large .g-cstyle8 {
    letter-spacing:-0.014em;
  }
  #g-historialvotaciones-large .g-cstyle9 {
    letter-spacing:-0.035em;
  }
  #g-historialvotaciones-large .g-cstyle10 {
    letter-spacing:-0.007em;
  }
  #g-historialvotaciones-large .g-cstyle11 {
    letter-spacing:0.001em;
  }
  #g-historialvotaciones-large .g-cstyle12 {
    letter-spacing:-0.02em;
  }
  #g-historialvotaciones-large .g-cstyle13 {
    letter-spacing:-0.019em;
  }
  #g-historialvotaciones-large .g-cstyle14 {
    letter-spacing:-0.03em;
  }
  #g-historialvotaciones-large .g-cstyle15 {
    letter-spacing:-0.009em;
  }
  #g-historialvotaciones-large .g-cstyle16 {
    letter-spacing:-0.029em;
  }
  #g-historialvotaciones-large .g-cstyle17 {
    letter-spacing:-0.059em;
  }
  #g-historialvotaciones-large .g-cstyle18 {
    letter-spacing:-0.015em;
  }
  #g-historialvotaciones-large .g-cstyle19 {
    letter-spacing:0.025em;
  }
  #g-historialvotaciones-large .g-cstyle20 {
    letter-spacing:-0.054em;
  }
  #g-historialvotaciones-large .g-cstyle21 {
    letter-spacing:-0.022em;
  }
  #g-historialvotaciones-large .g-cstyle22 {
    letter-spacing:-0.037em;
  }
  #g-historialvotaciones-large .g-cstyle23 {
    letter-spacing:-0.016em;
  }
  #g-historialvotaciones-large .g-cstyle24 {
    letter-spacing:-0.024em;
  }
  #g-historialvotaciones-large .g-cstyle25 {
    letter-spacing:-0.064em;
  }
  #g-historialvotaciones-small {
    position:relative;
    overflow:hidden;
  }
  #g-historialvotaciones-small p {
    font-weight:500;
    line-height:24px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:20px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-historialvotaciones-small .g-pstyle0 {
    line-height:46px;
    height:46px;
    font-size:38px;
  }
  #g-historialvotaciones-small .g-pstyle1 {
    line-height:34px;
    height:34px;
    font-size:28px;
  }
  #g-historialvotaciones-small .g-pstyle2 {
    line-height:30px;
    height:30px;
    font-size:25px;
  }
  #g-historialvotaciones-small .g-pstyle3 {
    line-height:43px;
    height:43px;
    font-size:36px;
  }
  #g-historialvotaciones-small .g-pstyle4 {
    line-height:46px;
    height:46px;
    font-size:38px;
    color:rgb(255,255,255);
  }
  #g-historialvotaciones-small .g-pstyle5 {
    line-height:34px;
    height:34px;
    font-size:28px;
    color:rgb(255,255,255);
  }
  #g-historialvotaciones-small .g-pstyle6 {
    line-height:34px;
    height:34px;
    font-size:28px;
    color:rgb(31,67,124);
  }
  #g-historialvotaciones-small .g-pstyle7 {
    height:24px;
  }
  #g-historialvotaciones-small .g-cstyle0 {
    letter-spacing:-0.005em;
  }
  #g-historialvotaciones-small .g-cstyle1 {
    letter-spacing:-0.04em;
  }
  #g-historialvotaciones-small .g-cstyle2 {
    letter-spacing:-0.004em;
  }
  #g-historialvotaciones-small .g-cstyle3 {
    letter-spacing:-0.079em;
  }
  #g-historialvotaciones-small .g-cstyle4 {
    letter-spacing:-0.038em;
  }
  #g-historialvotaciones-small .g-cstyle5 {
    letter-spacing:-0.008em;
  }
  #g-historialvotaciones-small .g-cstyle6 {
    letter-spacing:-0.014em;
  }
  #g-historialvotaciones-small .g-cstyle7 {
    letter-spacing:-0.019em;
  }
  #g-historialvotaciones-small .g-cstyle8 {
    letter-spacing:-0.029em;
  }
  #g-historialvotaciones-small .g-cstyle9 {
    letter-spacing:-0.068em;
  }
  #g-historialvotaciones-small .g-cstyle10 {
    letter-spacing:-0.035em;
  }
  #g-historialvotaciones-small .g-cstyle11 {
    letter-spacing:0.001em;
  }
  #g-historialvotaciones-small .g-cstyle12 {
    letter-spacing:-0.02em;
  }
  #g-historialvotaciones-small .g-cstyle13 {
    letter-spacing:-0.039em;
  }
  #g-historialvotaciones-small .g-cstyle14 {
    letter-spacing:-0.009em;
  }
  #g-historialvotaciones-small .g-cstyle15 {
    letter-spacing:-0.03em;
  }
  #g-historialvotaciones-small .g-cstyle16 {
    letter-spacing:-0.059em;
  }
  #g-historialvotaciones-small .g-cstyle17 {
    letter-spacing:-0.015em;
  }
  #g-historialvotaciones-small .g-cstyle18 {
    letter-spacing:0.029em;
  }
  #g-historialvotaciones-small .g-cstyle19 {
    letter-spacing:0.025em;
  }
  #g-historialvotaciones-small .g-cstyle20 {
    letter-spacing:-0.054em;
  }
  #g-historialvotaciones-small .g-cstyle21 {
    letter-spacing:-0.022em;
  }
  #g-historialvotaciones-small .g-cstyle22 {
    letter-spacing:-0.037em;
  }
  #g-historialvotaciones-small .g-cstyle23 {
    letter-spacing:-0.016em;
  }
  #g-historialvotaciones-small .g-cstyle24 {
    letter-spacing:-0.024em;
  }
  #g-historialvotaciones-small .g-cstyle25 {
    letter-spacing:-0.063em;
  }
  #g-historialvotaciones-small .g-cstyle26 {
    letter-spacing:-0.007em;
  }

`

const html = props => `
<div id="g-historialvotaciones-box" class="ai2html">


  <!-- Artboard: large -->
  <div id="g-historialvotaciones-large" class="g-artboard" style="width:1280px; height:1105.83996582031px;" data-aspect-ratio="1.157" data-min-width="1280">
<div style=""></div>
    <img id="g-historialvotaciones-large-img" class="g-aiImg" alt="" src="${img0}"/>
    <div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:7.6892%;margin-top:-25px;left:4.699%;width:587px;">
      <p class="g-pstyle0">HISTORIAL DE  <span class="g-cstyle0">V</span>O<span class="g-cstyle1">T</span><span class="g-cstyle2">A</span>CIONES</p>
    </div>
    <div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:14.1158%;margin-top:-18.1px;left:4.5071%;width:292px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>ARLAMEN<span class="g-cstyle1">T</span>ARIAS </p>
    </div>
    <div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:14.1159%;margin-top:-18.1px;left:69.7249%;width:191px;">
      <p class="g-pstyle1">PRIMARIAS </p>
    </div>
    <div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:14.1159%;margin-top:-18.1px;left:36.6968%;width:292px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>ARLAMEN<span class="g-cstyle4">T</span>ARIAS </p>
    </div>
    <div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:17.0957%;margin-top:-17.1px;left:4.5071%;width:132px;">
      <p class="g-pstyle2">Año 2<span class="g-cstyle5">0</span><span class="g-cstyle6">1</span>3 </p>
    </div>
    <div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:17.0957%;margin-top:-17.1px;left:36.6959%;width:130px;">
      <p class="g-pstyle2">Año 2<span class="g-cstyle5">0</span><span class="g-cstyle7">1</span>7 </p>
    </div>
    <div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:17.1904%;margin-top:-18.1px;left:69.7249%;width:276px;">
      <p class="g-pstyle1">PRESIDENCIALES </p>
    </div>
    <div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.8085%;margin-top:-17.1px;left:4.5071%;width:169px;">
      <p class="g-pstyle2">Exdistri<span class="g-cstyle8">t</span>o 60*</p>
    </div>
    <div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:19.8085%;margin-top:-17.1px;left:36.6959%;width:148px;">
      <p class="g-pstyle2">Distri<span class="g-cstyle8">t</span>o 28*</p>
    </div>
    <div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:20.0798%;margin-top:-17.1px;left:69.7239%;width:326px;">
      <p class="g-pstyle2">Año 20<span class="g-cstyle9">2</span><span class="g-cstyle10">1</span>, Apruebo Digni<span class="g-cstyle11">d</span>ad</p>
    </div>
    <div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.3122%;margin-top:-22.9px;left:70.1897%;width:145px;">
      <p class="g-pstyle3">60<span class="g-cstyle12">,</span>42%</p>
    </div>
    <div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.4026%;margin-top:-22.9px;left:37.0925%;width:143px;">
      <p class="g-pstyle3">32,82%</p>
    </div>
    <div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.5835%;margin-top:-22.9px;left:5.0852%;width:138px;">
      <p class="g-pstyle3">26,18%</p>
    </div>
    <div id="g-ai0-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:31.9659%;margin-top:-24.5px;left:11.0542%;width:123px;">
      <p class="g-pstyle4">15<span class="g-cstyle13">.</span>4<span class="g-cstyle14">1</span>7</p>
    </div>
    <div id="g-ai0-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:32.2371%;margin-top:-24.5px;left:42.5016%;width:133px;">
      <p class="g-pstyle4">18.626</p>
    </div>
    <div id="g-ai0-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.2763%;margin-top:-18.1px;left:11.1797%;width:119px;">
      <p class="g-pstyle1"><span class="g-cstyle2">V</span>OTOS</p>
    </div>
    <div id="g-ai0-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.9447%;margin-top:-24.5px;left:73.5212%;width:190px;">
      <p class="g-pstyle5">1.059.060</p>
    </div>
    <div id="g-ai0-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.5475%;margin-top:-18.1px;left:43.0396%;width:119px;">
      <p class="g-pstyle1"><span class="g-cstyle0">V</span>OTOS</p>
    </div>
    <div id="g-ai0-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.2551%;margin-top:-18.1px;left:76.2784%;width:119px;">
      <p class="g-pstyle6"><span class="g-cstyle0">V</span>OTOS</p>
    </div>
    <div id="g-ai0-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.7132%;margin-top:-18.1px;left:37.1825%;width:289px;">
      <p class="g-pstyle1">SEGUN<span class="g-cstyle13">D</span>A VUE<span class="g-cstyle1">L</span><span class="g-cstyle4">T</span>A </p>
    </div>
    <div id="g-ai0-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.8941%;margin-top:-18.1px;left:5.2196%;width:277px;">
      <p class="g-pstyle1">PRIMERA VUE<span class="g-cstyle4">LT</span>A</p>
    </div>
    <div id="g-ai0-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:58.7878%;margin-top:-18.1px;left:37.1825%;width:235px;">
      <p class="g-pstyle1">PRESIDENCIAL</p>
    </div>
    <div id="g-ai0-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:58.8782%;margin-top:-18.1px;left:5.2196%;width:235px;">
      <p class="g-pstyle1">PRESIDENCIAL</p>
    </div>
    <div id="g-ai0-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:61.6772%;margin-top:-17.1px;left:37.1825%;width:126px;">
      <p class="g-pstyle2">Año 20<span class="g-cstyle9">2</span>1</p>
    </div>
    <div id="g-ai0-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:61.858%;margin-top:-17.1px;left:5.2202%;width:126px;">
      <p class="g-pstyle2">Año 20<span class="g-cstyle9">2</span>1</p>
    </div>
    <div id="g-ai0-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.4575%;margin-top:-22.9px;left:7.4538%;width:142px;">
      <p class="g-pstyle3">25,82%</p>
    </div>
    <div id="g-ai0-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.6383%;margin-top:-22.9px;left:40.9894%;width:121px;">
      <p class="g-pstyle3">55,9%</p>
    </div>
    <div id="g-ai0-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:77.2708%;margin-top:-24.5px;left:11.2433%;width:180px;">
      <p class="g-pstyle5">1.815.0<span class="g-cstyle15">2</span>4</p>
    </div>
    <div id="g-ai0-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:77.9942%;margin-top:-24.5px;left:43.2943%;width:179px;">
      <p class="g-pstyle5">4.6<span class="g-cstyle16">1</span><span class="g-cstyle17">7</span>.385</p>
    </div>
    <div id="g-ai0-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.5812%;margin-top:-18.1px;left:13.6205%;width:119px;">
      <p class="g-pstyle6"><span class="g-cstyle2">V</span>OTOS</p>
    </div>
    <div id="g-ai0-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.5812%;margin-top:-18.1px;left:16.579%;width:44px;">
      <p class="g-pstyle7">X</p>
    </div>
    <div id="g-ai0-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.3046%;margin-top:-18.1px;left:45.6046%;width:119px;">
      <p class="g-pstyle6"><span class="g-cstyle0">V</span>OTOS</p>
    </div>
    <div id="g-ai0-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.9127%;margin-top:-13.6px;left:5.0903%;width:1168px;">
      <p class="g-pstyle8">*Ambos distri<span class="g-cstyle18">t</span>os representan a las comunas de Antá<span class="g-cstyle19">r</span>tica, Cabo de Hornos, Laguna Blanca, Natales, <span class="g-cstyle13">P</span>o<span class="g-cstyle19">r</span><span class="g-cstyle18">v</span>eni<span class="g-cstyle20">r</span>, Prim<span class="g-cstyle21">a</span><span class="g-cstyle18">v</span>era, Punta Arenas, </p>
    </div>
    <div id="g-ai0-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.083%;margin-top:-13.6px;left:5.0903%;width:453px;">
      <p class="g-pstyle8">Río <span class="g-cstyle22">V</span>e<span class="g-cstyle23">r</span>de, San Gregorio, Timau<span class="g-cstyle24">k</span>el, <span class="g-cstyle25">T</span>orres del <span class="g-cstyle10">P</span>aine</p>
    </div>
  </div>

  <!-- Artboard: small -->
  <div id="g-historialvotaciones-small" class="g-artboard" style="max-width: 360px;max-height: 2572px" data-aspect-ratio="0.14" data-min-width="0" data-max-width="1279">
<div style="padding: 0 0 714.5445% 0;"></div>
    <img id="g-historialvotaciones-small-img" class="g-aiImg" alt="" src="${img1}"/>
    <div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:2.8181%;margin-top:-24.5px;left:4.2257%;width:312px;">
      <p class="g-pstyle0">HISTORIAL DE </p>
    </div>
    <div id="g-ai1-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:4.5674%;margin-top:-24.5px;left:4.0147%;width:274px;">
      <p class="g-pstyle0"><span class="g-cstyle0">V</span>O<span class="g-cstyle1">T</span><span class="g-cstyle2">A</span>CIONES</p>
    </div>
    <div id="g-ai1-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:7.4289%;margin-top:-18.1px;left:5.6146%;width:292px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>ARLAMEN<span class="g-cstyle1">T</span>ARIAS </p>
    </div>
    <div id="g-ai1-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:8.6711%;margin-top:-17.1px;left:5.6146%;width:132px;">
      <p class="g-pstyle2">Año 2<span class="g-cstyle4">0</span><span class="g-cstyle5">1</span>3 </p>
    </div>
    <div id="g-ai1-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.8373%;margin-top:-17.1px;left:5.6146%;width:169px;">
      <p class="g-pstyle2">Exdistri<span class="g-cstyle6">t</span>o 60*</p>
    </div>
    <div id="g-ai1-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:12.5143%;margin-top:-22.9px;left:13.0072%;width:138px;">
      <p class="g-pstyle3">26,18%</p>
    </div>
    <div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:15.2969%;margin-top:-24.5px;left:34.2303%;width:123px;">
      <p class="g-pstyle0">15<span class="g-cstyle7">.</span>4<span class="g-cstyle8">1</span>7</p>
    </div>
    <div id="g-ai1-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.72%;margin-top:-18.1px;left:34.6763%;width:119px;">
      <p class="g-pstyle1"><span class="g-cstyle2">V</span>OTOS</p>
    </div>
    <div id="g-ai1-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:24.3006%;margin-top:-18.1px;left:5.6146%;width:292px;">
      <p class="g-pstyle1"><span class="g-cstyle3">P</span>ARLAMEN<span class="g-cstyle1">T</span>ARIAS </p>
    </div>
    <div id="g-ai1-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.5427%;margin-top:-17.1px;left:5.6146%;width:130px;">
      <p class="g-pstyle2">Año 2<span class="g-cstyle4">0</span><span class="g-cstyle9">1</span>7 </p>
    </div>
    <div id="g-ai1-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.709%;margin-top:-17.1px;left:5.6146%;width:148px;">
      <p class="g-pstyle2">Distri<span class="g-cstyle6">t</span>o 28*</p>
    </div>
    <div id="g-ai1-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.9972%;margin-top:-22.9px;left:12.2972%;width:143px;">
      <p class="g-pstyle3">32,82%</p>
    </div>
    <div id="g-ai1-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:31.9353%;margin-top:-24.5px;left:31.5272%;width:133px;">
      <p class="g-pstyle0">18.626</p>
    </div>
    <div id="g-ai1-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3584%;margin-top:-18.1px;left:33.4401%;width:119px;">
      <p class="g-pstyle1"><span class="g-cstyle0">V</span>OTOS</p>
    </div>
    <div id="g-ai1-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.8224%;margin-top:-18.1px;left:5.6149%;width:191px;">
      <p class="g-pstyle1">PRIMARIAS </p>
    </div>
    <div id="g-ai1-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.1441%;margin-top:-18.1px;left:5.6149%;width:276px;">
      <p class="g-pstyle1">PRESIDENCIALES </p>
    </div>
    <div id="g-ai1-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.3863%;margin-top:-17.1px;left:5.6149%;width:126px;">
      <p class="g-pstyle2">Año 20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai1-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.5525%;margin-top:-17.1px;left:5.6149%;width:210px;">
      <p class="g-pstyle2">Apruebo Digni<span class="g-cstyle11">d</span>ad</p>
    </div>
    <div id="g-ai1-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.9185%;margin-top:-22.9px;left:11.7972%;width:145px;">
      <p class="g-pstyle3">60<span class="g-cstyle12">,</span>42%</p>
    </div>
    <div id="g-ai1-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:51.4893%;margin-top:-24.5px;left:23.6368%;width:190px;">
      <p class="g-pstyle4">1.059.060</p>
    </div>
    <div id="g-ai1-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.9124%;margin-top:-18.1px;left:33.4401%;width:119px;">
      <p class="g-pstyle5"><span class="g-cstyle0">V</span>OTOS</p>
    </div>
    <div id="g-ai1-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:60.1432%;margin-top:-18.1px;left:5.6146%;width:277px;">
      <p class="g-pstyle1">PRIMERA VUE<span class="g-cstyle13">LT</span>A</p>
    </div>
    <div id="g-ai1-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:61.4649%;margin-top:-18.1px;left:5.6146%;width:235px;">
      <p class="g-pstyle1">PRESIDENCIAL</p>
    </div>
    <div id="g-ai1-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:62.707%;margin-top:-17.1px;left:5.6146%;width:126px;">
      <p class="g-pstyle2">Año 20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai1-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.6843%;margin-top:-22.9px;left:13.5565%;width:142px;">
      <p class="g-pstyle3">25,82%</p>
    </div>
    <div id="g-ai1-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.3717%;margin-top:-24.5px;left:27.0301%;width:180px;">
      <p class="g-pstyle4">1.815.0<span class="g-cstyle14">2</span>4</p>
    </div>
    <div id="g-ai1-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.7949%;margin-top:-18.1px;left:35.4822%;width:119px;">
      <p class="g-pstyle5"><span class="g-cstyle2">V</span>OTOS</p>
    </div>
    <div id="g-ai1-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.7949%;margin-top:-18.1px;left:46.0014%;width:44px;">
      <p class="g-pstyle6">X</p>
    </div>
    <div id="g-ai1-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:76.7427%;margin-top:-18.1px;left:5.6146%;width:289px;">
      <p class="g-pstyle1">SEGUN<span class="g-cstyle7">D</span>A VUE<span class="g-cstyle1">L</span><span class="g-cstyle13">T</span>A </p>
    </div>
    <div id="g-ai1-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:78.0644%;margin-top:-18.1px;left:5.6146%;width:235px;">
      <p class="g-pstyle1">PRESIDENCIAL</p>
    </div>
    <div id="g-ai1-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.3066%;margin-top:-17.1px;left:5.6146%;width:126px;">
      <p class="g-pstyle2">Año 20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai1-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.4005%;margin-top:-22.9px;left:19.1503%;width:121px;">
      <p class="g-pstyle3">55,9%</p>
    </div>
    <div id="g-ai1-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:86.3212%;margin-top:-24.5px;left:27.3456%;width:178px;">
      <p class="g-pstyle4">4.6<span class="g-cstyle15">1</span><span class="g-cstyle16">7</span>.385</p>
    </div>
    <div id="g-ai1-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:87.7443%;margin-top:-18.1px;left:35.5601%;width:119px;">
      <p class="g-pstyle5"><span class="g-cstyle2">V</span>OTOS</p>
    </div>
    <div id="g-ai1-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:94.6851%;margin-top:-13.6px;left:5.6146%;width:321px;">
      <p class="g-pstyle7">*Ambos distri<span class="g-cstyle17">t</span>os representan a las </p>
    </div>
    <div id="g-ai1-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.5014%;margin-top:-13.6px;left:5.6146%;width:291px;">
      <p class="g-pstyle7">comunas de Antá<span class="g-cstyle18">r</span>tica, Cabo de </p>
    </div>
    <div id="g-ai1-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.3178%;margin-top:-13.6px;left:5.6146%;width:303px;">
      <p class="g-pstyle7">Hornos, Laguna Blanca, Natales, </p>
    </div>
    <div id="g-ai1-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.1342%;margin-top:-13.6px;left:5.6146%;width:318px;">
      <p class="g-pstyle7"><span class="g-cstyle6">P</span>o<span class="g-cstyle19">r</span><span class="g-cstyle17">v</span>eni<span class="g-cstyle20">r</span>, Prim<span class="g-cstyle21">a</span><span class="g-cstyle17">v</span>era, Punta Arenas, </p>
    </div>
    <div id="g-ai1-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.9505%;margin-top:-13.6px;left:5.6146%;width:318px;">
      <p class="g-pstyle7">Río <span class="g-cstyle22">V</span>e<span class="g-cstyle23">r</span>de, San Gregorio, Timau<span class="g-cstyle24">k</span>el, </p>
    </div>
    <div id="g-ai1-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.7669%;margin-top:-13.6px;left:5.6146%;width:157px;">
      <p class="g-pstyle7"><span class="g-cstyle25">T</span>orres del <span class="g-cstyle26">P</span>aine</p>
    </div>
  </div>


</div>
`

const containerId = 'g-historialvotaciones-box'
const namespace = 'g-'
const name = 'historialvotaciones'

export default makeAi2React({ html, styles, containerId, namespace, name })

/* End ai2react - 2022-03-11 09:52 */
