/* Generated by ai2react v0.102.0 - 2022-03-11 09:52 */
/* ai file: historialpolitico.ai */

import { makeAi2React } from '../src'
const img0 =
  'https://especiales.latercera.com/boric-presidente-assets/v3/historialpolitico-large.jpg'
const img1 =
  'https://especiales.latercera.com/boric-presidente-assets/v3/historialpolitico-small.jpg'

const styles = `
  #g-historialpolitico-box ,
  #g-historialpolitico-box .g-artboard {
    margin:0 auto;
  }
  #g-historialpolitico-box p {
    margin:0;
  }
  #g-historialpolitico-box .g-aiAbs {
    position:absolute;
  }
  #g-historialpolitico-box .g-aiImg {
    position:absolute;
    top:0;
    display:block;
    width:100% !important;
  }
  #g-historialpolitico-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-historialpolitico-box .g-aiPointText p { white-space: nowrap; }
  #g-historialpolitico-large {
    position:relative;
    overflow:hidden;
  }
  #g-historialpolitico-large p {
    font-weight:500;
    line-height:24px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:20px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-historialpolitico-large .g-pstyle0 {
    line-height:32px;
    height:32px;
    font-size:27px;
  }
  #g-historialpolitico-large .g-pstyle1 {
    line-height:46px;
    height:46px;
    font-size:38px;
  }
  #g-historialpolitico-large .g-pstyle2 {
    line-height:28px;
    height:28px;
    font-size:23px;
  }
  #g-historialpolitico-large .g-pstyle3 {
    line-height:29px;
    height:29px;
    font-size:24px;
  }
  #g-historialpolitico-large .g-pstyle4 {
    height:24px;
  }
  #g-historialpolitico-large .g-cstyle0 {
    letter-spacing:-0.019em;
  }
  #g-historialpolitico-large .g-cstyle1 {
    letter-spacing:-0.04em;
  }
  #g-historialpolitico-large .g-cstyle2 {
    letter-spacing:-0.038em;
  }
  #g-historialpolitico-large .g-cstyle3 {
    letter-spacing:-0.032em;
  }
  #g-historialpolitico-large .g-cstyle4 {
    letter-spacing:-0.018em;
  }
  #g-historialpolitico-large .g-cstyle5 {
    letter-spacing:-0.037em;
  }
  #g-historialpolitico-large .g-cstyle6 {
    letter-spacing:-0.008em;
  }
  #g-historialpolitico-large .g-cstyle7 {
    letter-spacing:-0.014em;
  }
  #g-historialpolitico-large .g-cstyle8 {
    letter-spacing:-0.034em;
  }
  #g-historialpolitico-large .g-cstyle9 {
    letter-spacing:-0.068em;
  }
  #g-historialpolitico-large .g-cstyle10 {
    letter-spacing:-0.006em;
  }
  #g-historialpolitico-large .g-cstyle11 {
    letter-spacing:-0.013em;
  }
  #g-historialpolitico-large .g-cstyle12 {
    letter-spacing:-0.009em;
  }
  #g-historialpolitico-large .g-cstyle13 {
    letter-spacing:-0.016em;
  }
  #g-historialpolitico-large .g-cstyle14 {
    letter-spacing:-0.017em;
  }
  #g-historialpolitico-large .g-cstyle15 {
    letter-spacing:-0.022em;
  }
  #g-historialpolitico-large .g-cstyle16 {
    letter-spacing:-0.015em;
  }
  #g-historialpolitico-large .g-cstyle17 {
    letter-spacing:-0.004em;
  }
  #g-historialpolitico-large .g-cstyle18 {
    letter-spacing:0.028em;
  }
  #g-historialpolitico-large .g-cstyle19 {
    letter-spacing:0.025em;
  }
  #g-historialpolitico-large .g-cstyle20 {
    letter-spacing:-0.054em;
  }
  #g-historialpolitico-large .g-cstyle21 {
    letter-spacing:-0.024em;
  }
  #g-historialpolitico-large .g-cstyle22 {
    letter-spacing:-0.064em;
  }
  #g-historialpolitico-large .g-cstyle23 {
    letter-spacing:-0.007em;
  }
  #g-historialpolitico-small {
    position:relative;
    overflow:hidden;
  }
  #g-historialpolitico-small p {
    font-weight:500;
    line-height:24px;
    height:auto;
    filter:alpha(opacity=100);
    -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity:1;
    letter-spacing:0em;
    font-size:20px;
    text-align:left;
    color:rgb(0,0,0);
    text-transform:none;
    padding-bottom:0;
    padding-top:0;
    mix-blend-mode:normal;
    font-style:normal;
    position:static;
  }
  #g-historialpolitico-small .g-pstyle0 {
    line-height:46px;
    height:46px;
    font-size:38px;
  }
  #g-historialpolitico-small .g-pstyle1 {
    line-height:32px;
    height:32px;
    font-size:27px;
  }
  #g-historialpolitico-small .g-pstyle2 {
    line-height:31px;
    height:31px;
    font-size:26px;
  }
  #g-historialpolitico-small .g-pstyle3 {
    line-height:28px;
    height:28px;
    font-size:23px;
  }
  #g-historialpolitico-small .g-pstyle4 {
    height:24px;
  }
  #g-historialpolitico-small .g-cstyle0 {
    letter-spacing:-0.04em;
  }
  #g-historialpolitico-small .g-cstyle1 {
    letter-spacing:-0.009em;
  }
  #g-historialpolitico-small .g-cstyle2 {
    letter-spacing:-0.016em;
  }
  #g-historialpolitico-small .g-cstyle3 {
    letter-spacing:-0.038em;
  }
  #g-historialpolitico-small .g-cstyle4 {
    letter-spacing:-0.032em;
  }
  #g-historialpolitico-small .g-cstyle5 {
    letter-spacing:-0.018em;
  }
  #g-historialpolitico-small .g-cstyle6 {
    letter-spacing:-0.037em;
  }
  #g-historialpolitico-small .g-cstyle7 {
    letter-spacing:-0.008em;
  }
  #g-historialpolitico-small .g-cstyle8 {
    letter-spacing:-0.014em;
  }
  #g-historialpolitico-small .g-cstyle9 {
    letter-spacing:-0.017em;
  }
  #g-historialpolitico-small .g-cstyle10 {
    letter-spacing:-0.034em;
  }
  #g-historialpolitico-small .g-cstyle11 {
    letter-spacing:-0.015em;
  }
  #g-historialpolitico-small .g-cstyle12 {
    letter-spacing:-0.068em;
  }
  #g-historialpolitico-small .g-cstyle13 {
    letter-spacing:-0.006em;
  }
  #g-historialpolitico-small .g-cstyle14 {
    letter-spacing:-0.022em;
  }
  #g-historialpolitico-small .g-cstyle15 {
    letter-spacing:-0.013em;
  }
  #g-historialpolitico-small .g-cstyle16 {
    letter-spacing:-0.02em;
  }
  #g-historialpolitico-small .g-cstyle17 {
    letter-spacing:-0.004em;
  }
  #g-historialpolitico-small .g-cstyle18 {
    letter-spacing:0.029em;
  }
  #g-historialpolitico-small .g-cstyle19 {
    letter-spacing:0.025em;
  }
  #g-historialpolitico-small .g-cstyle20 {
    letter-spacing:-0.054em;
  }
  #g-historialpolitico-small .g-cstyle21 {
    letter-spacing:-0.024em;
  }
  #g-historialpolitico-small .g-cstyle22 {
    letter-spacing:-0.063em;
  }
  #g-historialpolitico-small .g-cstyle23 {
    letter-spacing:-0.007em;
  }

`

const html = props => `
<div id="g-historialpolitico-box" class="ai2html">


  <!-- Artboard: large -->
  <div id="g-historialpolitico-large" class="g-artboard" style="width:1280px; height:691.398010253906px;" data-aspect-ratio="1.851" data-min-width="1280">
<div style=""></div>
    <img id="g-historialpolitico-large-img" class="g-aiImg" alt="" src="${img0}"/>
    <div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.4099%;margin-top:-17.1px;left:58.7019%;width:211px;">
      <p class="g-pstyle0">C<span class="g-cstyle0">O</span>ALICIONES</p>
    </div>
    <div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:11.312%;margin-top:-26.2px;left:2.6295%;width:435px;">
      <p class="g-pstyle1">HISTORIAL POLÍTICO</p>
    </div>
    <div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:26.9106%;margin-top:-17.1px;left:2.6305%;width:192px;">
      <p class="g-pstyle0">MILI<span class="g-cstyle1">T</span>ANCIA</p>
    </div>
    <div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:2.9813%;width:76px;">
      <p class="g-pstyle2">2008</p>
    </div>
    <div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:9.5794%;width:76px;">
      <p class="g-pstyle2">2009</p>
    </div>
    <div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:16.2404%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle3">1</span>0</p>
    </div>
    <div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:22.8259%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle4">1</span>1</p>
    </div>
    <div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:29.4079%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle5">0</span>12</p>
    </div>
    <div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:36.0132%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle6">1</span>3</p>
    </div>
    <div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:42.6311%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle3">1</span>4</p>
    </div>
    <div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:49.213%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle7">1</span>5</p>
    </div>
    <div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:55.8292%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle8">1</span>6</p>
    </div>
    <div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:62.4578%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle9">1</span>7</p>
    </div>
    <div id="g-ai0-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:69.0002%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle10">1</span>8</p>
    </div>
    <div id="g-ai0-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:75.6038%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle11">1</span>9</p>
    </div>
    <div id="g-ai0-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:82.1552%;width:76px;">
      <p class="g-pstyle2">2020</p>
    </div>
    <div id="g-ai0-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:33.3942%;margin-top:-15.9px;left:88.7839%;width:75px;">
      <p class="g-pstyle2">20<span class="g-cstyle8">2</span>1</p>
    </div>
    <div id="g-ai0-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.9869%;margin-top:-16.5px;left:3.8261%;width:115px;">
      <p class="g-pstyle3">Iz<span class="g-cstyle12">q</span>uie<span class="g-cstyle13">r</span>da</p>
    </div>
    <div id="g-ai0-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.9869%;margin-top:-16.5px;left:56.7292%;width:140px;">
      <p class="g-pstyle3">M<span class="g-cstyle14">o</span>vimien<span class="g-cstyle7">t</span>o</p>
    </div>
    <div id="g-ai0-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.9869%;margin-top:-16.5px;left:76.5648%;width:158px;">
      <p class="g-pstyle3">Co<span class="g-cstyle15">n</span><span class="g-cstyle16">v</span>ergencia</p>
    </div>
    <div id="g-ai0-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.4581%;margin-top:-16.5px;left:3.8261%;width:125px;">
      <p class="g-pstyle3"><span class="g-cstyle13">A</span>utónoma</p>
    </div>
    <div id="g-ai0-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.4581%;margin-top:-16.5px;left:56.7292%;width:149px;">
      <p class="g-pstyle3"><span class="g-cstyle13">A</span>u<span class="g-cstyle16">t</span>onomista</p>
    </div>
    <div id="g-ai0-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:43.4581%;margin-top:-16.5px;left:76.5648%;width:83px;">
      <p class="g-pstyle3">Social</p>
    </div>
    <div id="g-ai0-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.2585%;margin-top:-18.3px;left:2.6296%;width:439px;">
      <p class="g-pstyle0">CARGOS DE REPRESEN<span class="g-cstyle1">T</span><span class="g-cstyle17">A</span>CIÓN</p>
    </div>
    <div id="g-ai0-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:2.9813%;width:76px;">
      <p class="g-pstyle2">2008</p>
    </div>
    <div id="g-ai0-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:9.5794%;width:76px;">
      <p class="g-pstyle2">2009</p>
    </div>
    <div id="g-ai0-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:16.2404%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle3">1</span>0</p>
    </div>
    <div id="g-ai0-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:22.8259%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle4">1</span>1</p>
    </div>
    <div id="g-ai0-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:29.4079%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle5">0</span>12</p>
    </div>
    <div id="g-ai0-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:36.0132%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle6">1</span>3</p>
    </div>
    <div id="g-ai0-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:42.6311%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle3">1</span>4</p>
    </div>
    <div id="g-ai0-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:49.213%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle7">1</span>5</p>
    </div>
    <div id="g-ai0-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:55.8292%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle8">1</span>6</p>
    </div>
    <div id="g-ai0-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:62.4578%;width:74px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle9">1</span>7</p>
    </div>
    <div id="g-ai0-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:69.0002%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle10">1</span>8</p>
    </div>
    <div id="g-ai0-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:75.6038%;width:75px;">
      <p class="g-pstyle2">2<span class="g-cstyle2">0</span><span class="g-cstyle11">1</span>9</p>
    </div>
    <div id="g-ai0-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:82.1552%;width:76px;">
      <p class="g-pstyle2">2020</p>
    </div>
    <div id="g-ai0-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.8545%;margin-top:-15.9px;left:88.7533%;width:76px;">
      <p class="g-pstyle2">2022</p>
    </div>
    <div id="g-ai0-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:78.0258%;margin-top:-16.5px;left:23.838%;width:130px;">
      <p class="g-pstyle3">Presiden<span class="g-cstyle4">t</span>e</p>
    </div>
    <div id="g-ai0-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:78.0258%;margin-top:-16.5px;left:43.8686%;width:114px;">
      <p class="g-pstyle3">Diputado</p>
    </div>
    <div id="g-ai0-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:78.0258%;margin-top:-16.5px;left:69.8355%;width:114px;">
      <p class="g-pstyle3">Diputado</p>
    </div>
    <div id="g-ai0-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:78.0258%;margin-top:-16.5px;left:89.778%;width:130px;">
      <p class="g-pstyle3">Presiden<span class="g-cstyle4">t</span>e</p>
    </div>
    <div id="g-ai0-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.497%;margin-top:-16.5px;left:43.8686%;width:149px;">
      <p class="g-pstyle3">Exdistri<span class="g-cstyle16">t</span>o 60</p>
    </div>
    <div id="g-ai0-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.497%;margin-top:-16.5px;left:69.8355%;width:143px;">
      <p class="g-pstyle3">Distri<span class="g-cstyle16">t</span>o 28*</p>
    </div>
    <div id="g-ai0-45" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.497%;margin-top:-16.5px;left:89.778%;width:72px;">
      <p class="g-pstyle3">de la</p>
    </div>
    <div id="g-ai0-46" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:82.0756%;margin-top:-16.5px;left:23.838%;width:132px;">
      <p class="g-pstyle3">de la FECH</p>
    </div>
    <div id="g-ai0-47" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.9682%;margin-top:-16.5px;left:89.778%;width:122px;">
      <p class="g-pstyle3"><span class="g-cstyle14">R</span>epública</p>
    </div>
    <div id="g-ai0-48" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:91.357%;margin-top:-13.6px;left:2.6296%;width:834px;">
      <p class="g-pstyle4">*Antiguo distri<span class="g-cstyle13">t</span>o 60, co<span class="g-cstyle12">m</span>pues<span class="g-cstyle13">t</span>o por las comunas de Antá<span class="g-cstyle18">r</span>tica, Cabo de Hornos, Laguna Blanca, </p>
    </div>
    <div id="g-ai0-49" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:94.8282%;margin-top:-13.6px;left:2.6296%;width:824px;">
      <p class="g-pstyle4">Natales, <span class="g-cstyle16">P</span>o<span class="g-cstyle19">r</span><span class="g-cstyle16">v</span>eni<span class="g-cstyle20">r</span>, Prim<span class="g-cstyle15">a</span><span class="g-cstyle16">v</span>era, Punta Arenas, Río <span class="g-cstyle1">V</span>e<span class="g-cstyle13">r</span>de, San Gregorio, Timau<span class="g-cstyle21">k</span>el, <span class="g-cstyle22">T</span>orres del <span class="g-cstyle23">P</span>aine</p>
    </div>
  </div>

  <!-- Artboard: small -->
  <div id="g-historialpolitico-small" class="g-artboard" style="max-width: 360px;max-height: 2076px" data-aspect-ratio="0.173" data-min-width="0" data-max-width="1279">
<div style="padding: 0 0 576.6111% 0;"></div>
    <img id="g-historialpolitico-small-img" class="g-aiImg" alt="" src="${img1}"/>
    <div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:3.3477%;margin-top:-24.5px;left:4.9544%;width:239px;">
      <p class="g-pstyle0">HISTORIAL</p>
    </div>
    <div id="g-ai1-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:5.4538%;margin-top:-26.2px;left:4.9544%;width:209px;">
      <p class="g-pstyle0">POLÍTICO</p>
    </div>
    <div id="g-ai1-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.2041%;margin-top:-17.1px;left:6.2641%;width:192px;">
      <p class="g-pstyle1">MILI<span class="g-cstyle0">T</span>ANCIA</p>
    </div>
    <div id="g-ai1-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:11.7368%;margin-top:-17.6px;left:37.3937%;width:123px;">
      <p class="g-pstyle2">Iz<span class="g-cstyle1">q</span>uie<span class="g-cstyle2">r</span>da</p>
    </div>
    <div id="g-ai1-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:11.6527%;margin-top:-15.9px;left:6.2646%;width:76px;">
      <p class="g-pstyle3">2008</p>
    </div>
    <div id="g-ai1-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:13.0857%;margin-top:-17.6px;left:37.3937%;width:134px;">
      <p class="g-pstyle2"><span class="g-cstyle2">A</span>utónoma</p>
    </div>
    <div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:14.0132%;margin-top:-15.9px;left:6.2646%;width:76px;">
      <p class="g-pstyle3">2009</p>
    </div>
    <div id="g-ai1-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:16.3256%;margin-top:-15.9px;left:6.712%;width:74px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>0</p>
    </div>
    <div id="g-ai1-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:18.6861%;margin-top:-15.9px;left:6.6225%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle5">1</span>1</p>
    </div>
    <div id="g-ai1-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:21.0467%;margin-top:-15.9px;left:6.5074%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle6">0</span>12</p>
    </div>
    <div id="g-ai1-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:23.359%;margin-top:-15.9px;left:6.5649%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle7">1</span>3</p>
    </div>
    <div id="g-ai1-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:25.7196%;margin-top:-15.9px;left:6.712%;width:74px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>4</p>
    </div>
    <div id="g-ai1-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:28.0801%;margin-top:-15.9px;left:6.597%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle8">1</span>5</p>
    </div>
    <div id="g-ai1-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.3802%;margin-top:-17.6px;left:37.3937%;width:150px;">
      <p class="g-pstyle2">M<span class="g-cstyle9">o</span>vimien<span class="g-cstyle8">t</span>o</p>
    </div>
    <div id="g-ai1-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.3925%;margin-top:-15.9px;left:6.7247%;width:74px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle10">1</span>6</p>
    </div>
    <div id="g-ai1-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:31.7291%;margin-top:-17.6px;left:37.3937%;width:159px;">
      <p class="g-pstyle2"><span class="g-cstyle2">A</span>u<span class="g-cstyle11">t</span>onomista</p>
    </div>
    <div id="g-ai1-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:32.753%;margin-top:-15.9px;left:6.9485%;width:74px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle12">1</span>7</p>
    </div>
    <div id="g-ai1-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:35.1135%;margin-top:-15.9px;left:6.5522%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle13">1</span>8</p>
    </div>
    <div id="g-ai1-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.51%;margin-top:-17.6px;left:37.3937%;width:170px;">
      <p class="g-pstyle2">Co<span class="g-cstyle14">n</span><span class="g-cstyle11">v</span>ergencia</p>
    </div>
    <div id="g-ai1-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:37.4259%;margin-top:-15.9px;left:6.5907%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle15">1</span>9</p>
    </div>
    <div id="g-ai1-21" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:38.8589%;margin-top:-17.6px;left:37.3937%;width:88px;">
      <p class="g-pstyle2">Social</p>
    </div>
    <div id="g-ai1-22" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.7864%;margin-top:-15.9px;left:6.2646%;width:76px;">
      <p class="g-pstyle3">2020</p>
    </div>
    <div id="g-ai1-23" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:42.147%;margin-top:-15.9px;left:6.4884%;width:75px;">
      <p class="g-pstyle3">20<span class="g-cstyle10">2</span>1</p>
    </div>
    <div id="g-ai1-24" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:46.1538%;margin-top:-17.1px;left:4.7643%;width:211px;">
      <p class="g-pstyle1">C<span class="g-cstyle16">O</span>ALICIONES</p>
    </div>
    <div id="g-ai1-25" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:54.4879%;margin-top:-17.1px;left:4.5983%;width:186px;">
      <p class="g-pstyle1">CARGOS DE </p>
    </div>
    <div id="g-ai1-26" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:55.9438%;margin-top:-18.3px;left:4.5983%;width:275px;">
      <p class="g-pstyle1">REPRESEN<span class="g-cstyle0">T</span><span class="g-cstyle17">A</span>CIÓN</p>
    </div>
    <div id="g-ai1-27" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:58.8152%;margin-top:-15.9px;left:6.2646%;width:76px;">
      <p class="g-pstyle3">2008</p>
    </div>
    <div id="g-ai1-28" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:61.1276%;margin-top:-15.9px;left:6.2646%;width:76px;">
      <p class="g-pstyle3">2009</p>
    </div>
    <div id="g-ai1-29" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:63.4881%;margin-top:-15.9px;left:6.712%;width:74px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>0</p>
    </div>
    <div id="g-ai1-30" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:65.8846%;margin-top:-17.6px;left:37.3937%;width:139px;">
      <p class="g-pstyle2">Presiden<span class="g-cstyle5">t</span>e</p>
    </div>
    <div id="g-ai1-31" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:65.8487%;margin-top:-15.9px;left:6.6225%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle5">1</span>1</p>
    </div>
    <div id="g-ai1-32" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.2335%;margin-top:-17.6px;left:37.3937%;width:141px;">
      <p class="g-pstyle2">de la FECH</p>
    </div>
    <div id="g-ai1-33" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:68.161%;margin-top:-15.9px;left:6.5074%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle6">0</span>12</p>
    </div>
    <div id="g-ai1-34" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:70.5216%;margin-top:-15.9px;left:6.5649%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle7">1</span>3</p>
    </div>
    <div id="g-ai1-35" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:72.8217%;margin-top:-17.6px;left:37.3937%;width:122px;">
      <p class="g-pstyle2">Diputado</p>
    </div>
    <div id="g-ai1-36" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:72.8339%;margin-top:-15.9px;left:6.712%;width:74px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle4">1</span>4</p>
    </div>
    <div id="g-ai1-37" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:74.1706%;margin-top:-17.6px;left:37.3937%;width:160px;">
      <p class="g-pstyle2">Exdistri<span class="g-cstyle11">t</span>o 60</p>
    </div>
    <div id="g-ai1-38" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.1945%;margin-top:-15.9px;left:6.597%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle8">1</span>5</p>
    </div>
    <div id="g-ai1-39" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:77.555%;margin-top:-15.9px;left:6.7247%;width:74px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle10">1</span>6</p>
    </div>
    <div id="g-ai1-40" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:79.8674%;margin-top:-15.9px;left:6.9485%;width:74px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle12">1</span>7</p>
    </div>
    <div id="g-ai1-41" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:82.312%;margin-top:-17.6px;left:37.3937%;width:122px;">
      <p class="g-pstyle2">Diputado</p>
    </div>
    <div id="g-ai1-42" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:82.2279%;margin-top:-15.9px;left:6.5522%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle13">1</span>8</p>
    </div>
    <div id="g-ai1-43" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:83.6609%;margin-top:-17.6px;left:37.3937%;width:153px;">
      <p class="g-pstyle2">Distri<span class="g-cstyle11">t</span>o 28*</p>
    </div>
    <div id="g-ai1-44" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:84.5884%;margin-top:-15.9px;left:6.5907%;width:75px;">
      <p class="g-pstyle3">2<span class="g-cstyle3">0</span><span class="g-cstyle15">1</span>9</p>
    </div>
    <div id="g-ai1-45" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:86.9008%;margin-top:-15.9px;left:6.2646%;width:76px;">
      <p class="g-pstyle3">2020</p>
    </div>
    <div id="g-ai1-46" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:89.2009%;margin-top:-17.6px;left:37.3937%;width:206px;">
      <p class="g-pstyle2">Presiden<span class="g-cstyle5">t</span>e de la </p>
    </div>
    <div id="g-ai1-47" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:89.2613%;margin-top:-15.9px;left:6.2646%;width:76px;">
      <p class="g-pstyle3">2022</p>
    </div>
    <div id="g-ai1-48" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.5498%;margin-top:-17.6px;left:37.3937%;width:131px;">
      <p class="g-pstyle2"><span class="g-cstyle9">R</span>epública</p>
    </div>
    <div id="g-ai1-49" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:93.1998%;margin-top:-13.6px;left:7.3448%;width:321px;">
      <p class="g-pstyle4">*Ambos distri<span class="g-cstyle11">t</span>os representan a las </p>
    </div>
    <div id="g-ai1-50" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:94.2114%;margin-top:-13.6px;left:7.3448%;width:291px;">
      <p class="g-pstyle4">comunas de Antá<span class="g-cstyle18">r</span>tica, Cabo de </p>
    </div>
    <div id="g-ai1-51" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.2231%;margin-top:-13.6px;left:7.3448%;width:303px;">
      <p class="g-pstyle4">Hornos, Laguna Blanca, Natales, </p>
    </div>
    <div id="g-ai1-52" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.2347%;margin-top:-13.6px;left:7.3448%;width:318px;">
      <p class="g-pstyle4"><span class="g-cstyle8">P</span>o<span class="g-cstyle19">r</span><span class="g-cstyle11">v</span>eni<span class="g-cstyle20">r</span>, Prim<span class="g-cstyle14">a</span><span class="g-cstyle11">v</span>era, Punta Arenas, </p>
    </div>
    <div id="g-ai1-53" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.2464%;margin-top:-13.6px;left:7.3448%;width:318px;">
      <p class="g-pstyle4">Río <span class="g-cstyle6">V</span>e<span class="g-cstyle2">r</span>de, San Gregorio, Timau<span class="g-cstyle21">k</span>el, </p>
    </div>
    <div id="g-ai1-54" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:98.258%;margin-top:-13.6px;left:7.3448%;width:157px;">
      <p class="g-pstyle4"><span class="g-cstyle22">T</span>orres del <span class="g-cstyle23">P</span>aine</p>
    </div>
  </div>


</div>
`

const containerId = 'g-historialpolitico-box'
const namespace = 'g-'
const name = 'historialpolitico'

export default makeAi2React({ html, styles, containerId, namespace, name })

/* End ai2react - 2022-03-11 09:52 */
